### ISSUE TITLE
Corebird doesn't load new tweets

### ISSUE THREAD

**Issue by martijnvandijk** [baedert/corebird#116]
Corebird doesn't seem to load new tweets, nor can I force it to refresh. I have to restart corebird to load new tweets. Version: 0.6.1

**Comment by MargaTintel** [comment]
Today I just started to use Corebird, but it still doesn't seem to load new tweets, nor can I force it to refresh. I have to restart corebird to load new tweets

**Comment by medeotl** [comment]
same issue as MargaTintel here (archlinux, compiled via AUR, version 1.0)

**Comment by baedert** [comment]
What? Doesn't load new tweets after a network reconnect? Doesn't load new tweets after you start it?

**Comment by medeotl** [comment]
it doesn't load new tweets after you start it

**Comment by medeotl** [comment]
this is the pastebin of what i get launching via terminal: http://pastebin.com/FJp9rYcx

**Comment by baedert** [comment]
Puh, a few questions:

- What is your local timezone set to?
- What is your Twitter timezone set to (in the Twitter preferences)?
- What's your local locale (i.e. on your normal pc where you run corebird)?

**Comment by medeotl** [comment]
tl:dr: it now work, thanks for your work, sorry for my mistakes

I'm in Italy
Twitter was set to GMT-03:00 (don't know why, corrected)
local time zone wasn't set yet (fresh installation of arch). I've tryied to set language = eng and time/keyboard/formats italian, no way (yet)
so i've set everything italian, resinstalled corebird, properly set manually time (it was +1hour, don't know why). Now everything work properly.
Sorry for having reported an issue that was just my set-up problem.
Keep up with the great work you are doing

**Comment by MargaTintel** [comment]
It works with me now too, timezones corrected, sorry for the set-up problems at my site.
Thanks for your effort.

Regards,
Marga
