### ISSUE TITLE
Cannot open links

### ISSUE THREAD

**Issue by madx** [baedert/corebird#149]
I cannot open links anymore in Corebird

I do not know if this is related to me installing a new version (#g8caa5ae) or the new GTK version (3.12.1)

I'm running ArchLinux

**Comment by uppercaseA** [comment]
I have this issue on Arch gnome 3.16.3. The gtk3-demo opens links as it should. On corebird when i click a link on feed nothing happen and when i open the post and click the link an I-beam cursor appears.

**Comment by baedert** [comment]
Not enough info, it works here and apparently everywhere else and the links in the corebird labels aren't any different than those in gtk3-demo.

**Comment by uppercaseA** [comment]
hmm if it helps "Source"  and "Twitter Web Client" don't work as well. What else could I test to find the problem? thank you, however

**Comment by baedert** [comment]
Can you activate them using the keyboard? Any console output (try to start with `G_MESSAGES_DEBUG=all corebird`). What version?

**Comment by uppercaseA** [comment]
wow, sorry I am completely dump. I thought i had pulled the latest version but apparently i had not. Everything works great now. Sorry for the confusion.
