### ISSUE TITLE
Remove notifications on exit

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#158]
Currently unseen notifications are still present even if corebird is already closed this is very confusing in some cases. Especially because Gnome restores unseen notifications on next login. So please remove all corebird notifications if corebird gets closed.

**Comment by baedert** [comment]
Is this still an issue? I improved the notification withdrawing a lot some time ago and haven't seen this happening since.

**Comment by baedert** [comment]
Shouldn't be a problem anymore with the newer notification withdrawing strategy.
