### ISSUE TITLE
Support Twitter's Mute-Feature

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#179]
Since a few weeks Twitter has a function to mute a person you follow. It would be very cool if corebird could support this function.

**Comment by HanFox** [comment]
Blocking stops all conversation, but muting allows you to filter someone's tweets, but still be able to interact with them if needs be (i.e. DMs and @mentions).

I'd like to be able to mute a few people, but still be able to keep following them.

The profiles page should show both the option of Blocking and Muting (unless I'm misinterpreting your last comment -- or the Twitter API handles Mutes in weird ways?).

**Comment by HanFox** [comment]
I know this is poor form, but I'm going to ping you @baedert so you can see if my comment above makes adding Mute viable for you now.

**Comment by andersbateva** [comment]
+baedert , I could not understand what you meant with "blocking _and_ muting". Are you thinking about blocking some people and muting some other people, or blocking _and_ muting the same people? The latter, I think isn't even possible. But the first, I think is necessary.

There are many categories of people, like: friend (follows the user and followed by the user), known (follows the user), neutral (doesn't follows), enemy (muted) and arch-enemy (blocked). I have some people blocked, and some people muted, so I would like to be able to mute people without needing to enter Twitter.com...

**Comment by StuntsPT** [comment]
So, I guess this can be closed now, as muting is implemented in version 1.3.
Right?

**Comment by HanFox** [comment]
@StuntsPT @baedert The mute doesn't seem to work properly. After a client restart muted people may show back up in the timeline. In the very least their retweets do for me.

**Comment by baedert** [comment]
Can't reproduce that here, both tweets and retweets are not shown. Are you talking about the muted user being the retweeter or the retweetee?

**Comment by HanFox** [comment]
The retweeter and usually on new retweets after the restart.

**Comment by StuntsPT** [comment]
Confirming the bug, and confirming that thus far, using the git build I'm not seeing re-tweets of muted accounts any more.

**Comment by HanFox** [comment]
Can confirm that git version seems to have resolved the issue.
