### ISSUE TITLE
Pressing n in DM input field opens "new tweet" popup

### ISSUE THREAD

**Issue by badboy** [baedert/corebird#185]
When trying to write a DM and I press n while the input box is focused it opens the "new tweet popup".
Keyboard shortcuts like this should be disabled when an input box is focused.
Same thing happens for the search input box, but NOT for the filter input.

**Comment by baedert** [comment]
For reference: https://github.com/Ardour/ardour/blob/master/gtk2_ardour/utils.cc#L447
