### ISSUE TITLE
No package 'gstreamer-video-1.0' found

### ISSUE THREAD

**Issue by steckerhalter** [baedert/corebird#189]
I'm not able to combile corebird on debian sid any longe because of this missing dep:

```
configure: error: Package requirements (gtk+-3.0 >= 3.12
             glib-2.0 >= 2.40
             rest-0.7
             libsoup-2.4
             gee-0.8
             json-glib-1.0
             sqlite3 gstreamer-video-1.0 gdk-x11-3.0) were not met:

No package 'gstreamer-video-1.0' found
```

I know about `--disable-video`, does a newer gstreamer version contain the video dep?

**Comment by andersbateva** [comment]
Good, installing `libgstreamer-plugins-base1.0-dev` solved the problem of the missing `gstreamer-video-1.0` on Ubuntu 16.04!

**Comment by s-abhilash** [comment]
Installing libgstreamer-plugins-base1.0-dev worked.

**Comment by MOOREZHANG64** [comment]
Install libgstreamer-plugins-base1.0-dev
Installing libgstreamer-plugins-base1.0-dev package on Ubuntu 14.04 (Trusty Tahr) is as easy as running the following command on terminal:

sudo apt-get update
sudo apt-get install libgstreamer-plugins-base1.0-dev

**Comment by DaLian369** [comment]
> 仅供参考。在_Fedora_或什至_Red Hat_或_CentOs 上_，要安装的软件包是`gstreamer1-plugins-base-deve`.

gstreamer1-plugins-base-devel

**Comment by ilyasofficial1617** [comment]
is there any for windows ?
