### ISSUE TITLE
Twitter emojis not shown

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#197]
Twitter's Android (and iOS?) Apps support adding emojis to tweets. Corebird currently doesn't show these emojis and would be nice if this could be changed

**Comment by baedert** [comment]
I guess I can close this now since the next gtk/pango/cairo/fontconfig or whatever versions will support color emoji.

**Comment by Jvaldez10** [comment]
Hola  en Arch Linux, lo soluciones y logre ver los emoji en corebird con los siguientes comandos:
yay -S ttf-twemoji  
yay -S ttf-twemoji-color
