### ISSUE TITLE
Inline media preview is disrupting

### ISSUE THREAD

**Issue by hfiguiere** [baedert/corebird#232]
Simply put the "large" but cropped preview of the inline media in 0.8 is disrupting the reading flow. It also clearly break the separation between tweets.

Better option:
- square on the right like previously in 0.7
- preview in the current form, BUT the left margin aligned with the one of the tweet, and an inset of a few pixel right and bottom.

**Comment by Ps0ke** [comment]
I agree

**Comment by baedert** [comment]
The inline media are now aligned with the tweet text to work better for quoted tweets.
