### ISSUE TITLE
cache never gets cleared

### ISSUE THREAD

**Issue by baedert** [baedert/corebird#287]

**Comment by pedrofleck** [comment]
Same problem here, I was looking Disk Space Management when I saw a 7gb cache folder from Corebird. Is it safe to delete, at least, until it got fixed?
![captura de tela de 2015-05-22 13-44-37](https://cloud.githubusercontent.com/assets/761321/7775374/0debde4e-0089-11e5-9d50-7fc6479d7f84.png)

**Comment by baedert** [comment]
Yes, you can just delete all the files. But you can't delete the entire folder hierarchy and not restart it.

**Comment by pedrofleck** [comment]
Ok, thank you. Any fix for it?

**Comment by baedert** [comment]
No, otherwise it would be... fixed in the repo.

**Comment by baedert** [comment]
Okay, avatars don't get cached anymore.

**Comment by baedert** [comment]
... and media not anymore either.

**Comment by pedrofleck** [comment]
Great! Thank you :)

**Comment by baedert** [comment]
Profile cache is gone as well, I think this is fixed.
