### ISSUE TITLE
click on tweet now show tweet detail

### ISSUE THREAD

**Issue by hfiguiere** [baedert/corebird#293]
click on tweet now show tweet detail. This is very disruptive and break the click to "focus". Double-click was fine. why such a change?

**Comment by hfiguiere** [comment]
And just to explain, in a lot of situation Corebird lose the focus in the timeline, which break navigating the tweets with the keyboard.

**Comment by hfiguiere** [comment]
All of that is making me go back to 0.8 as packaged in Fedora 21 instead of master. It looks like it is a deliberate change.

Another use case broken: when you start corebird, the list doesn't have the focus, so can't keyboard navigate.

**Comment by baedert** [comment]
That was suggested by a few designers at guadec and it's more consistent with the activation modes in all the other listboxes inside corebird.

**Comment by hfiguiere** [comment]
I don't think it is consistent. Different things, for sure. I just mess it up completely.

**Comment by kmac** [comment]
I'm finding this behaviour a bit difficult to work with as well (though I'm new to corebird, so I'm not familiar with the previous double-click behaviour).

It's most notable when switching from mouse scrolling to keyboard scrolling. It seems the currently selected tweet stays in place when mouse scrolling. Then, invoking a keyboard action (e.g. up or page-up) results in a big delta from the currently displayed list of tweets versus the list after the keypress (usually several pages older in the timeline). To avoid this, I'll resort to selecting one of the currently visible tweets. But this expands the tweet and I have to hit back to get back to the list.

I hope the above makes sense. I don't think it's an uncommon use-case. Maybe there's a mid-way solution, like allowing single click in the body but double-click in the header?

**Comment by baedert** [comment]
I'm inclined to add a setting for this (even though I hate it). It seems like 2 completely different ways to use the timeline. We can't really fix GtkListBox's focus tracking, the focused row doesn't change when scrolled (although since [this bug](https://bugzilla.gnome.org/show_bug.cgi?id=708320) is now fixed, we *could* implement that...).
