### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by ItzBlitz98** [baedert/corebird#297]
I can't seem to get corebird to run anymore. It just segfaults.

I deleted both the ~/.config/corebird and ~/.cache/corebird folders and now the window opens but when i click request pin it just segfaults again.

Don't know if this helps but this is the result from journalctl -f 

```
Jan 05 00:03:27 nexus kernel: corebird[8749]: segfault at 1be2b060 ip 00007f82161f9b2a sp 00007ffff3da42c8 error 4 in libc-2.20.so[7f8216178000+199000]
Jan 05 00:03:28 nexus systemd-coredump[8756]: Process 8749 (corebird) of user 1000 dumped core.
```

OS: Antergos
Using the git version but tried the stable 0.9-1 and that does the same

**Comment by baedert** [comment]
Which commit are you on? I guess you recently updated? When did it start to happen?

**Comment by ItzBlitz98** [comment]
I'm using the latest commit and i tried the release version and its doing the same.

It happened recently (before christmas), Just was too busy with the holidays to report it.

This is the result from gdb

```
Core was generated by `corebird'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f903dc39b2a in strlen () from /usr/lib/libc.so.6
```

**Comment by baedert** [comment]
But that's not a backtrace? Can you run it again in gdb and execute "bt" inside gdb once it crashed?

**Comment by deepfryed** [comment]
https://gist.github.com/deepfryed/8284e44f2cae66e0296b8479187600ca

That's the backtrace, using corebird 1.2-2 on debian

**Comment by baedert** [comment]
What librest version are you using?

**Comment by deepfryed** [comment]
righteo upgraded from 0.7.92-2 to 0.7.93-1 and that seems to have fixed the issue. 

thanks, ui is shiny :+1:
