### ISSUE TITLE
Right click menu for tweets should disappear after focus is lost

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#298]
I've noticed that on Corebird, when you right click a tweet to bring up the options to respond, retweet, etc. the menu doesn't go away until you right click it again by hand, including when the page is left or when you right click on another tweet. It would be a bit more convenient if it did this on it's own when the user right clicks another tweet, leaves the page, etc.

**Comment by baedert** [comment]
I think it would additionally make sense if it was only possible for one of them to show the action buttons at a time?

**Comment by Lyude** [comment]
@baedert yeah, that would definitely help

**Comment by baedert** [comment]
Ok, we hide them now when switching pages and of course after activating any of the actions. I tried some other versions like "hide them when the user scrolled away some distance" or "hide them if the mouse cursor leaves the tweet and doesn't enter it again within 2 seconds", but none of them worked out very well.

**Comment by Lyude** [comment]
Alright, the new behavior works really well and basically solves the problem, so I'm gonna mark this as closed
