### ISSUE TITLE
Corebird doesn't block users properly

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#301]
Corebird's blocking only ever seems to work with mentions that occurred before the client was loaded. If I block someone on Twitter, I still continue to get notified about all of their tweets.

**Comment by baedert** [comment]
This is only about mentions, right? Blocked/muted/rt_disabled after the client started only works since a few weeks ago and I didn't implement it for mentions yet.

**Comment by Lyude** [comment]
Yeah, it's just mentions

**Comment by baedert** [comment]
Did that commit work out for you?

**Comment by Lyude** [comment]
Sorry! I should have said something before. Just tested it with a friend of mine on Twitter and yes, it seems the commit does indeed work. Thanks a ton! You just made Twitter a whole lot nicer to use :+1:
