### ISSUE TITLE
Corebird occasionally hangs and spams log with assert failures

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#303]
Hi! As of recently, corebird has occasionally been freezing, while at the same time outputting this to my log as quickly as possible (it even makes journald take up an entire CPU):
```
Jan 29 10:31:18 meerkat org.baedert.corebird.desktop[3715]: (corebird:3715): Gtk-CRITICAL **: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed
```
I don't have anymore info right now, but if you need more I can e-mail you a coredump (provided that I can encrypt it with GPG or something, seeing as my API keys are probably in it)

**Comment by baedert** [comment]
That's very vague of course, but I've seen similar things when adding the get_visible_row_at function to TweetLIstBox and I've replaced it with something easier in 417447845e4edd647e0be594435d7a0278f0dd01 (and screwed up the bug reference).

**Comment by Lyude** [comment]
Yeah, I would have given more information but the bug only happens occasionally, and I haven't figured out what exactly triggers it (and I forgot to send `SIGQUIT` the last time it came up, so I don't have a coredump just yet). I'll test the latest commit and see if it comes back up again

**Comment by Lyude** [comment]
If this bug was present, I should have ran into it at least once by now. Gonna take a guess and say it's fixed :)
