### ISSUE TITLE
@ Handle doesn't update when changed

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#304]
Recently I changed the @ handle for one of my accounts, and I've noticed that corebird doesn't seem to update the one it has cached.

**Comment by baedert** [comment]
Where doesn't it update?

**Comment by Lyude** [comment]
@baedert everything. The title bar doesn't update, neither does the @ handle in the account selection button on the main window (the one that shows your avatar), along with the @ handle in the "Open Account" menu on the top gnome bar

**Comment by Lyude** [comment]
Okay, so I've noticed when replying to tweets from my self with said account, it won't filter out my @ handle from the mentions either

**Comment by baedert** [comment]
Oookay, can you try that again now? I hope that won't cause inconsistencies...

**Comment by Lyude** [comment]
Okay! It works 99%. When I loaded corebird it detected the changes and updated everything. Replying to myself filtered out my @ like it's supposed to, and my @ name updated in all of the context menus except for the application menu on the top bar in gnome. I had to restart corebird for this to update properly.

**Comment by baedert** [comment]
ok, the app menu now also gets updated.
