### ISSUE TITLE
"Account already in use"

### ISSUE THREAD

**Issue by zyphrus** [baedert/corebird#308]
After the initial session after (what I believe is, cleaned ~/.config/corebird & new binaries) a clean install, logging in and closing Corebird. Starting Corebrid then gives the login screen, requesting a PIN for the account I used previously comes back with the message "Account already in use". With no other instances of Corebird.

This started occur after I changed my twitter's profile name, the console output when I get the "Account already in use" : 

```
Corebird.vala:295: Could not add window for account '<old twitter handle>'
Corebird.vala:239: No window opened
account_get_screen_name: assertion 'IS_ACCOUNT (self)' failed

(process:6430): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
AccountCreateWidget.vala:102: Account is already in use
fatal: Unable to read current working directory: No such file or directory 
```

OS: Arch Linux x64

**Comment by baedert** [comment]
Is that 0.9 or the current dev version? Did you change your profile *name* or your *handle*(aka screen_name)? Handle changes haven't been handled very well until recently.

OTOH, that message should never appear of course if you really deleted the entire `~/.config/corebird`.

**Comment by zyphrus** [comment]
I changed my handle, to be doubly sure, the @\<handle\>. 
It occurs in both 0.9 and dev
When cleaning I do delete the whole folder with a `rm -rf ~/.config/corebird`

**Comment by baedert** [comment]
I don't really know what to say -- if this is the first account you set up after removing the old database file, the check for existing accounts can never be true of course. You aren't one of those people who still have a `~/.corebird`, are you? The only thing left then is building it with `--enable-debug` and posting that output.

**Comment by zyphrus** [comment]
It seems the fault might be on my side. I must confess I have been installing from AUR [`corebird`](https://aur.archlinux.org/packages/corebird/) and [`corebid-git`](https://aur.archlinux.org/packages/corebird-git/) with edited PKGBUILD's with the added `--enabled-debug` .

Using these packages I get this output:

```
Corebird.vala:295: Could not add window for account '<old screen name>'
Corebird.vala:239: No window opened
account_get_screen_name: assertion 'IS_ACCOUNT (self)' failed
UserStream.vala:76: CREATING USER STREAM FOR @screen_name
AccountCreateWidget.vala:49: Trying to open http://twitter.com/oauth/authorize?oauth_token=<token>

(process:26261): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
AccountCreateWidget.vala:97: Checking for <new screen name>
AccountCreateWidget.vala:102: Account is already in use
```

I thought this was weird and did a hand with the AUR packages removed and got actual debug output: 

```
** (corebird:17285): DEBUG: Corebird.vala:133: startup
** (corebird:17285): DEBUG: Database.vala:45: $HOME/.config/corebird/Corebird.db User version: 1

** (corebird:17285): WARNING **: Corebird.vala:300: Could not add window for account '<old handle>'
** (corebird:17285): DEBUG: UserStream.vala:80: CREATING USER STREAM FOR <new handle>
** (corebird:17285): DEBUG: Database.vala:45: $HOME/.config/corebird/accounts/<ID>.db User version: 2
** (corebird:17285): DEBUG: UserStream.vala:123: Starting stream for <new handle>
** (corebird:17285): DEBUG: Account.vala:515: Add <N> disabled_rts ids
** (corebird:17285): DEBUG: Account.vala:484: Add <N> blocked ids
** (corebird:17285): DEBUG: Account.vala:453: Add <N> muted ids
** (corebird:17285): DEBUG: Account.vala:409: Adding <N> friends...
Message with type STREAM_MESSAGE_TYPE_FRIENDS
{"friends":[<...>]}



** (corebird:17285): DEBUG: UserStream.vala:153: STOPPING STREAM FOR <new handle>

** (corebird:17285): WARNING **: UserStream.vala:206: buf == NULL
** (corebird:17285): DEBUG: UserStream.vala:190: USERSTREAM for <new handle> DESTROYED
** (corebird:17285): DEBUG: MainWindow.vala:319: Windows: 1
** (corebird:17285): DEBUG: MainWindow.vala:420: Saving geomentry for <new handle>: 2000,204,480,700
```

After that, it started to work. Not sure what really happened in all honesty, but it still knows my old handle (which twitter might of provided or some file somewhere has not been cleaned, I dunno) and the AUR packages seemly did something to break it.

**Comment by cpu82** [comment]
I had the same problem, but after switch to the current *development version* this problem go away.
