### ISSUE TITLE
Tweet more than 140 chars. Tweet discarded

### ISSUE THREAD

**Issue by hfiguiere** [baedert/corebird#311]
Corebird should disable the tweet button if more than 140 chars, instead of throwing it away.

**Comment by baedert** [comment]
It's been just like that for an eternity, when does it not happen?

**Comment by hfiguiere** [comment]
It did last night on 0.9 (from F21). I validated the tweet with ctrl-Return. I tried again. Indeed the button is grayed out. But the keyboard shortcut still work. And I get an error popup.

**Comment by hfiguiere** [comment]
Note: if posting fails for whatever reason, Corebird shouldn't discard the tweet. So it might be two bugs.
