### ISSUE TITLE
Official TW App behaviour

### ISSUE THREAD

**Issue by Luisfo** [baedert/corebird#313]
I'm using version 0.7
I'm missing the same behaviour as the official mobile App:

1. When somebody retweet a 'reply' (i.e. a tweet starts with "@user ...") is not shown in corebird TL. It should. It happens to me sometimes.

2. When somebody retweet a tweet from a followee it is shown in the TL (it should have been previously showed in the TL). It shouldn't.

I don't know if it is aim by corebird to have the same behaviour as the official TW app. But, at least, this functions might be an option available in the settings.

**Comment by baedert** [comment]
1. We don't get this information from the API, so we can't show them.

2. That should already hapen in current master. What version are you using?

**Comment by Luisfo** [comment]
1. I understand.

2. Currently, I'm using v0.7. I'm checking the v0.9 is the last one.

Well, I think this 'issue' can be closed!
