### ISSUE TITLE
Navigation keys should direct focus to timeline automatically

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#323]
It's kind of difficult to use the keyboard shortcuts, because you need to get the focus to go over to the timeline widget before you can even use the arrow keys to select a tweet. It sounds like it would be a good idea if, by default, any arrow key presses made while on a timeline direct focus to the timeline widget automatically, instead of requiring the user to select a tweet, go to the details, and then go back to the timeline.

**Comment by Lyude** [comment]
Changed this because I noticed this behavior also applies to the home key, and probably a couple others

**Comment by baedert** [comment]
> [...] any arrow key presses made while on a timeline direct focus to the timeline widget automatically [...]

Huh, is there a "not" missing here?

> [...] requiring the user to select a tweet, go to the details, and then go back to the timeline.

Well you can just tab there of course (we even [skip the sidebar](https://github.com/baedert/corebird/blob/master/src/MainWidget.vala#L119), which breaks a11y keyboard navigation :/)


Generally, we could only capture arrow key presses if no widget has focus yet (which is basically only the case after starting the application...). Another (even useful) addition would be to capture DOWN presse in the headerbar and just focus the current timeline (or the current page I guess) in that case.

**Comment by baedert** [comment]
Just read this again, I now understand what you meant and there's no "not" missing. A little late, but okay.

Yeah a11y relies on the cursor keys working like that. I described the current situation in https://github.com/baedert/corebird/commit/f039bd577dd15b1a4320d6033153bca9d8b996d7.

**Comment by baedert** [comment]
Pressing the down arrow key now directly selects the first tweet in the timeline here, so closing this.
