### ISSUE TITLE
Profile window creates cute, small white square you can't close out of

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#326]
So this is definitely a strange one. I've noticed that every time I open up the window to edit my twitter profile, corebird makes this small white square at the top left corner of the screen. You can't seem to close out of it, and it only disappears once I exit out of corebird completely.
![screenshot from 2015-03-08 11 02 56](https://cloud.githubusercontent.com/assets/1527057/6546253/4dee4482-c583-11e4-9d64-07460bfd81e6.png)

**Comment by baedert** [comment]
![](http://replygif.net/i/290.gif)

**Comment by baedert** [comment]
You can't select that with the inspector wither, right?

55×55px fwiw

**Comment by baedert** [comment]
Aaah, happens when you have a mention in your description, that square is the completion window.
I'll look at that later today.

**Comment by Lyude** [comment]
Funny you mention that. Looks like I can't select it with the inspection window, But if I click on the textbox in the profile window, it moves below the textbox, and then if focus leaves said textbox it disappears

**Comment by Lyude** [comment]
Looks like after 3e2b130 the cute white square has disappeared, going to mark this as closed!
