### ISSUE TITLE
Corebird-git broke at start with seg

### ISSUE THREAD

**Issue by marciosr** [baedert/corebird#336]
In git version (arch linux aur-corebird-git), right now it is happening with my instalation:

-->$ corebird 

** (corebird:4800): WARNING **: Corebird.vala:314: Could not add window for account 'marciosousaroch'

** (corebird:4800): WARNING **: MainWindow.vala:379: Couldn't load window geometry for screen_name `screen_name'
Falha de segmentação (imagem do núcleo gravada)

--> gdb output is:
Starting program: /usr/bin/corebird
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

** (corebird:16512): WARNING **: Corebird.vala:314: Could not add window for account 'marciosousaroch'

** (corebird:16512): WARNING **: MainWindow.vala:379: Couldn't load window geometry for screen_name `screen_name'
[New Thread 0x7fffeb342700 (LWP 16517)]
[New Thread 0x7fffebcce700 (LWP 16516)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4aa520a in strlen () from /usr/lib/libc.so.6

**Comment by marciosr** [comment]
Using gtk version 3.14.9-1 and compiled with vala 0.26.2-1

**Comment by baedert** [comment]
When did you update that last? When you run it in gdb, can you execute "bt" after it crashes and post that output?

**Comment by marciosr** [comment]
Today (git version 3398+gea4ff44-1);
(gdb) bt
#0  0x00007ffff4aa520a in strlen () from /usr/lib/libc.so.6
#1  0x00007ffff4e32a24 in g_string_append_uri_escaped () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff70ed75c in ?? () from /usr/lib/librest-0.7.so.0
#3  0x00007ffff70e8f4e in ?? () from /usr/lib/librest-0.7.so.0
#4  0x00007ffff70ea143 in rest_proxy_call_async () from /usr/lib/librest-0.7.so.0
#5  0x00007ffff70ea845 in rest_proxy_call_run () from /usr/lib/librest-0.7.so.0
#6  0x00007ffff70ec41a in oauth_proxy_request_token () from /usr/lib/librest-0.7.so.0
#7  0x00005555555a655f in ?? ()
#8  0x00007ffff50e63a4 in ?? () from /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff5100007 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff510095f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff7623aad in ?? () from /usr/lib/libgtk-3.so.0
#12 0x00007ffff7623b05 in ?? () from /usr/lib/libgtk-3.so.0
#13 0x00007ffff50e6175 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff50f732b in ?? () from /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff51006f8 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff510095f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff7621a90 in ?? () from /usr/lib/libgtk-3.so.0
#18 0x00007ffff279f1f0 in ffi_call_unix64 () from /usr/lib/libffi.so.6
#19 0x00007ffff279ec58 in ffi_call () from /usr/lib/libffi.so.6
#20 0x00007ffff50e6ddc in g_cclosure_marshal_generic_va () from /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff50e63a4 in ?? () from /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff5100007 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#23 0x00007ffff510095f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#24 0x00007ffff76c64f1 in ?? () from /usr/lib/libgtk-3.so.0
#25 0x00007ffff50e912e in g_cclosure_marshal_VOID__BOXEDv () from /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff50e63a4 in ?? () from /usr/lib/libgobject-2.0.so.0
#27 0x00007ffff5100007 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#28 0x00007ffff510095f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#29 0x00007ffff76c3ade in ?? () from /usr/lib/libgtk-3.so.0
#30 0x00007ffff76c4f2b in ?? () from /usr/lib/libgtk-3.so.0
#31 0x00007ffff76c7940 in ?? () from /usr/lib/libgtk-3.so.0
#32 0x00007ffff769b02b in gtk_event_controller_handle_event () from /usr/lib/libgtk-3.so.0
#33 0x00007ffff783683d in ?? () from /usr/lib/libgtk-3.so.0
#34 0x00007ffff77096e9 in ?? () from /usr/lib/libgtk-3.so.0
#35 0x00007ffff50e63a4 in ?? () from /usr/lib/libgobject-2.0.so.0
#36 0x00007ffff50ffab0 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#37 0x00007ffff510095f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#38 0x00007ffff783a124 in ?? () from /usr/lib/libgtk-3.so.0
#39 0x00007ffff770704e in ?? () from /usr/lib/libgtk-3.so.0
#40 0x00007ffff7708c0e in gtk_main_do_event () from /usr/lib/libgtk-3.so.0
#41 0x00007ffff5b18c12 in ?? () from /usr/lib/libgdk-3.so.0
#42 0x00007ffff4e1171d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#43 0x00007ffff4e11a08 in ?? () from /usr/lib/libglib-2.0.so.0
#44 0x00007ffff4e11abc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#45 0x00007ffff664e09c in g_application_run () from /usr/lib/libgio-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#46 0x0000555555567ca5 in ?? ()
#47 0x00007ffff4a45800 in __libc_start_main () from /usr/lib/libc.so.6
#48 0x0000555555567b29 in ?? ()

**Comment by marciosr** [comment]
corebird crashes at this moment:

![captura de tela de 2015-03-15 09 21 39](https://cloud.githubusercontent.com/assets/1645395/6655950/bf656fb6-caf4-11e4-8f42-12f4edbd2949.png)

**Comment by baedert** [comment]
I can't reproduce that at all. What librest version do you have installed?

**Comment by marciosr** [comment]
rest 0.7.92-1

**Comment by marciosr** [comment]
It work now! 
I instaled res-git from AUR and corebird works fine now!
Thanks for the help!
