### ISSUE TITLE
Localization of invalid strings

### ISSUE THREAD

**Issue by r3pek** [baedert/corebird#341]
Compiling Corebird with a different location than en_US (in this case I think is turkish), produces invalid C code.

The build log can be see here: http://pastebin.com/u4J1rP0k
Notice the COREBİRD_app_entries constant(!?) with the invalid "I" resulting in errors compiling.

Reported here: https://aur.archlinux.org/packages/corebird/

**Comment by baedert** [comment]
What's the used valac version?
