### ISSUE TITLE
corebird suddenly crashes

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#346]
Since yesterday corebird suddenly crashes. When running corebird from terminal the following errormessages are listed:

> ** (corebird:2728): CRITICAL **: InlineMediaDownloader.vala:160: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/583955307652452352_74255305_0.png' contains no data (error code 0)

> ** (corebird:2728): CRITICAL **: string_substring: assertion '(_tmp17_ + _tmp18_) <= _tmp19_' failed

> ** (corebird:2728): CRITICAL **: text_transform_is_whitespace: assertion 's != NULL' failed
Speicherzugriffsfehler (Speicherabzug geschrieben)

This might be related to d9c0e707bc4706a75fff52d846687d8189833ba5

**Comment by yanthor** [comment]
Same issue here. I'm using archlinux, tried both corebird and corebird-git from AUR.

**Comment by baedert** [comment]
Yes, that's easily possible. I couldn't find any issues with the texttransform branch so I merged it to get more feedback. I'll be busy until wednesday next week. There's a farily elaborate testsuite for it though, so compiling with --enable-debug, running under gdb and getting a backtrace from such a crash (maybe posting the value of org.baedert.corebird.text-transform-flags, but it shouldn't be necessary) would help a lot (and ensure that such a  bug won't happen in the future).

**Comment by yanthor** [comment]
Tested with  corebird-git 3405+g80ca816-1 from AUR
I don't have much experience with gdb, how to get the value of org.baedert.corebird.text-transform-flags ?
```
#0  0x00007ffff4aa520a in strlen () from /usr/lib/libc.so.6
#1  0x00000000004ceb0a in text_transform_transform (text=0x7fffc800d800 "Комикси на деня: №111312 с Ахмед Доган http://t.co/DoPo6OsZXW #comix #dnk", entities=0x7fffc800d970, 
    entities_length1=3, flags=TRANSFORM_FLAGS_REMOVE_MEDIA_LINKS, media_count=0) at /tmp/trizen-yanthor/corebird-git/src/corebird/src/util/TextTransform.vala:81
#2  0x0000000000450058 in tweet_get_trimmed_text (self=0x988c80) at /tmp/trizen-yanthor/corebird-git/src/corebird/src/Tweet.vala:339
#3  0x00000000004d0de7 in tweet_list_entry_construct (object_type=17828656, tweet=0x988c80, window=0xb7e380, account=0x83a6a0) at /tmp/trizen-yanthor/corebird-git/src/corebird/src/list/TweetListEntry.vala:113
#4  0x00000000004d1c4a in tweet_list_entry_new (tweet=0x988c80, window=0xb7e380, account=0x83a6a0) at /tmp/trizen-yanthor/corebird-git/src/corebird/src/list/TweetListEntry.vala:104
#5  0x00000000004bd1ad in __lambda49_ (_data55_=0x14a9660) at /tmp/trizen-yanthor/corebird-git/src/corebird/src/util/TweetUtils.vala:312
#6  0x00000000004bd6c3 in ___lambda49__gsource_func (self=0x14a9660) at TweetUtils.c:3714
#7  0x00007ffff4e1162d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#8  0x00007ffff4e11a08 in ?? () from /usr/lib/libglib-2.0.so.0
#9  0x00007ffff4e11abc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#10 0x00007ffff664e09c in g_application_run () from /usr/lib/libgio-2.0.so.0
#11 0x000000000041187b in _vala_main (args=0x7fffffffe628, args_length1=1) at /tmp/trizen-yanthor/corebird-git/src/corebird/src/main.vala:27
#12 0x00000000004118c8 in main (argc=1, argv=0x7fffffffe628) at /tmp/trizen-yanthor/corebird-git/src/corebird/src/main.vala:18
```

**Comment by baedert** [comment]
The value's in the stack trace, so no need to post it again. Thanks!

**Comment by baedert** [comment]
Is this still happening after 39e26fa10be9115ab91c9adfde911b0d3d204dfe?

**Comment by yanthor** [comment]
I will try to test it later tonight. Thank you for the work you do!

**Comment by yanthor** [comment]
Nice, no more crashes. I wish you happy holidays!
