### ISSUE TITLE
Misspelled words cleared when beginning to type another word

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#350]
So, from what I can tell corebird checks for incorrectly spelled words after the user hits a space. This is great, but the problem is once you begin typing another word, the red highlighting seems to disappear for any previously misspelled words. Try typing this in a tweet to see what I'm talking about:

```
fff fff fff fff
```

**Comment by sunng87** [comment]
I can reproduce on my build. This is probably an upstream (gtkspell3) issue.

**Comment by Lyude** [comment]
Are you sure about that? Evolution uses gtkspell and seems to be fine

**Comment by baedert** [comment]
Doesn't look like we get spell checking any time soon, we can reopen this when the time comes.
