### ISSUE TITLE
missing Package requirements (ubuntu 14.10)

### ISSUE THREAD

**Issue by benborges** [baedert/corebird#352]
configure: error: Package requirements (gtk+-3.0 >= 3.14
             glib-2.0 >= 2.40
             rest-0.7
             libsoup-2.4
             gee-0.8
             json-glib-1.0
             sqlite3) were not met:

Requested 'gtk+-3.0 >= 3.14' but version of GTK+ is 3.12.2
No package 'rest-0.7' found
No package 'libsoup-2.4' found
No package 'gee-0.8' found
No package 'json-glib-1.0' found

Can't manage to compile corebird on my system, any help to be able to install missing requirements ?

**Comment by baedert** [comment]
1) Find out how to install development packages on your distribution, install them for rest, libsoup, gee and json-glib
2) Corebird 1.0 requires gtk+ 3.14, but your system only has 3.12. I can only find tutorials about how to install corebird 0.9 so you might want to try that instead (there's also a PPA somewhere)

**Comment by RyanNerd** [comment]
ktI'm using Linux Mint 17.3 which is a fork of Ubuntu 14.10 and have been trying to compile (without any success) some apps that require gtk 3.14. I found out why this [does not work](http://www.omgubuntu.co.uk/2014/09/gnome-3-14-wont-included-ubuntu-14-10)

Apparently back-porting this is a major effort.
