### ISSUE TITLE
Tweet action buttons overlap timestamp and conversation icon on hover

### ISSUE THREAD

**Issue by nevillepark** [baedert/corebird#353]
Using 0.9 on Elementary OS Freya. Not sure if the conversation icon and timestamp are meant to be clickable; you can't click on them without the buttons for fav, RT, etc., getting in the way, and it looks bad anyway.

Normal tweet:
![screenshot from 2015-04-12 13 27 01](https://cloud.githubusercontent.com/assets/9839923/7106693/0b6504ec-e118-11e4-84c7-2c66c59da017.png)

When mouse is hovering over it:
![screenshot from 2015-04-12 13 27 15](https://cloud.githubusercontent.com/assets/9839923/7106694/0b6b0388-e118-11e4-8a33-02556c564bfe.png)

**Comment by baedert** [comment]
The "problem" is that we take the backgorund color of the list row and use it in the box that appears when hovering (and contains those buttons). Your theme does not give them any background color it seems.

But anyway, 1.0 doesn't have the hover buttons anymore.

**Comment by nevillepark** [comment]
Thanks! The ubuntuhandbook PPA doesn't have a 1.0 package for Trusty (what Freya's based on) so I'll see about compiling it myself.
