### ISSUE TITLE
"Unrecognised image file format" for every jpeg files

### ISSUE THREAD

**Issue by newincpp** [baedert/corebird#356]
hello,
I tried Corebird today which is pretty cool and work pretty well =)
except this:
A lot of images don't show-up (just displaying "100%") and I have a lot of warning in my terminal that look like this:

 ** (corebird:26420): WARNING **: InlineMediaDownloader.vala:289: Unrecognised image file format(/home/newin/.cache/corebird/assets/media/589091822229684224_532768122_0.jpeg)

or like this:

** (corebird:26420): WARNING **: Twitter.vala:115: Unrecognised image file format for http://pbs.twimg.com/profile_images/3531201765/bcddf30cb7e038ec9aefc2a2893174cc_normal.jpeg

Every-time it's related to "InlineMediaDownloader.vala" and "Twitter.vala" and it's only related to jpeg files.
I've tried to read the code of corebird to understand where is come from but I've never seen any vala code in my life...

**Comment by baedert** [comment]
What does `gdk-pixbuf-query-loaders` print on the console?

**Comment by newincpp** [comment]
I don't see anything about gdk-pixbuf in the console.
here is my complete log: http://pastebin.com/kM7qtUr7

**Comment by newincpp** [comment]
Because I am on gentoo regarding your comment I just checked if gdk-pixbuf was compiled with jpeg support and I hadn't I rexompiled it with jpeg support and it work now. thank you!

PS: it would be nice if you say in the readme that we need this support in gdk-pixbuf (as for the --disable-video option with gstreamer) for every source based distros
