### ISSUE TITLE
uses more idle cycles after resume from suspend

### ISSUE THREAD

**Issue by axfelix** [baedert/corebird#357]
Hi,

First I want to say that I absolutely love the app -- it's one of a handful of Gtk3 Vala apps that I use day to day at this point that I think are easily OSX-nice, and make Linux seem way better on the UX front than it has in recent years.

WIth that said, I've noticed that Corebird tends to use more idle CPU cycles after the computer resumes from suspend until I restart the app. It's relatively negligible (like 2-3% of one core on an i5-4300Y), but it does seem to discourage the CPU from downclocking when it otherwise would. Any idea what this might be? I can try to provide logs if needed.

Running 1.0 on Gnome 3 in Arch Linux, fwiw.

**Comment by baedert** [comment]
Do you have any users blocked? Or retweets disabled? Users muted? Can you always reproduce it? 2% cpu usage is what I usually get when just showing a rotating spinner (which we show at the bottom of a timeline if the results indicate that more tweets are available).

**Comment by axfelix** [comment]
None of the above. It probably has something to do with the time elapsed since suspend, if corebird wants to fetch the intervening tweets for some reason... But it's definitely more CPU than is used otherwise.

**Comment by baedert** [comment]
No, we basically just erase all tweets from the timeline and load a few new ones. If you can't reliably reproduce it, it's both very hard to figure out what the actual problem is... and likely just the spinner.

**Comment by baedert** [comment]
arch has gtk+3.16 already, can you try if it's still a problem with master?*


* if that doesn't break anything...

**Comment by axfelix** [comment]
Yeah, I can grab a new build in a bit. The behaviour hasn't changed under 3.16 generally, though I have noticed I can somehow get it to go away by deliberately clicking between tabs or scrolling down to the bottom of the home timeline to make it load another batch of tweets, suggesting that this may indeed be related to the spinner, or at least to Corebird perpetually wanting to load more tweets after having missed some.

**Comment by baedert** [comment]
That spinner is gone now so I'll close this issue. Feel free to reopen it if it's still an issue with never versions.
