### ISSUE TITLE
Revamped quote tweet

### ISSUE THREAD

**Issue by gespadas** [baedert/corebird#358]
Corebird should implement this new feature of Twitter » https://twitter.com/twitter/status/585225218093932544

**Comment by quack1** [comment]
I agree, having to click on "tweet" links to open a new tweet in Firefox is kind of annoying...

**Comment by baedert** [comment]
Regardless of the original feature suggestion: tweet links have been opening in corebird instead of a browser for a while now.

**Comment by quack1** [comment]
Oh, I may have an old version of corebird... I will check that, thanks for
the info!

**Comment by hfiguiere** [comment]
Not in 0.9, for sure.

**Comment by baedert** [comment]
Oh great, the text of the retweeted/quoted tweet isn't even part of the tweet's json data. m(

**Comment by baedert** [comment]
I'll look into this as soon as I find a tweet with the new quoted_status object: https://twittercommunity.com/t/api-payloads-to-include-original-quoted-tweet-objects/38184

**Comment by HeikoAdams** [comment]
If it helps: https://twitter.com/OstfrieseInFran/status/605398702459633664

**Comment by baedert** [comment]
@HeikoAdams Can I push the json data of that tweet to https://github.com/baedert/corebird-debug-tool?

**Comment by HeikoAdams** [comment]
Yes

**Comment by baedert** [comment]
A first version of this is implemented in master if you haven't noticed yet.
