### ISSUE TITLE
Corebird should stop showing a modal dialog when the connection fails in the background

### ISSUE THREAD

**Issue by hfiguiere** [baedert/corebird#359]
Corebird should stop showing a modal dialog when the connection fails **in the background**. It is not important and I think the user should be only notified if the failure has lasted a bit long or if the user initiated the operation...

**Comment by baedert** [comment]
What dialog? Do you have a screenshot?

**Comment by hfiguiere** [comment]
Now I do:

![screenshot from 2015-05-21 13-30-17](https://cloud.githubusercontent.com/assets/114441/7754846/9924466c-ffbd-11e4-8dc6-68fd03ccfd95.png)

**Comment by baedert** [comment]
To be fair, that is an error we get after several minutes when trying to do some API calls (but after asking around, nobody seems to be affected reliably...), i.e. it's not just "in the background".
Anyway, those dialogs already don't show up anymore.
