### ISSUE TITLE
Icons missing on kde environment

### ISSUE THREAD

**Issue by iPotable** [baedert/corebird#360]
Hello,

The icons images are missing when running the client on a kde (plasma 5.2) environment. I think a dependency is missing, but I don't which package. I'm running on Archlinux, using the stable release 1.0 available from the Arch User Repository. Do you know which package is missing ?

![screenshot](https://cloud.githubusercontent.com/assets/2788478/7439546/273eda2c-f080-11e4-8992-97483a12e363.png)

**Comment by baedert** [comment]
`adwaita-icon-theme`?

**Comment by iPotable** [comment]
I already have adwaita-icon-theme as it is a gtk3 dependency :/

**Comment by baedert** [comment]
They show up just fine here in KDE, do you get any console output?

**Comment by iPotable** [comment]
Here are the errors returned when started on a virtual console : 
```
(gst-plugin-scanner:9394): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstrsvg.so': librsvg-2.so.2: cannot open shared object file: No such file or directory

(gst-plugin-scanner:9394): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstopencv.so': libopencv_calib3d.so.2.4: cannot open shared object file: No such file or directory

(corebird:9382): GLib-GObject-WARNING **: The property SoupSession:ssl-ca-file is deprecated and shouldn't be used anymore. It will be removed in a future version.
```

I do not understand their meanings. Maybe a gstreamer package is missing, i do not know.

**Comment by iPotable** [comment]
It seams the first file is in gst-plugin-bad dependence and I installed it from the package dependencies on aur https://aur.archlinux.org/packages/corebird/

**Comment by baedert** [comment]
Just a guess, but do you have librsvg installed?

**Comment by iPotable** [comment]
Your guess is correct. librsvg wasn't installed on my system. I installed it and now I have the icons working. Should you add it to the corebird dependencies ?

**Comment by baedert** [comment]
It just got added to the `adwaita-icon-theme` dependencies (and should really be a dependency for all icon themes) so it should be fine.
