### ISSUE TITLE
little issue on notification

### ISSUE THREAD

**Issue by vlag24** [baedert/corebird#362]
hello from France,
I just want to report a little issue on notification for french language in corebird_1.1~really1.0+git20150421-1_i386. 
Each tweet notification says XXX "tweeté" or "tweetée", it's a bit annoying because it should say "a tweeté" only, regardless the gender. Voilà.
great tweeter application by the way, good job, it's my regular on Elementary OS Freya ;)

**Comment by baedert** [comment]
Hey, thanks for reporting.
The translations are kept in Transifex (see the README for the link), so you can just change it yourself (I don't know any french...).

**Comment by vlag24** [comment]
ok thanks :)
