### ISSUE TITLE
Suggest : display image thumbnail like Twitter and browser client

### ISSUE THREAD

**Issue by harobed** [baedert/corebird#364]
Suggest : display image thumbnail like Twitter and browser client http://a5.mzstatic.com/us/r30/Purple5/v4/13/28/62/1328628b-bb08-f8f6-c9f2-727b844496ec/screen800x500.jpeg

**Comment by baedert** [comment]
Search for duplicates on the bug tracker.

**Comment by harobed** [comment]
#199
