### ISSUE TITLE
Window close button is different from theme

### ISSUE THREAD

**Issue by lucaciavatta** [baedert/corebird#366]
I'm using Corebird under Ubuntu 15.04 with Unity and I noticed a graphical issue.
If I use a different theme with the window close button of different color, the Corebird close button is still of the standard Ambiance color. Also with the high contrast theme, Corebird uses a different close button(seems the standard Gnome button).

To explain better, I have uploaded 2 images:
http://postimg.org/image/8f1zfikh7/
http://postimg.org/image/x6aekgnu9/

**Comment by baedert** [comment]
Client-side window decorations (like the one corebird uses) are controlled by your gtk theme and not your WM theme. If the close button style of the 2 doesn't match, it just won't look the same.

**Comment by lucaciavatta** [comment]
It happens with some themes, also the standard Ubuntu high contrast, and only with Corebird in my system. I'll try to investigate it. Thx for the answer.

**Comment by lucaciavatta** [comment]
@baedert you're right!
All the themes that give the issue with Corebird have the Header Bars section in the gtk-widgets.css file not properly configured. I have tried to manually adjust the values for the close button and all went fine.

Excuse me for disturb and thank you very much for the feedback.
