### ISSUE TITLE
Get the followers/following list of an account

### ISSUE THREAD

**Issue by seboss666** [baedert/corebird#367]
I'm currently using corebird on Manjaro Linux (from the AUR package). I've tried to see the followers list of an account from the account detail page. But clicking on the number does nothing.

Is this a bug or does the functionality just exist ? I don't know how to mark this issue, bug or enhancement.

Thanks in advance.

**Comment by baedert** [comment]
That's not implemented, no.

**Comment by baedert** [comment]
Ok there's something in the `profile-buttons` branch, now. Feedback welcome.

**Comment by baedert** [comment]
In master now.
