### ISSUE TITLE
Tweet Details Keyboard Navigation

### ISSUE THREAD

**Issue by jacobmischka** [baedert/corebird#368]
Hotkeys stop working when viewing a tweet's details, I would imagine that pressing r when viewing a tweet should still bring up the reply dialog, likewise pressing up or down should navigate among replies.

**Comment by baedert** [comment]
No, that works when a tweet in a list is focused, nowhere else. If you have  tweet in the tweet details page focused and press `r`, you'll reply to the selected tweet, not the tweet whose details you're looking at.

**Comment by jacobmischka** [comment]
Would it be possible to be able focus the primary tweet you're viewing in that list? I see what you mean now with being able to navigate among the replies and reply with r to them, but currently you have to focus the reply button and then hit enter to reply to the tweet you're viewing details, is that correct?

**Comment by baedert** [comment]
Yes, that's correct.
