### ISSUE TITLE
Reversed Replies

### ISSUE THREAD

**Issue by jacobmischka** [baedert/corebird#369]
This is an enhancement request, the option to view replies to a tweet when viewing its details in top>bottom chronological order would be really nice I think.

**Comment by baedert** [comment]
Why? It makes sense to me to have the chronologically closest tweets also closest in the layout (also, nothing here makes sense really, since the replies shown there are only a rough estimation, only <=5 and change a lot so you can't rely on them a lot anyway...)

**Comment by jacobmischka** [comment]
Because that's how tweetdeck and every other twitter client I've used does it

**Comment by IBBoard** [comment]
Making it clearer that they're there would also be good. I wondered what the blue bar was about at the top of some posts and only worked it out by accident! I'll put that in as a separate ticket, in case it can be a separate change.

**Comment by IBBoard** [comment]
Why did this issue get closed? I think it is a separate but related enhancement to my #462 that would make a lot of sense.

**Comment by jacobmischka** [comment]
Because the developer seems to have made a choice that he likes it the way it is, and he hasn't given it any thought in 8 months, and I was cleaning up open issues I had created.
