### ISSUE TITLE
Notifications ignore filters

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#370]
Corebird doesn't respect filters on notifying about new tweets. For example I get a notfication about 5 new tweets even if 4 of them are filtered out.

**Comment by baedert** [comment]
What version is that?

**Comment by HeikoAdams** [comment]
Latest git-snapshot

**Comment by baedert** [comment]
Can't reproduce that here. I don't see how that would work from the code either. Is/Was there anything special about those tweets?

**Comment by HeikoAdams** [comment]
The notification said that there were 5 new tweets but only 1 was visible because the other ones where hit by a filter created shortly before
