### ISSUE TITLE
Some images are not displayed

### ISSUE THREAD

**Issue by steinuil** [baedert/corebird#378]
It seems corebird refuses to display every other image, since half of the avatars look like [this](http://i.imgur.com/MGmQywo.jpg) and most of the images are not displayed at all. When opened from a terminal it keeps throwing messages [like these](https://gist.github.com/steinuil/e54fdc1a0b79a234282a) to stderr.

I have no idea what could be causing it, I compiled gd with jpeg and png support and the other libraries look fine.

**Comment by baedert** [comment]
What does `gdk-pixbuf-query-loaders` print?

**Comment by steinuil** [comment]
Ah, apparently gdk-pixbuf was compiled without jpeg support for some reason.
Guess that will have to be fixed if I find the time to update the gentoo ebuild for corebird.

**Comment by steinuil** [comment]
I re-compiled gdk-pixbuf with jpeg and now the images work, thanks!
