### ISSUE TITLE
Tweet actions now take more clicks... and are less discoverable

### ISSUE THREAD

**Issue by hfiguiere** [baedert/corebird#381]
Since I have 1.0, tweet actions take more clicks and are less discoverable.... seriously right click to get the buttons to appear? The way it was before was fine.

**Comment by hfiguiere** [comment]
And it is not discoverable either, except by thinking there is a contextual menu in there.

**Comment by baedert** [comment]
Didn't you have a déjà vu feeling when writing this? https://github.com/baedert/corebird/issues/295

You attitude and phrasing will just cause me to ignore you even more.

**Comment by hfiguiere** [comment]
Maybe because it was closed. My attitude is "report issues". Apparently you don't want that either. Ah well.

**Comment by hfiguiere** [comment]
WONTFIX
