### ISSUE TITLE
No refresh (load new tweets) in arch linux !

### ISSUE THREAD

**Issue by moontoise** [baedert/corebird#382]
hi guys
i newly installed CoreBird on my pc, and i really really love it and its functions !
but i have an big problem! no new tweets load automaticly or manually :-(
CoreBird output (pourfallah is mine username):
""
** (corebird:25148): WARNING **: UserStream.vala:202: buf(pourfallah) == NULL

** (corebird:25148): WARNING **: UserStream.vala:202: buf(pourfallah) == NULL

** (corebird:25148): WARNING **: UserStream.vala:202: buf(pourfallah) == NULL
""

**Comment by baedert** [comment]
That buf == NULL output gets printed how often? Periodically? I just finally changed that code to also try to reconnect when we get a NULL buffer, but if you get that every time and nothing else, there's nothing I could to so you actually receive any data...

**Comment by moontoise** [comment]
@baedert
yeah, its show every 30 seconds.
but, how i can fix my problem? my birdie dont recieve and show any new tweets!
Please ! I really love corebird and i want to use it 100% :-(
thank u
My Pc Details:
OS: Arch Linux (2015.07.01) x86_64
Vala Version: 0.25.0

**Comment by moontoise** [comment]
its can go better if corebird go refresh by shortkey (like Ctrl+R or F5).
can do this?!

**Comment by baedert** [comment]
So, does it still happen after updating? If that happens all the time and you don't receive any data at all, there's something wrong either on your system or on the twitter server, but I don't have control over either.
I won't add a refresh button.

**Comment by r3pek** [comment]
I also have this problem... running 1.0.1

**Comment by osaris** [comment]
Same problem here running 1.1, it works well when I start corebird until my computer goes to sleep and resume.

It looks like corebird tries to load feed when computer come back from sleep and network adapter is still down (even if it connects to network very quickly). Then it doesn't load those tweets anymore but it loads new tweets. Very annoying :-/

**Comment by baedert** [comment]
That's not the same problem. You're suspending/resuming. Master should have a retry button in that case (the fact that it doesn't appear in 1.1 was a bug...), but I'm not sure if that would fix your problem.

**Comment by osaris** [comment]
Ok but the error message is the same. I have the retry button but it says "Loading..." and nothing happens until new tweets arrives (but older tweets aren't loaded).
