### ISSUE TITLE
Videos show up as black window

### ISSUE THREAD

**Issue by katastrophal** [baedert/corebird#388]
I'm on Fedora 22 with latest updates
All Videos show up as shown in the image below. I see the loading bar flash, but it is a black window afterwards. 
And now comes the funny part: If I open corebird from a terminal, the videos show up normally!

![bildschirmfoto von 2015-08-02 10-03-22](https://cloud.githubusercontent.com/assets/2559413/9025254/df61b6e0-38fd-11e5-8296-abed1889fe8f.png)

**Comment by katastrophal** [comment]
In my journalctl it shows the following errors:

Aug 02 10:14:25 firefly /usr/libexec/gdm-x-session[3853]: Activating service name='org.baedert.corebird'
Aug 02 10:14:25 firefly /usr/libexec/gdm-x-session[3853]: Successfully activated service 'org.baedert.corebird'
Aug 02 10:14:26 firefly org.baedert.corebird[3905]: (corebird:12467): GLib-GObject-WARNING **: The property SoupSession:ssl-ca-file is deprecated and shouldn't be used anymore. It will be removed in a future version.
Aug 02 10:14:27 firefly org.baedert.corebird[3905]: ** (corebird:12467): CRITICAL **: UserStream.vala:240: <data>:1:8: Verarbeitungsfehler: unexpected identifier `Exceeded', expected value
Aug 02 10:14:27 firefly org.baedert.corebird[3905]: ** (corebird:12467): CRITICAL **: UserStream.vala:241: Exceeded connection limit for user
Aug 02 10:14:27 firefly org.baedert.corebird[3905]: ** (corebird:12467): WARNING **: UserStream.vala:206: buf == NULL
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GStreamer-CRITICAL **: gst_element_factory_make: assertion 'gst_is_initialized ()' failed
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GStreamer-CRITICAL **: gst_element_factory_make: assertion 'gst_is_initialized ()' failed
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GStreamer-CRITICAL **: gst_element_get_bus: assertion 'GST_IS_ELEMENT (element)' failed
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GStreamer-CRITICAL **: gst_bus_set_sync_handler: assertion 'GST_IS_BUS (bus)' failed
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GStreamer-CRITICAL **: gst_bus_add_watch_full: assertion 'GST_IS_BUS (bus)' failed
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Aug 02 10:14:38 firefly org.baedert.corebird[3905]: (corebird:12467): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

**Comment by baedert** [comment]
That sounds exactly like the bug thas was fixed for 1.0.1.

**Comment by katastrophal** [comment]
yea. sorry for the noise. Just rebuilt the fedora package with 1.0.1 and works like a charm!
