### ISSUE TITLE
I'm using corebird on Opensuse 13.2 with KDE Plasma

### ISSUE THREAD

**Issue by gooGooGaJoob** [baedert/corebird#390]
I'm unable to change the default browser, that opens up when I click on a link. I've got google-chrome set as the default but Corebird always opens up firefox.

Is there anyway I can change this?

**Comment by baedert** [comment]
https://twitter.com/corebirdclient/status/578591859120971776

Like that?

**Comment by gooGooGaJoob** [comment]
Awesome, worked like a charm. Thanks you very much.

IMO Corebird is the best Twitter Client for Linux :)

**Comment by baedert** [comment]
\o/
