### ISSUE TITLE
Filter don't work in stream mode

### ISSUE THREAD

**Issue by Zerocchi** [baedert/corebird#391]
I tried filtering some words and users using filter options, but the filtered words only disappeared when timeline isn't moving or when I restarted Corebird. The filtered words/users will keep appearing as the timeline streams.

**Comment by baedert** [comment]
What version?

**Comment by Zerocchi** [comment]
I downloaded it from the website. I guess it's version 1.0.

**Comment by baedert** [comment]
What website?! There's an about dialog you can check the version in.

**Comment by Zerocchi** [comment]
Ah sorry, it was 0.9. Should I upgrade to 1.0 then?

**Comment by baedert** [comment]
If you can: yes, of course. My memory of 0.9 isn't exactly good anymore.

**Comment by Zerocchi** [comment]
Updated to 1.0.1. Still same. The words and users still appeared as the timeline streams.

**Comment by baedert** [comment]
It definitely works here so you'll need to provide more data. What are you blocking, show a screenshot of a tweet still appearing in the timeline, etc.
Filters don't work for users, are you blocking them?

**Comment by Zerocchi** [comment]
I just want to imitate the mute function on Twitter using filter. It doesn't work for users? That's what I want to do and I thought it's gonna work.

**Comment by baedert** [comment]
But you also said you filtered words? You can't mute people from corebird and filters don't work for users, no.

**Comment by Zerocchi** [comment]
Ah my mistake. Filtered words does work but not users. Wish corebird has this feature soon. Thanks for the quick response!

**Comment by baedert** [comment]
Well nobody gives enough of a crap to even reply when I ask something, e.g. in https://github.com/baedert/corebird/issues/179. I usually don't tend to implement features in that case.
