### ISSUE TITLE
inline media preview broken since yesterday

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#395]
Since yesterday it looks like inline mediapreview is broken. When starting corebird from terminal I get the following errors:

>** (corebird:6044): WARNING **: Twitter.vala:133: Unrecognized image file format for http://pbs.twimg.com/profile_images/344513261578877263/a9729b5b25e2b6a1b2bf88dc2e359f00_normal.jpeg

>** (corebird:6044): WARNING **: Twitter.vala:133: Unrecognized image file format for http://pbs.twimg.com/profile_images/467693156893728768/n5kKTG2S_normal.jpeg

>** (corebird:6044): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/640857222956781568_15822932_0.png' contains no data

>** (corebird:6044): WARNING **: InlineMediaDownloader.vala:156: 'http://pbs.twimg.com/media/COTIP3gUcAAVOK3.jpg` couldn't be loaded from disk.

>** (corebird:6044): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/640853715382091776_313821005_0.png' contains no data

>** (corebird:6044): WARNING **: InlineMediaDownloader.vala:156: 'http://pbs.twimg.com/media/COTFDF8WIAALAAT.jpg` couldn't be loaded from disk.

>** (corebird:6044): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/640849437980532736_15822932_0.png' contains no data

>** (corebird:6044): WARNING **: InlineMediaDownloader.vala:156: 'http://pbs.twimg.com/media/COTBKtWWgAAq76b.jpg` couldn't be loaded from disk.

>** (corebird:6044): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/640842775022407680_174160697_0.png' contains no data

>** (corebird:6044): WARNING **: InlineMediaDownloader.vala:156: 'http://pbs.twimg.com/media/COS7G5ZWcAA7U4t.jpg` couldn't be loaded from disk.

>** (corebird:6044): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/640842182199394304_15822932_0.png' contains no data

>** (corebird:6044): WARNING **: InlineMediaDownloader.vala:156: 'http://pbs.twimg.com/media/COS6kYAVAAA8H5H.jpg` couldn't be loaded from disk.

> ** (corebird:6044): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/640840741942657024_2974537143_0.png' contains no data

> ** (corebird:6044): WARNING **: InlineMediaDownloader.vala:156: 'http://pbs.twimg.com/media/COS5Oh6WsAAvawK.jpg` couldn't be loaded from disk.

> ** (corebird:6044): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/633282488694108160_184203603_633282486957535232.png' contains no data

> ** (corebird:6044): WARNING **: InlineMediaDownloader.vala:156: 'https://pbs.twimg.com/tweet_video/CMnfEQ2UcAA1oHg.mp4` couldn't be loaded from disk.

**Comment by baedert** [comment]
I think I could reproduce this for a little while yesterday but not anymore, does it still happen for you?

**Comment by HeikoAdams** [comment]
The "unrecognized file format" error is still present. The other ones are gone.

**Comment by baedert** [comment]
For *new* media or only old one? Can you `rm ~/.cache/corebird/`, then start corebird again and check if it still happens?

**Comment by HeikoAdams** [comment]
It still happens even after killing the cache dir

**Comment by baedert** [comment]
Wait, we are talking about the current master version, right?

**Comment by HeikoAdams** [comment]
Yes

**Comment by baedert** [comment]
m(
This is basically the same problem as in #271. The same tweets gets quoted twice, we try to download the same media twice, try to save it to the same path twice and only one of them succeeds.

The easy short-term fix could be to just append *another* piece of information to the media path to differentiate them between quote tweets, but long-term we definitely want to just have an in-memory hashmap of the currently downloading files (and, well, maybe not save them to disk at all...).

**Comment by HeikoAdams** [comment]
What about checking if a file already exists before downloading it?

**Comment by baedert** [comment]
That would solve the error messages, but the second tweet would not get signalled when the files are successfully downloaded.

**Comment by HeikoAdams** [comment]
Is there no way to pass the already downloaded file to the second tweet if both tweets require the same file?

**Comment by baedert** [comment]
If the file is already downloaded: Yes. But that's not the interesting case. That should already work (and did in my tests)

**Comment by baedert** [comment]
Okay, just made the inline media downloading not download the same file twice at the same time. There's also a unit test to ensure it works (and it does here). Can you make sure it also works for you?

**Comment by HeikoAdams** [comment]
Okay, the only error-messages I get are:

>** (corebird:9363): WARNING **: Utils.vala:66: Image file '/home/heiko/.cache/corebird/assets/media/thumbs/642087867448172544_41116723_0.png' contains no data

>** (corebird:9363): WARNING **: InlineMediaDownloader.vala:175: 'http://pbs.twimg.com/media/COknf-XW8AAs175.jpg` couldn't be loaded from disk.

**Comment by HeikoAdams** [comment]
After updating to lastest git-master I only get the following errors:

>** (corebird:15794): WARNING **: Twitter.vala:133: Unrecognized image file format for http://pbs.twimg.com/profile_images/344513261578877263/a9729b5b25e2b6a1b2bf88dc2e359f00_normal.jpeg

**Comment by baedert** [comment]
okay that one makes sense. So I can close this one and #271.

**Comment by HeikoAdams** [comment]
Why? The images are still not displayed

**Comment by baedert** [comment]
What images? In what case? Can you just give more inormation?

**Comment by HeikoAdams** [comment]
I hope that helps
![bildschirmfoto von 2015-09-12 13-59-48](https://cloud.githubusercontent.com/assets/1418818/9831403/9af16e46-5956-11e5-86fd-352e3bd144aa.png)

**Comment by HeikoAdams** [comment]
BTW: I cleared the cache before starting corebird

**Comment by baedert** [comment]
I can't reproduce that issue at all, I tried getting more people to test it but found exactly one who was willing to try and he couldn't reproduce it either.

**Comment by HeikoAdams** [comment]
Okay, I tried again. Clearing the cache (rm -rf .cache/corebird/) and starting corebird from terminal and this time I only get the "unrecognized file format" error but still no inline preview

**Comment by remeh** [comment]
Hey,

I don't know if I have exactly the same issue but since 2 or 3 days, I've got segmentation fault which *seems* to be caused by images: 

```
** (corebird:16173): WARNING **: Twitter.vala:133: Unrecognized image file format for http://pbs.twimg.com/profile_images/568365219064578048/ZH82rnCg_normal.jpeg

** (corebird:16173): WARNING **: Utils.vala:66: Image file '/home/remy/.cache/corebird/assets/media/thumbs/646899366830075905_69004966_0.png' contains no data

** (corebird:16173): WARNING **: InlineMediaDownloader.vala:175: 'https://vine.co/v/eMn7FjnVVYl` couldn't be loaded from disk.

** (corebird:16173): WARNING **: Utils.vala:66: Image file '/home/remy/.cache/corebird/assets/media/thumbs/646897017038499841_23762505_0.png' contains no data

** (corebird:16173): WARNING **: InlineMediaDownloader.vala:175: 'https://instagram.com/p/7_8jRdkEfh/` couldn't be loaded from disk.

(corebird:16173): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(corebird:16173): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(corebird:16173): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
zsh: segmentation fault (core dumped)  corebird
```

Hope this help.

**Comment by baedert** [comment]
Great, *another* crash I can only reproduce in a non-debug build.

**Comment by remeh** [comment]
It's a corebird built from git, can I add some debug flags while compiling ? Is actually `--enable-debug` a build flag because it doesn't seem to be a runtime flag ? I've never really used Vala but I'll try to help finding the bug.

**Comment by baedert** [comment]
It's fine, I can reproduce it. Yes, `--enable-debug` should be passed at configure time (when executing the autogen.sh script), but you should get debug messages by setting the `G_MESSAGES_DEBUG` env var, i.e. `G_MESSAGES_DEBUG=all corebird`. But that likely doesn't help at all in this case :(

**Comment by baedert** [comment]
Great, seems like there's *some* bug in gio/glib, but I don't know where since I don't have debugging symbols and as soon as I compile a version (either master or 2.44) in jhbuild and try that, the bug vanishes.

**Comment by remeh** [comment]
Just FYI, I run corebird with glib 2.44.1

**Comment by baedert** [comment]
Just figured it out! It's a bug in gdk-pixbuf. And then I found out I wasn't the first one: https://bugzilla.gnome.org/show_bug.cgi?id=755269 m(

This bug should've only been in gdk-pixbuf 2.32 and my local one is 2.31 though, so I'm not sure why it still segfaults...

**Comment by baedert** [comment]
Correction: The bug is in 2.31.7 which I have locally installed and 2.32 contains a fix for it.

**Comment by remeh** [comment]
Ha! I also have gdk-pixbuf 2.31.7 :)

**Comment by baedert** [comment]
@HeikoAdams, can you confirm that gdk-pixbuf version? If you have the same, can you try to downgrade and try it again?

**Comment by HeikoAdams** [comment]
I've version 2.32.0

**Comment by remeh** [comment]
Since 2.32.1 on ArchLinux, problem fixed.

**Comment by StuntsPT** [comment]
Confirming that gdk-pixbuf 2.32.1 on ArchLinux fixes the problem.

**Comment by baedert** [comment]
@HeikoAdams Is this stil broken for you?

**Comment by HeikoAdams** [comment]
No, it seems to be fixed
