### ISSUE TITLE
Show discussion in tweet detail

### ISSUE THREAD

**Issue by varod** [baedert/corebird#396]
If we click on a tweet which replies to another one, the discussion appears. Or at least the initial tweet appears.
But when we directly click on this initial tweet the discussion doesn't appear. 

It should be great to have this feature

Thanks for this product :)

**Comment by baedert** [comment]
I don't get it? Clicking on the "initial tweet" (i.e. the begin of the discussion?) *can* show the replies just fine (you do know that you can scroll up whenever that blue bar at the top appears?), but Twitter does not have real API for it so we have to fake that in some way and it's unreliable. In can work, but it can also fail.

**Comment by varod** [comment]
I do know but I've just discovered the blue bar ... it seems doing what I've mentioned. So my issue seems not the be one :)
I've found some tweet on which i've some difference with twitter website but it should be the unreliable effect.
Thanks for your quick answer :)
