### ISSUE TITLE
Wrong tweet opened

### ISSUE THREAD

**Issue by jc00ke** [baedert/corebird#397]
The gif was the best way for me to catch it in action.

![gifrecord_2015-09-10_141526](https://cloud.githubusercontent.com/assets/18191/9801234/ae3505d0-57c6-11e5-8bc9-3ce9b638adbd.gif)

From the timeline, [@IPFS](https://twitter.com/IPFSbot)'s `RT` of [@datagrok's tweet](https://twitter.com/datagrok/status/641908163181195265) opened up [the wrong tweet](https://twitter.com/kyledrake/status/641790722937491460)

**Comment by baedert** [comment]
Did you open that tweet before clicking that link? Does it still happen after a restart?

**Comment by jc00ke** [comment]
Yes, I did open the tweet that it went to before I clicked that link.

After a restart nothing is displayed for that link:
![tweet details_002](https://cloud.githubusercontent.com/assets/18191/9806620/9c7811f4-57fb-11e5-81b0-e8fb2570c980.png)

**Comment by baedert** [comment]
Ah, that is a retweet of  https://twitter.com/datagrok/status/641908163181195265, which quotes an unavailable tweet, so we can't show it, abort somewhere and never clear the data from the TweetInfoPage (which just shows the last tweet you've opened).

**Comment by baedert** [comment]
Ok, wrote a quick error state for the TweetInfoPage:
![screenshot from 2015-09-11 12-07-33](https://cloud.githubusercontent.com/assets/887764/9812483/f1f61356-587d-11e5-8b50-279eaab628c8.png)

I think it's better than the current situation of just showing the last/no tweet in there and crashing when rt/fav/... buttons are clicked. OTOH the error messages we get from librest are not very descriptive to users, e.g. in the "not found" case we could just say something like "the tweet has been deleted" or similar.

**Comment by jc00ke** [comment]
Awesome! I wish I could build from source but I don't have `gtk >= 3.16`. Maybe once I update to `15.10`.

**Comment by baedert** [comment]
Yeah, maybe I'll won't bump the dependency to 3.18 until then :P 

Anyway, thanks for reporting!

**Comment by jc00ke** [comment]
Ha, no bumping! :wink:
