### ISSUE TITLE
Profile too big for window

### ISSUE THREAD

**Issue by elya5** [baedert/corebird#398]
The profile of [ffigurebust](https://twitter.com/ffigurefbust) is too big for the corebird window and causes rendering issues. This is the only profile that triggers the problem for me.
I am using corebird 1.0.1.

![screenshot](https://cloud.githubusercontent.com/assets/4464481/9905596/2573030e-5c86-11e5-8715-a6e126f05fa3.png)

**Comment by baedert** [comment]
Ok, don't really know how handle locations like 
![screenshot from 2015-09-16 15-29-03](https://cloud.githubusercontent.com/assets/887764/9905856/b7587d5c-5c87-11e5-9174-fa246845b09f.png)
(Yes, with all those spaces).

I guess *some* of the spaces in locations are *sometimes* useful so I can't just remove them? I'd just let the location label ellipsize at the end which is most likely better in any case but in thise case it also looks weird (Tit [long space] ...).

**Comment by elya5** [comment]
I agree. It's probably the cleanest way to just ellipsize the label.

**Comment by baedert** [comment]
Ok, fixed in master. Thanks for reporting!
