### ISSUE TITLE
crash on archlinux 

### ISSUE THREAD

**Issue by wolftankk** [baedert/corebird#404]
on the newest git version:

coredump:

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `corebird'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f15e07b81d4 in ?? () from /usr/lib/libgio-2.0.so.0
[Current thread is 1 (Thread 0x7f15e2324940 (LWP 9116))]
(gdb) bt
#0  0x00007f15e07b81d4 in ?? () from /usr/lib/libgio-2.0.so.0
#1  0x00007f15e07b8229 in ?? () from /usr/lib/libgio-2.0.so.0
#2  0x00007f15def8790d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#3  0x00007f15def87ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#4  0x00007f15def87d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#5  0x00007f15e07dc47c in g_application_run () from /usr/lib/libgio-2.0.so.0
#6  0x0000559e99572bce in ?? ()
#7  0x00007f15debba610 in __libc_start_main () from /usr/lib/libc.so.6
#8  0x0000559e99572a19 in ?? ()

**Comment by baedert** [comment]
That looks exactly like the crash mentioned in #395, i.e. caused by gdk-pixbuf 2.31.7, so you'll either have to downgrade that or wait for an upgrade (3.32.0 contains a fix).
