### ISSUE TITLE
Notifications tend to crash AppIndicator Extension

### ISSUE THREAD

**Issue by axfelix** [baedert/corebird#405]
Not sure why this is, and the fault is probably not with Corebird as the extension in question is unmaintained ... https://github.com/rgcjonas/gnome-shell-extension-appindicator

But I'm fairly certain I've never seen any other application's notifications crash the extension, whereas Corebird's do quite frequently. Any idea why that might be?

**Comment by baedert** [comment]
It might be because corebird uses `GNotification` and not `NotifyNotification` but I have no clue about that extension. Both nautilus and gnome-software seem to use `GNotification` in recent versions (i.e. I just `ag`'ed that in my jhbulid checkout), are you not using them or do their notifications just not crash the extension?

**Comment by axfelix** [comment]
I'm using both nautilus and gnome-software (fairly standard Arch Gnome 3 setup), but they don't trigger notifications particularly often relative to Geary, Empathy, and Hexchat, which I get all the time and don't seem to be as brittle -- so this is a pretty good working theory. It's almost definitely the extension's "fault," though, so I wouldn't expect you to fix this.

**Comment by baedert** [comment]
Okay, closing this then.

**Comment by axfelix** [comment]
PS -- I just realized from trying to run this on my Ubuntu/Unity machine now that it's updated to 16.04 and has less broken Gtk3 support -- GNotification isn't very well supported under Unity (it just creates an unthemed popup window rather than hooking into notify-osd. It's still a little unstable with some shell extensions under my Arch/Gnome 3 environment, but works as desired there. Is there any reason you aren't using NotifyNotification?
