### ISSUE TITLE
Videos not playing on Wayland

### ISSUE THREAD

**Issue by ianbrunelli** [baedert/corebird#406]
I have the following output when trying to open videos:

```
(corebird:2231): GLib-GObject-WARNING **: invalid cast from 'GdkWaylandWindow' to 'GdkX11Window'

(corebird:2231): Gdk-WARNING **: gdkwindow-x11.c:5540 drawable is not a native X11 window
```

Are you planning to port the media player to use `gtkgst`? Or at least force the app to use XWayland for now?

**Comment by baedert** [comment]
> Are you planning to port the media player to use `gtkgst`?

Exactly that.

> Or at least force the app to use XWayland for now?

Is that just a suggestion or have you actually tried that this makes it work?

**Comment by ianbrunelli** [comment]
> Is that just a suggestion or have you actually tried that this makes it work?

Only a suggestion. But I ran it with `GDK_BACKEND=x11` and videos still don't work (no error on terminal, though, and now the video area is black), so I think this wouldn't help.

**Comment by baedert** [comment]
FYI there's now a `gtkgst` branch that uses gtksink and seems to work fine for me on wayland.

**Comment by ianbrunelli** [comment]
Working as expected :D 

Is there any particular reason for you to have chosen `gtksink` instead of `gtkglsink`?

**Comment by baedert** [comment]
Not really, just that judging from the examples gtksink is more what I want, i.e. just a video widget while the gtkglsink example shows the testsrc in a rotating cube :)

**Comment by ianbrunelli** [comment]
I see... I just asked because I had a better performance when using `gtkglsink` (`gtksink` feels a bit laggy in here), but I have no technical knowledge in this matter.

**Comment by baedert** [comment]
Just quickly tried it, doesn't seem to play the video here with my current implementation :/

**Comment by ianbrunelli** [comment]
For the `gtkglsink` you need to create a `glsinkbin` first.

Here are two code samples in Python:

- [gtksink](http://ur1.ca/nwwc3)

- [gtkglsink](http://ur1.ca/nwwcc)

**Comment by baedert** [comment]
Yeah I was talking about my implementation in corebird, not really in the mood of changing all that to try gtkglsink

**Comment by ianbrunelli** [comment]
> not really in the mood of changing all that

No problem. I thought it'd be simple because it's only three different lines in Python, but I know that Vala is certainly a lot more complex than that.

**Comment by ianbrunelli** [comment]
So, I played a bit with it and wrote this patch¹, which is working fine in here, and the video is playing smoother than before.

1: https://paste.fedoraproject.org/274620/44397487/

**Comment by baedert** [comment]
If asked around and apparently gtkglsink doesn't work correctly with both nouveau and radeon drivers. Unfortunately the call to `gst_element_factory_make` still succeeds with those drivers and everything appears  to work etc. until it crashes (or just doesn't work I guess, the symptoms may vary), so we can't just use gtkglsink and gtksink as fallback.

**Comment by ianbrunelli** [comment]
So, I can speak about the radeon issue: it only happens in X11 (afaik), and it makes the window stop redrawing¹, but only in some cases. From what I heard, I think the nouveau issue is similar.

In Corebird, however, everything is working fine for me on both Wayland and X11.

1: [Bug 91930 - Program with GtkGLArea widget does not redraw](https://bugs.freedesktop.org/show_bug.cgi?id=91930)

**Comment by baedert** [comment]
Just tried to test it with nouveau and that was a big mistake, won't do that again.
I'd just way we could use glsink and see how people react, but juding from past experience, nobody will say anything until I make a release and then everybody will.

But generally -- what do you mean exactly when you say that glsink plays yhe video smoother? I was hoping that that not to make any impact. 

The only problem with the current implementation I have is that there seems to be some lag when looping the video, but I have not found a way to do that really with `GstAppSrc`, I probably need to investigate some more and fix that. Or maybe I just hope for nobody to notice. Also we have to ship our own gstreamer-1.0.vapi because the bindings are broken once again.

**Comment by ianbrunelli** [comment]
> Just tried to test it with nouveau and that was a big mistake, won't do that again.
> I'd just way we could use glsink and see how people react, but juding from past experience, nobody will say anything until I make a release and then everybody will.

I think considering it is broken with nouveau, this is not really a good idea.

If you think gtksink works fine, then you should release it, and then evaluate the possibility to move to gtkglsink after the bugs are fixed.

> But generally -- what do you mean exactly when you say that glsink plays yhe video smoother?

For me it seems like the fps is higher on gtkglsink. In gtksink I notice that the frames are "jumping" (like if it skips some frames), but in gtkglsink everything plays very fluidly.

> The only problem with the current implementation I have is that there seems to be some lag when looping the video

Really? Everything seems normal in here (with both gtksink and gtkglsink).

**Comment by baedert** [comment]
>> Just tried to test it with nouveau and that was a big mistake, won't do that again.
>> I'd just way we could use glsink and see how people react, but juding from past experience, nobody will say anything until I make a release and then everybody will.

> I think considering it is broken with nouveau, this is not really a good idea.

I meant: since you use radeon but it works for you in corebird, that might be also the case for nouveau so it just wouldn't be an issue at all.

I'll just merge the branch into master now and see how that works out.

**Comment by ianbrunelli** [comment]
> I meant: since you use radeon but it works for you in corebird, that might be also the case for nouveau so it just wouldn't be an issue at all.

Yeap. The issues with gtkglsink in radeon begin when you add other widget(s) into the window (HeaderBar, Buttons, etc.), but the video dialog is "empty", so everything works fine. I believe the nouveau issues are similar (taking in consideration some IRC talks I read), but it would be nice to have someone with nouveau trying it.

**Comment by baedert** [comment]
Closing this, since the original issue is fixed. gtkglsink seems to work with radeon and I'll try to find someone with nouveau to test it at some point. 

Thanks for reporting the bug and the additional investigation!
