### ISSUE TITLE
corebird crash on data loading

### ISSUE THREAD

**Issue by webczat** [baedert/corebird#408]
Hello.

In case of the newest corebird, it often, but not always, crashes on startup, and always when I scroll tweets down enough to cause it to try to load more data.
I am a blind user with a screenreader enabled, but I do not think it is related.

**Comment by baedert** [comment]
yeah you'll have to downgrade your installed gdk-pixbuf version from 3.31.7 to basically anything else. You can of course also downgrade corebird, but it will then also crash when downloading any gif file.

**Comment by webczat** [comment]
Actually, upgrading gdk-pixbuf beyond the version you said to be problematic also seems to work, there is one in arch testing repo.

**Comment by baedert** [comment]
Of course. Everything besides 2.31.7 works.
