### ISSUE TITLE
Sidebar icons are very small (and less tall) in 1.1

### ISSUE THREAD

**Issue by axfelix** [baedert/corebird#409]
Unless this is some gtk version change that I'm not conscious of (which is possible), it looks like the sidebar icons are now square rather than being slightly taller than they are wide? There's plenty of whitespace on the sidebar, I'd like to see the old version restored. In Numix (the default theme for Gnome 3 in Antergos), they're pretty tiny this way.

**Comment by baedert** [comment]
Nothing changed there on my side for 1.1, unless you just did a transition from 0.8 to 1.1.

**Comment by axfelix** [comment]
Odd. I actually switched from a git commit slightly pre-1.1 (https://aur.archlinux.org/packages/corebird-git/) to the 1.1 freeze (https://aur.archlinux.org/packages/corebird/). I doubt it has anything to do with my having manually updated gdk-pixbuf to 2.32 to avoid the crash? It probably is a gtk thing.
