### ISSUE TITLE
duplicate tweets in list

### ISSUE THREAD

**Issue by charlesay** [baedert/corebird#414]
all tweets in some of my lists are displayed twice.

**Comment by baedert** [comment]
Cool.

**Comment by MrPrimate** [comment]
Was this issue fixed, as it still occurs in my Ubuntu package on 16.04 v 1.2.2-1

**Comment by baedert** [comment]
I've never seen it, there's absolutely no description of how it happened, etc. so no I didn't fix it but no there never was any bug I could fix.

**Comment by charlesay** [comment]
I am sorry I wasn't able to provide more info when I reported this issue, and still can't.

This behaviour occurs occasionally  (ie not everytime I view a list timeline) and I don't see any info about it in either the output of corebird launched in a terminal or journalctl. where might it be found?

**Comment by MrPrimate** [comment]
Hmm, this happens pretty consistently with my version of corebird. When I visit the first list, everything is fine, but when I go to check another, that's when I get duplicates.

**Comment by charlesay** [comment]
yes, but even from the first occurrence on it happens inconsistently (with only  some lists, not on every view of a list)

**Comment by MrPrimate** [comment]
Actually I lie, the duplicates only appear if I have scrolled down the list and caused a new fetch of data in the first list, then duplicates appear when I visit other lists.

However, having just checked this a bit, it doesn't always create duplicates. Just on some of the lists.

**Comment by baedert** [comment]
That's something I can work with and reproduce.

**Comment by MrPrimate** [comment]
Thanks!
