### ISSUE TITLE
Big window border in fresh installed Ubuntu 15.10

### ISSUE THREAD

**Issue by ivlevdenis** [baedert/corebird#418]
![screenshot](http://storage5.static.itmages.com/i/15/1028/h_1446030855_7398895_85852dcb17.png)

**Comment by baedert** [comment]
You updated ubuntu and not corebird, didn't you?
Ask the ubuntu support about that.

**Comment by ivlevdenis** [comment]
@baedert "Big window border in fresh installed Ubuntu 15.10"

**Comment by baedert** [comment]
So? I didn't change anything, yet the appearance changes depending on the ubuntu version, i.e. ubuntu changed something and I didn't. It look normal under other DEs.

**Comment by loxK** [comment]
Same issue

**Comment by loxK** [comment]
No other app has this issue. So ?

**Comment by loxK** [comment]
Here is a quick fix: http://www.webupd8.org/2015/11/fix-large-black-borders-around-header.html
