### ISSUE TITLE
Can't Get To Own Profile

### ISSUE THREAD

**Issue by bendangelo** [baedert/corebird#419]
I don't see any buttons that would get me to view my own profile.

**Comment by KamranMackey** [comment]
To get to your profile you click on your profile picture...

**Comment by zzzeek** [comment]
what I do right now is:  1. go to the search  2. search for yourself  3. click that.   

But this is a pretty major missing feature.

If there's curiosity why this feature might be useful, at the very least it's common to have the use case of, "oh crap, what did I tweet last night", or "on second thought, I should delete that tweet", etc.

**Comment by archdria** [comment]
I think a good intuitive way to achieve this would be by going to your account icon (top left) and then, clicking on the account (image, @name, etc) should open the profile.

**Comment by baedert** [comment]
master has a button per account row in the accounts popover now.
