### ISSUE TITLE
Call to gtk-update-icon-cache missing on make install

### ISSUE THREAD

**Issue by zedtux** [baedert/corebird#425]
After having cloned, autogened, and maked, doing `sudo make install` is copying the icon files, but the GTK icons' cache isn't refreshed which leads the user to see the standard icon for apps without icon, until the user restart or execute a call to `gtk-update-icon-cache` like the following:

```
~ • sudo gtk-update-icon-cache /usr/share/icons/hicolor
[sudo] password for zedtux: 
gtk-update-icon-cache: Cache file created successfully.
```

Then the corebird icon is visible everywhere (application switch, the about window and so on).

**Comment by baedert** [comment]
Yeah, but that's normally the package managers task (which could e.g. call gtk-update-icon-cache only once after installing n packages with icons).

**Comment by zedtux** [comment]
You're right. Maybe the documentation could be updated and explain that compiling from sources needs then for GTK to execute `gtk-update-icon-cache`, with KDE execute `...` etc  ..., couldn't be ?

**Comment by zedtux** [comment]
Thank you @baedert :)
