### ISSUE TITLE
list failing to refresh

### ISSUE THREAD

**Issue by charlesay** [baedert/corebird#426]
Refreshing lists by means of the button on the top of one doesn't work. New content is displayed when the view is switched elsewhere and one then returns to the list in question (this did not work some times in the past but that could not be reproduced when debug output was enabled).

a log of a session that should show it is pasted here: https://paste.gnome.org/pxkdsj6vw

**Comment by baedert** [comment]
You aren't per change building the git version and can check if it still happens after that patch?

**Comment by charlesay** [comment]
is there a way to transfer the existing account-authentication to a new installation of the git version? I think I could not newly authenticate with twitter right now

**Comment by baedert** [comment]
The accounts are saved in your home directory so that shouldn't matter

**Comment by charlesay** [comment]
seems to be working fine in the git version, thanks!

**Comment by baedert** [comment]
okay, no problem.
