### ISSUE TITLE
Don't change favorite icon to heart

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#428]
Twitter recently changed the icon for favoriting tweets from a star to a heart. Please don't follow this ugly decision and keep the star

**Comment by mralext20** [comment]
how about allowing the option to change to the heart?

**Comment by HeikoAdams** [comment]
That would be an acceptable solution - if the default is "star" ;-)

**Comment by baedert** [comment]
> how about allowing the option to change to the heart?
No.

> That would be an acceptable solution[...]
No it wouldn't.

**Comment by baedert** [comment]
Merged  #429.
