### ISSUE TITLE
Inline media preview for myvideo videos

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#430]
MyVideo is a very popular german video portal and it would be nice if corebird could provide inline preview for myvideo links like http://www.myvideo.de/musik/the-chemical-brothers/galvanize-video-m-8209964

**Comment by baedert** [comment]
I don't see an easy way to extract the actual video url from the html code. But we can't really embed myvideo videos because they can be arbitrarily long and we currently have to download the entire video before playing it.
