### ISSUE TITLE
Corebird crashes when opening a tweet containing a video

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#431]
When trying to open a tweet which contains a video corebird crashes with the following error message:
>CRITICAL **: MediaVideoWidget.vala:126: Could not create a gtksink. Need gst-plugins-bad >= 1.6

**Comment by baedert** [comment]
And you have gst-plugins-bad>=1.6?

**Comment by HeikoAdams** [comment]
Yes, I think so
>$  rpm -qa gstreamer1-plugins-bad\*
>gstreamer1-plugins-bad-free-extras-1.6.1-1.fc23.x86_64
>gstreamer1-plugins-bad-free-1.6.1-1.fc23.x86_64
>gstreamer1-plugins-bad-freeworld-1.6.1-1.fc23.x86_64

**Comment by baedert** [comment]
welp, can you run something like `G_MESSAGES_DEBUG=all corebird --gst-debug-level=5` and try opening a video that way? Or if it's too much output, try a lover value?

By opening the tweet you mean clicking on the video preview image, right?

**Comment by HeikoAdams** [comment]
>By opening the tweet you mean clicking on the video preview image, right?
Yes, you're right.

A (hopefully complete) output of your debug command can be found there: https://dl.dropboxusercontent.com/u/1948249/corebird_debug.txt

**Comment by baedert** [comment]
fwiw I talked to the maintainer of that package about why gtksnk would be missing (apparently they can just build gst-plugins-bad without it), but I did not get a response yet...

**Comment by HeikoAdams** [comment]
According to the changelog of the latest build of that package it seems the maintainer has fixed that problem:
> * Mon Nov 09 2015 Wim Taymans <wtaymans@redhat.com> - 1.6.1-2 - Enable more plugins: gtksink, webp, bluez, bs2b, gme, ofa, openal, opencv, openjpeg

**Comment by baedert** [comment]
Sucks that the check for gstreamer-plugins-bad >= 1.6 is not enough, but I hope other distributions have it enabled...
Anyway, closing this then, reopen it if there are still problems after you received that update.

**Comment by HeikoAdams** [comment]
Tested on Fedora 23 with the update (currently in testing-repo) applied and works fine so far
