### ISSUE TITLE
Researcher -> rechercher

### ISSUE THREAD

**Issue by eseyman** [baedert/corebird#433]
I use corebird as provided by Fedora (Corebird 1.1 on Fedora 22). When using the search function, I'm presented with a form button that reads "Researcher". The french word is, in fact, "Rechercher".

**Comment by baedert** [comment]
As the readme states, translations are managed through transifex, so you can fix it there.

**Comment by eseyman** [comment]
Indeed. I took a look in transifex and the issue is fixed there.
