### ISSUE TITLE
Missing inline-preview for twimg.com

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#438]
If a tweet contains a link to Twitters own image/video hosting service (i.e. https://amp.twimg.com/v/e9afe290-b796-49ed-b80d-3aba49d43288) there is no inline-preview.

**Comment by baedert** [comment]
I know, twimg images shoudl already work, but there's no reliable way to get the mp4 file from the html code of the amp.twimg site, so we can't use that. Also those videos have arbitrary l;ength which would make it difficult in any case.
