### ISSUE TITLE
Stalled functionality when idle

### ISSUE THREAD

**Issue by quantalmax** [baedert/corebird#439]
Using Corebird 1.1 from Fedora 23 Repositories on Gnome Shell (Linux Kernel 4.2.5-300.fc23.x86_64)

After approx. 1 minute of idle time Corebird refuses to display 'Mentions' and 'Favourites', 'Search" stops working. 'Home' seems to get updated though and the client is overall working and responsive.

I already checked time zone settings' consistency among twitter.com and my system. I am located in Austria(Austrian date/time/number formats) yet I have English(US) system-wide as language preference. May that cause the malfunction?

Regards

**Comment by baedert** [comment]
Can you run `G_MESSAGES_DEBUG=all corebird` and paste the output when that is happening? I have a suspicion (in which case I can do nothing about it, but anyway.)

**Comment by quantalmax** [comment]
I messed with the timeserver settings and everything but the search function seems to be fine now. When the search crashes after some positive results I get:
`(corebird:4086): Gtk-CRITICAL **: gtk_list_box_row_grab_focus: assertion 'box != NULL' failed`

Thanks for the immediate response and the superb maintenance.

**Comment by baedert** [comment]
How did you cause that critical? Did you search something, then get to some other page and pack to the search after a while?

**Comment by quantalmax** [comment]
Exactly. Launch corebird. Go to search tab, search for any flag or hashtag, getting expected results. Switch to home tab. Leave it idle for some time. Still getting tweets. Go back to search tab. Type in any query and it just keeps loading without any results. The rest of the application keeps working flawlessly.

**Comment by baedert** [comment]
I meant the crash, but I think I fixed that in master after you mentioned it. You're probably getting some console output saying the request timed out after some time; I still have no idea why that is happening (I asked on Twitter if that's happening to anyone else besides me but didn't get an answer) and I can't reproduce it reliably so I think it's a server-side problem and nothing I can fix unfortunately.
