### ISSUE TITLE
Refresh favourites

### ISSUE THREAD

**Issue by nifker** [baedert/corebird#442]
Is it possible to refresh my favourites?

**Comment by baedert** [comment]
Refresh after what happened?
New favorites should be added automatically.

**Comment by nifker** [comment]
Not happening not even if I click on favourites again.

**Comment by baedert** [comment]
Clicking on it again doesn't change a thin. Refresh after *what*? What did you do or didn't to, what to d you expect to see, etc. I really don't want to ask you a question for every single piece of information.

**Comment by nifker** [comment]
I favourited a post and it doesnt show in the favourites.

**Comment by baedert** [comment]
Fixed in master.
