### ISSUE TITLE
[featurerequest] Multicolumn 

### ISSUE THREAD

**Issue by arthurlogilab** [baedert/corebird#443]
It would be nice to be able to use corebird with multiple columns (main timeline, lists, searches, mentions).

**Comment by baedert** [comment]
I said this a hundred times already, but that's not going to happen. Too much work, not enough time, not enough people.

**Comment by arthurlogilab** [comment]
If someone in the community where to work on this, would you welcome a pull request ?

**Comment by arthurlogilab** [comment]
Do you have links to the "hundreds" of times you have answered to this feature request ?

**Comment by baedert** [comment]
> If someone in the community where to work on this, would you welcome a pull request ?

That would be a change in the thousands of changed LOC; it changes almost everything about the UI and there are no standard widgets in gtk+ for a lot of things you want to do. And in the end, I have to maintain it.

> Do you have links to the "hundreds" of times you have answered to this feature request ?

No.
