### ISSUE TITLE
[featurerequest] images not cropped

### ISSUE THREAD

**Issue by arthurlogilab** [baedert/corebird#445]
Would it be possible to have an option to show full thumbnails of the images posted by users instead of a cropped image ?

**Comment by baedert** [comment]
> Would it be possible to have an option

As a rule: No.

This is already in master.

**Comment by arthurlogilab** [comment]
Which version is that going to be ? (am on 1.0.1)

**Comment by baedert** [comment]
The next one, so 1.2.

**Comment by arthurlogilab** [comment]
good news, thanks.
