### ISSUE TITLE
Open Links in Backgroud

### ISSUE THREAD

**Issue by 19kestier** [baedert/corebird#447]
I like to go through my tweets and open all of the news links I find interesting, but Corebird sends the focus to the Firefox every time I click a link. Is there any way to have it open links in the background?

**Comment by baedert** [comment]
No, and that's also why we can't change that.

**Comment by step-artur87** [comment]
Hi. To avoid switching to Firefox You can make Corebird always in top (if Your OS allow it).

**Comment by viciousvm** [comment]
Hi all :-) If Corebird window is active, press ALT-SPACE and select Always on top (in Linux )
