### ISSUE TITLE
Feature Request: Help page/Window explaining shortcuts

### ISSUE THREAD

**Issue by pludi** [baedert/corebird#450]
Currently everyone getting acquainted with Corebird has to look up the shortcuts on the GitHub page. And even those seem to be out of sync with ui/shortcuts-window.ui as far as descriptions are concerned.

Would it be possible to add that information to eg. the settings dialog?

**Comment by baedert** [comment]
> And even those seem to be out of sync with ui/shortcuts-window.ui as far as descriptions are concerned.

What what what.

Well, adding that sounds literallt just like adding a shortcuts window, which ui/shortcuts-window is for. The settings dialog seems like a weird place since you can't edit them (don't ask for a UI to edit them).

**Comment by pludi** [comment]
I'm not asking for a feature to edit the shortcuts, but rather something like an about page, which might be found among the other pages in a settings dialog.

Aside from that, while there is a window defined in the source, I've yet to find a way to display that dialog (XFCE4 on Fedora 23).

**Comment by baedert** [comment]
> I'm not asking for a feature to edit the shortcuts, but rather something like an about page, which might be found among the other pages in a settings dialog.

I know.

> Aside from that, while there is a window defined in the source, I've yet to find a way to display that dialog (XFCE4 on Fedora 23).

It requires gtk+ >= 3.19

**Comment by ricardoborgesjr** [comment]
Maybe a Mallard help file to view with Yelp (or another viewer)

**Comment by pludi** [comment]
> It requires gtk+ >= 3.19

So, unless we're on a bleeding-edge distro like Arch, or always compile GTK+ plus dependencies ourselves, we're looking at 5 (Ubuntu 16.04) to 6 months (Fed 24 in May 2016) before the first big Desktop distros will ship the GTK+ version required for the help page to display.

Me, I'm fine with that.

However, new users might rather look for Help using the F1 key, or the About/Settings-Dialog, instead of trying Ctrl/Command/...+F1 (if I read the mapping in [src/Corebird.vala for v1.1](/baedert/corebird/blob/2144fa5a95e3a435336b70f0a3a67924d8a4760f/src/Corebird.vala#L180) right).

Closing the issue since my requested feature already exists.

**Comment by baedert** [comment]
gtk+ 3.20 will be released in march, so Ubuntu 16.04 could technically ship it, yes. However, they always ship an older version (which is why 15.10 ships with 3.16 and not 3.18).

Welcome to Linux distros.

> However, new users might rather look for Help using the F1 key, or the About/Settings-Dialog, instead of trying Ctrl/Command/...+F1 (if I read the mapping in src/Corebird.vala for v1.1 right).

We could add F1 additionally, the current ones are just the shortcuts GtkApplication gives you by default if you decide to use that feature. But an entry in the app menu would also be nice, I just havent found the nerves to make that work depending on the used gtk+ version (ideally at runtime...).
