### ISSUE TITLE
SVG icons don't scale down fully

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#451]
I have an odd issue that only seems to affect one of my two machines, but I think it is something Corebird can fix.

On my openSUSE Leap 42.1 machine (GTK 3.16.7) all of the custom Corebird SVG icons in the header bar and for the Mentions/DMs/Filters are larger than the ones taken from the system theme.

![screenshot from 2015-12-09 20-26-12](https://cloud.githubusercontent.com/assets/388582/11697788/4385b0de-9eb3-11e5-95b8-686a87589abd.png)

On my openSUSE Tumbleweed machine (GTK 3.18) all of the custom Corebird SVG icons render properly.

According to [this forum post](https://bbs.archlinux.org/viewtopic.php?id=188502), GTK 3.14 changed something where GTK honours the minimum size set in the icon theme.

If I edit /usr/share/icons/hicolor/index.theme and replace "MinSize=32" with "MinSize=16" for all "scalable/*" entries then the custom SVGs render at the correct size. That's obviously not a practical option, though.

According to the same forum post, there's a constant called GTK_ICON_LOOKUP_FORCE_SIZE that you can pass to force scaling to a size outside the icon theme's range. I think that all that is required to fix this on GTK 3.16 with large MinSize on scalable images is for Corebird to somehow specify it for its custom SVGs.

Unfortunately, I've not found how to add it in the Vala code, and after upgrading to Glade 3.19 to get it to load the .ui files then I can't see how to define it in there.

**Comment by baedert** [comment]
> If I edit /usr/share/icons/hicolor/index.theme and replace "MinSize=32" with "MinSize=16" for all "scalable/*" entries then the custom SVGs render at the correct size. That's obviously not a practical option, though.

Why does it even say MinSize=32?

> I think that all that is required to fix this on GTK 3.16 with large MinSize on scalable images is for Corebird to somehow specify it for its custom SVGs.

It has worked fine, since forever for me, so I don't know why this would need a fix in applications.

We are passing `GTK_ICON_SIZE_BUTTON` there, which is basically by definition correct and 16px.

**Comment by IBBoard** [comment]
My understanding from the forum post I linked to is that it says "MinSize=32" for all "scalable" icons because they don't want to shrink icons too small (because an SVG designed for 256px+ will look terrible at 16px - it probably won't look great at 32ps either, but it might be passable) and they expect 16px PNGs to exist, but that the changed GTK behaviour means that it doesn't behave like that now.

The issue is then a fight between Corebird passing GTK_ICON_SIZE_BUTTON and saying "give me 16px icons" and GTK 3.14+ changing its behaviour compared to previous GTK and saying "sorry, I only have corebird-compose-symbolic in SVG and it icon theme says don't shrink it below 32px, so here's a 32x32 copy".

Based on [this patch](https://mail.gnome.org/archives/commits-list/2015-February/msg07043.html) that Evolution did then it is a separate flag from the icon size when done in code, but these icons are done from a Glade file and so I can't find the option.

**Comment by baedert** [comment]
> My understanding from the forum post I linked to is that it says "MinSize=32" for all "scalable" icons because they don't want to shrink icons too small (because an SVG designed for 256px+ will look terrible at 16px - it probably won't look great at 32ps either, but it might be passable) and they expect 16px PNGs to exist, but that the changed GTK behaviour means that it doesn't behave like that now.

They are scalable. they are supposed to be scaled. They even have a -symbolic prefix, so they constist of a single shape with a single color.

I don't see a MinSIze=32 for any scalable/ directory in the upstream index.theme. Is that only in the 3.16 one?

I don't even know if/why anything from hicolor would matter. The icons have been compiled into the binary for an eternity now. Do you have old corebird icons in your hicolor directory?

**Comment by IBBoard** [comment]
Sorry, I added an edit.

They are scalable, but openSUSE puts sensible min and max sizes because it is allowed in icon theme definitions and SVGs still have a minimum size that they'll look good at. The patch is actually https://build.opensuse.org/package/view_file/openSUSE:Leap:42.1/hicolor-icon-theme/hicolor-scalable-sizes.patch?expand=1. GTK is now honouring it.

I don't believe I have any icons left over. My best guess why hicolor MinSize affects it is because it is the fallback theme.

The MinSize was added by openSUSE for a reason. GTK changed to honour the minimum size for a reason. They also added a way to override it if the app developer really wants to. It just needs Corebird to do define it however is necessary.

**Comment by baedert** [comment]
> [...] openSUSE puts sensible min and max sizes [...]

I read that as "arbitrary" but ok :P

The right fix here is apparently to install symbolic icons into `symbolic/` instead of into `scalable/`, I see if I can come up with something...

**Comment by IBBoard** [comment]
I think that putting the limit in is sensible, because most SVG is designed for 256px and higher so will look terrible at 16px, but I agree that the 32px minimum is a bit of an arbitrary limit.

I've just checked my openSUSE Tumbleweed machine and it does still have MinSize=1 for scalable/*, which is why the icons worked there but not on Leap.

I'll try to get a build done this weekend and test it out. Thanks.

**Comment by kanishkablack** [comment]
I guess its working fine on Suse Leap

**Comment by IBBoard** [comment]
Just rebuilt and it works fine on Leap now. Checking the index.theme for hicolor, the MinSize is set as 8 for symbolic.

Thanks.
