### ISSUE TITLE
Corebird loses tweet if Twitter rejects it

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#466]
Related to #460, but potentially relevant for other situations.

If you write a tweet and then Twitter rejects it (e.g. because the tweet is too long and Corebird miscounted, before #460, but potentially for other reasons like Twitter being down or timing out) then the compose window has already closed before the "posting tweet failed" message pops up. At this point, the content of the tweet is lost and needs to be typed again.

It'd be more helpful if Corebird didn't lose failed tweets (e.g. by not closing the compose window until it has successfully posted to Twitter - although there might be reasons why that is bad).

**Comment by baedert** [comment]
master keeps the written tweet around now.
