### ISSUE TITLE
Conversations not properly displayed anymore(?)

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#469]
It looks like the latest git revision has a problem in displaying conversations. If I i.e. open the following tweet (https://twitter.com/csickendieck/status/676838489829343232) in corebird the related tweets are not listed but the conversation icon is shown in my timeline.

![bildschirmfoto von 2015-12-15 20-04-52](https://cloud.githubusercontent.com/assets/1418818/11820920/3634a1f2-a367-11e5-85b1-5be507fcd2d2.png)
![bildschirmfoto von 2015-12-15 20-04-58](https://cloud.githubusercontent.com/assets/1418818/11820921/36399f36-a367-11e5-8bfa-5b407780c177.png)

**Comment by baedert** [comment]
Hmm, that works just fine here for that tweet. That's not with gtk+ master from a few hours ago, right?

**Comment by HeikoAdams** [comment]
No, its with gtk 3.18.6 from Fedora 23

**Comment by Lyude** [comment]
I think this is actually a problem with the Twitter API now, Twidere recently had similar issues and they added a bit of text below the related tweets with a hyperlink explaining that they couldn't display the related tweets due to API limitations.

**Comment by baedert** [comment]
Is this still a problem?

**Comment by HeikoAdams** [comment]
I think no

**Comment by baedert** [comment]
okay \o/
