### ISSUE TITLE
CoreBird doesn't open browser when "Request Pin" is clicked

### ISSUE THREAD

**Issue by bijanebrahimi** [baedert/corebird#470]
Hi, I just installed corebird ([corebird](https://aur.archlinux.org/packages/corebird/) from arch linux AUR repo)

The problem is when I click "Request PIN", there is no browser window opening. as I investigate though the code, I found [launch_default_for_uri](https://people.gnome.org/~gcampagna/docs/Gio-2.0/Gio.AppInfo.launch_default_for_uri.html) responsible to open the proper application to open the URI. since i'm not using GNOME Desktopn Environment (Currently I'm using i3, a tilling window manager for Linux), it somehow fails  to find te proper [GUI] application yet it return no error.

so, how to investigate further?
Thanks in advance

**Comment by baedert** [comment]
Does "it returns no error" mean that it doesn't print any to the console either?
Did you [set your default browser](https://wiki.archlinux.org/index.php/xdg-open#Set_the_default_browser)?

**Comment by hiraethmarkb** [comment]
I am seeing the same issue on XFCE (Fedora 25), following the steps outlined by bijanebrahimi.

I have my default browser set, running `exo-open --launch WebBrowser` opens whatever has been set as the default (I have even tried changing it to other browsers, Firefox, Chrome, Opera, etc).

In all cases, whatever is set as default is opens when running `exo-open --launch WebBrowser`.

Regardless of the browser set as default, clicking 'Request Pin' returns no error either in the console or in the gui.

Corebird installed from Flatpak.

**Comment by hiraethmarkb** [comment]
My apologies, didn't realise that this issue had been closed. Created a new one at https://github.com/baedert/corebird/issues/654
