### ISSUE TITLE
URLs with preceding punctuation aren't counted as URLs

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#471]
If you post a tweet with a URL in brackets then Corebird treats the URL as text. If the URL is long then this causes problems!

Example tweet:

```
My build of @Corebird (https://software.opensuse.org/download.html?project=home%3AIBBoard%3Adesktop&package=corebird) now comes with more theme compatibility for Adwaita-compliant themes
```

Corebird count: -46 left
Twitter count: 24 left

Put a space between the bracket and the "https" and Corebird colours the URL as a link and shows a count of 24 left (because it also includes the closing bracket in the URL, which Twitter doesn't)

**Comment by baedert** [comment]
This is correctly counted now, but not correctly annotated as a link in the compose window.

**Comment by baedert** [comment]
Should work now
