### ISSUE TITLE
Link colour isn't used for hashtags in compose, is used in timeline

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#473]
My GTK theme has green links. In the timeline I get green hashtags because they're links. The compose view uses the default "Adwaita blue".

![corebirdlinkcolour](https://cloud.githubusercontent.com/assets/388582/11983333/90a691d8-a9aa-11e5-9273-67adeb4d41b8.png)

**Comment by baedert** [comment]
Does that still happen after f7b811fa6566bbc83b86688337427bbe5afeef4b?

**Comment by IBBoard** [comment]
No, that fixes it. Thanks.
