### ISSUE TITLE
Add direct link to polls

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#475]
I don't like polls, but not everyone flags when a post is a poll. While implementing the poll is probably impossible, it'd be good if we could have a link to the tweet on Twitter underneath the text of the tweet in Corebird so that we a) know that there is a poll and b) can quickly jump to the poll if we care.

**Comment by StuntsPT** [comment]
+1

**Comment by IBBoard** [comment]
Does anyone even have a reference of what the structure looks like in JSON? I've not been able to find anything in the Twitter dev docs.

**Comment by baedert** [comment]
What structure?

**Comment by IBBoard** [comment]
Whatever keys/properties/etc Twitter have in their JSON to say "this tweet is a poll" that would let clients either display the poll or (more likely) provide a link to the web page with the poll on it.

**Comment by baedert** [comment]
Polls are not public API, there's nothing like that. You can press `k` on ever tweet row to get the json from it when built with `--enable-debug`.

**Comment by IBBoard** [comment]
I'm not surprised that the poll itself isn't public API (so you might only know that a tweet has a poll, not what the poll is or what the options are) but not even marking the poll as a poll seems… bad.

And having just checked, you're right - Twitter don't even mark polls as polls. I guess that means this one's completely impossible until Twitter changes its mind and at least _flags_ them as polls :\

(Knowing about "k" is useful, though - I wondered if I could find a way to see tweet JSON. Useful to be able to print selected ones to the console)

**Comment by IBBoard** [comment]
Vaguely related to #317 in that it is something Twitter doesn't do an API for yet.

**Comment by Vistaus** [comment]
In that case we must go to the Twitter community page and ask them to open up the Poll API. I want polls as well, btw. Even a link would be fine, at least a link is better than having to go manually to someone's profile and look for the poll.

**Comment by IBBoard** [comment]
Polls apparently are now public API to some degree - but they're a "premium" feature.

https://developer.twitter.com/en/docs/tweets/enrichments/overview

Closing on the basis that Twitter won't even let the API tell you that a poll exists.

**Comment by Vistaus** [comment]
@IBBoard The cheapest plan is $149. It's certainly possible, but we need to get a lot of users to back Timm on Patreon in order for him to pay that.
