### ISSUE TITLE
To save a image crashes corebird

### ISSUE THREAD

**Issue by marciosr** [baedert/corebird#480]
In corebird git (25/12), when I try to save a media (image) to a folder o my computer, corebird crashes.
It happens using the right click and the context menu option "Save Original".
If I click on the image opening the new widget image, give a right click and click on the "Save Image" option nothing happens.

Arch Linux with:
gtk3 3.18.6
glib 2.46.2
vala 0.30

gdb backtrace:

#0  0x00007ffff4c015f8 in raise () from /usr/lib/libc.so.6
Backtrace stopped: Cannot access memory at address 0x7fffffffd628

Terminal output:

ERROR:widgets/MediaButton.c:755:media_button_save_original_activated: assertion failed: (false)

Program received signal SIGABRT, Aborted.
0x00007ffff4c015f8 in raise () from /usr/lib/libc.so.6

**Comment by baedert** [comment]
That functionality actually got removed in the `new-compose-imag` branch I'm working on currently because cairo doesn't have a way to save non-png images. The current code crashes because of an `assert(false);`.

**Comment by baedert** [comment]
Doesn't crash anymore because the menu item doesn't exist anymore. If you want to download images, open them in your browser and save them from there.
