### ISSUE TITLE
Missing images on some icons

### ISSUE THREAD

**Issue by Rombusevil** [baedert/corebird#483]
icons that shows the missing image are:
Mentions
Direct Messages
Filters
Compose tweet
retwit icon

**Comment by baedert** [comment]
What gtk+ version?

**Comment by Rombusevil** [comment]
3.18.6-1

**Comment by baedert** [comment]
What package provides `/usr/share/icons/hicolor/index.theme` on debian? What version of that do you have installed? Does that file deifne a `symbolic/` directory?

**Comment by baedert** [comment]
So, looks like you need hicolor version >= 0.15 (from march 2015)...

**Comment by Rombusevil** [comment]
I have "hicolor-icon-theme" installed, but I don't know hot to tell what version it is. How can I upgrade to 0.15?

**Comment by baedert** [comment]
From https://packages.debian.org/testing/hicolor-icon-theme it doesn't look like there's a 0.15 release available. You'd have to ask the package's maintainer or whoever does the releases for a new release it seems (the bug tracker is weird...). It's been 9 months since the hicolor upstream release, no idea why it's not available in debian.

**Comment by cpw** [comment]
I don't believe that hicolor is the problem? You have custom icons in data/symbolic. These icons were working prior to commit https://github.com/baedert/corebird/commit/5fa96363733a1143869288ca66feedb3730ea891. I just tested and it seems you're no longer installing these icons..

**Comment by cpw** [comment]
I've filed a bug with debian to try and get them to pull in the newer hicolor version. I don't understand why this is required, but hopefully it can be fixed.

**Comment by baedert** [comment]
Is this fixed? Is there a publicly accessible bug report one could follow?

**Comment by baedert** [comment]
Ok.

**Comment by cpw** [comment]
Update: Bug report is here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810986 and it's seen no action since filing. I doubt this is going to be fixed, the maintainer is one who I think is very inactive in Debian, sadly. I can't find an upload from him since 2013 or so.

**Comment by baedert** [comment]
Does it work *now*?
