### ISSUE TITLE
Latest git-master crashes when opening settings

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#489]
Todays git-master crashes when opening the settings. When running corebird from terminal the following error message is raised:
> (corebird:29326): GLib-GIO-ERROR **: Settings schema 'org.baedert.corebird' does not contain a key named 'hide-nsfw-content'
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

**Comment by baedert** [comment]
But that's just the error you get everytime I introduce a new setting. you need to install the settings schema first (make install).

**Comment by HeikoAdams** [comment]
I did a make install and I also called glib-compile-schemas after installation in my package

**Comment by HeikoAdams** [comment]
Correct me if I'm wrong but 85730807a009220ce5fffbc6ea8a94a6be07b587 only adds the setting to the settings but the schema is not modified

**Comment by baedert** [comment]
urgh, the .xml vs. .xml.in confusion again, sorry. Should work now.

**Comment by HeikoAdams** [comment]
Yes, not it works. Thanks!
