### ISSUE TITLE
Scale down images when replying or quoting a tweet

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#490]
Otherwise it could happen that the text-input is outside of the desktops visible area and you have to write blind.

**Comment by IBBoard** [comment]
Is this the same as bug #458?

(BTW, if you drag the corner of the dialog, which isn't always the actual corner, then you can resize the window so you don't post blind!)

**Comment by HeikoAdams** [comment]
Yes, it looks like.

Haven't tried but not sure that works on GNOME 3

**Comment by IBBoard** [comment]
What, resizing the corner? I'm on Gnome 3, so I'm fairly sure it works ;) I guess purist Gnome dialogs don't resize, but this is more "resizable child window" than proper "Gnome dialog that is stuck to the parent".
