### ISSUE TITLE
Empty timeline after resuming from standby

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#492]
When resuming my notebook from standby (opening the lid) the timeline is empty corebird only says "loading"

**Comment by baedert** [comment]
I just ran into that without resuming from standby, just scrolling down, leaving the latoptop running for a few days, then scrolling up was enough.

**Comment by baedert** [comment]
I have used it quiet a few times with resume from standby now and couldn't reproduce that behavior, please reopen if it happens again.
