### ISSUE TITLE
Group private messages

### ISSUE THREAD

**Issue by moebiuseye** [baedert/corebird#498]
Twitter can have group private messages,

I think supporting this feature would be great.

CoreBird is a great piece of software! Thanks to all the contributors. :)

**Comment by baedert** [comment]
I'm pretty sure Twitter does not offer an API to do that, so we can't implement it in any case.

**Comment by kanishkablack** [comment]
https://twittercommunity.com/t/private-group-messaging-api-available/31832

**Comment by baedert** [comment]
Yep, can't support that.
