### ISSUE TITLE
Can't open quoted tweet - again

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#499]
When trying to open the tweet quoted by https://twitter.com/IngeHannemann/status/689502594037846016 I always get back to the quoting tweet.

**Comment by baedert** [comment]
Works here.

**Comment by HeikoAdams** [comment]
Looks like this is a little heisenbug - it happens only from time to time

**Comment by baedert** [comment]
When this happens, do you see output similar to "connection terminated unexpectedly" in the journal/on the terminal?

**Comment by HeikoAdams** [comment]
The only error I found the journal wa
> (corebird:12185): Gtk-CRITICAL **: gtk_stack_set_visible_child: assertion 'GTK_IS_STACK (stack)' failed

**Comment by baedert** [comment]
Let's close this then.
