### ISSUE TITLE
Layout broken on latest git master

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#502]
On latest git master the layout is broken due to the following error raised if corebird is launched from terminal:
> ** (corebird:16582): WARNING **: Utils.vala:356: Error while loading ui/style.css: style.css:149:12'min-height' is not a valid property name

Screenshot:
![bildschirmfoto von 2016-01-23 12-23-15](https://cloud.githubusercontent.com/assets/1418818/12529923/1a32bb6e-c1cc-11e5-8496-ca00139abf19.png)

**Comment by baedert** [comment]
m(
Didn't push the needed commit from home...
