### ISSUE TITLE
Size of Picture Review Box

### ISSUE THREAD

**Issue by HybridGlucose** [baedert/corebird#511]
I don't know how to call that area but I think you understand what I mean.  
I think that box can scale a little big like web.   
Sorry for my poor English.

**Comment by baedert** [comment]
I guess you're talking about 1.1. It's completely different in master.

**Comment by HybridGlucose** [comment]
> I guess you're talking about 1.1. It's completely different in master.
Yes XD
I use Arch AUR corebird 1.1-1
I will await the new version.
Thank you.
