### ISSUE TITLE
Authorizing issue...

### ISSUE THREAD

**Issue by bluesfreak72** [baedert/corebird#513]
I'm running Ubuntu 15.10 and just installed CoreBird.  I'm trying to obtain the pin to authenticate, but when I click the button, a blank page comes up in Google Chrome.  Am I doing something wrong or is there a work-around?

**Comment by baedert** [comment]
Is there any output when you run it from the console? Does "blank page" also mean that there's no url in the address bar?

**Comment by bluesfreak72** [comment]
Here's the output from the console:

$ corebird

** (corebird:19766): WARNING **: MainWindow.vala:388: Couldn't load window
geometry for screen_name `screen_name'
Created new window in existing browser session.



When the new window comes up, the url in the browser is
http://home.brandthunder.com/ohiostate/, but that's because I've installed
that theme in Google Chrome.  If I didn't have that theme, it would be
blank.

On Fri, Feb 12, 2016 at 1:25 PM, baedert <notifications@github.com> wrote:

> Is there any output when you run it from the console? Does "blank page"
> also mean that there's no url in the address bar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baedert/corebird/issues/513#issuecomment-183440242>.
>



-- 
<><  Scott Vargovich  <><
------------------------------------------
OpenPGP Key ID: 29C36884
==================
Ham Radio Call Sign: KE8CQC
------------------------------------------

**Comment by baedert** [comment]
That output is unrelated, but 1.1 doesn't print more information in case opening the browser fails unfortunately. I can't really help you any more at this point, this should just work with any browser; can you try another one (like firefox)?

**Comment by bluesfreak72** [comment]
That did it.

On Sat, Feb 13, 2016 at 8:14 AM, baedert <notifications@github.com> wrote:

> That output is unrelated, but 1.1 doesn't print more information in case
> opening the browser fails unfortunately. I can't really help you any more
> at this point, this should just work with any browser; can you try another
> one (like firefox)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baedert/corebird/issues/513#issuecomment-183662674>.
>



-- 
<><  Scott Vargovich  <><
------------------------------------------
OpenPGP Key ID: 29C36884
==================
Ham Radio Call Sign: KE8CQC
------------------------------------------
