### ISSUE TITLE
Some tweets trigger horizontal scrolling

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#514]
Sometimes I'll browse my timeline and suddenly the images become really wide. From a bit of investigating, it appears that "@FakeUnicode" is causing it with some of their odd tweets. I think (but I'm not certain) that it is long hashtags that cause it.

As an example, see https://twitter.com/FakeUnicode/status/701996229257883648. Twitter lets the crazy hashtag of Unicode overflow. Corebird makes the whole content of all tweets scroll horizontally.

I'm not sure what the best option is here and whether there is a decent fix. Scrolling just a single tweet would limit the impact, but may not be intuitive. Hiding overflow isn't clear and obvious. Putting ellipses in the middle of the display text might work, but it may also break up long-but-sensible hashtags and we'd need to find a sensible character count at which to start putting ellipses in.

**Comment by baedert** [comment]
You can't really fix that (without modifying the tweet text). That behavior is known and easily reproducible by just using 140 '?' characters and hoping someone has a rather narrow window. Pango just never breaks that and now you have 140 characters in a single line (that example isn't the best since '?' isn't the widest character ever, but you get the idea).

**Comment by IBBoard** [comment]
I did think it'd just be long content, but there's "it's a minor glitch" and there's "man, it screws everything". If I fullscreen Corebird on a 1080p monitor then I can see about 3/5ths of that tweet (based on the scroll bar). That means that all images from all other tweets are then pushed that far across as well. It isn't a narrow window issue, it is an any window issue.

Is it possible to do an equivalent of the CSS "overflow: hidden" to prevent horizontal scrolling and image movement in the main timeline but show the full width when viewing a single tweet?

**Comment by baedert** [comment]
> It isn't a narrow window issue, it is an any window issue.

The point wasn't the narrow window, it was the fact that this problem has existed since forever and that there's no really easy way to fix it (even sanitizing the input, how would one even fix 140 questionmarks?)

> Is it possible to do an equivalent of the CSS "overflow: hidden" to prevent horizontal scrolling and image movement in the main timeline but show the full width when viewing a single tweet?

Not really. Just, uhm, don't follow "FakeUnicode" accounts that deliberately try to break the layout?

**Comment by ValdikSS** [comment]
The same could be seen in an input field. AFAIK with previous Pango versions it worked fine on Fedora 23.

**Comment by IBBoard** [comment]
I've found a new problem tweet today:

https://twitter.com/FakeUnicode/status/912996696216395778

Strangely, my custom build on openSUSE Tumbleweed still exhibited the "stretches the window REALLY wide" behaviour, but then I went to test it on openSUSE Leap 42.3 (my home machine) before reporting and the column goes wide, but Corebird just shows a horizontal scroll bar. They're both built from the same source and patches on the Open Build Service.

Could that a difference between GTK 3.20.10 (Leap, scrolls) and GTK 3.22.21 (Tumbleweed, doesn't scroll, extends app)? Or is it something else?

**Comment by Vistaus** [comment]
I don't know. All I can say is that here on Solus with GTK 3.22 all tweets from @ FakeUnicode trigger horizontal scrolling for me.

**Comment by IBBoard** [comment]
Odd. I only get minimal scrolling at my standard width (maybe 300px, at a guess) until I scroll back at least five pages!

**Comment by ValdikSS** [comment]
This is what just happened to me.
![spectacle j13525](https://user-images.githubusercontent.com/3054729/30933255-bb3bf586-a3d2-11e7-89a8-6a6076b5ff70.png)

**Comment by IBBoard** [comment]
Oh, I got something a bit like that the first time it happened, but couldn't recreate it. I put it down to Gnome glitching out about suddenly having to make a window that wide! Mine was less readable, though. Thinner slices of content and more corruption, as if it had a 1D list of pixels that were for a 1000px wide display but were being written to an 800px wide area, so the "extra" pixels were written to the next line, and the second 1000px of content started 200px in and wrapped 400px on to the next line, and so on (if that makes sense).

**Comment by Vistaus** [comment]
@ValdikSS I can partly reproduce that here on Solus. Corebird still looks fine when clicking on that tweet except that the window gets really wide horizontally. But not garbled like in your screenshot/video.

**Comment by baedert** [comment]
I'm going to assume that's a rendering bug in the compositor when the window is too wide until proven wrong.

**Comment by IBBoard** [comment]
For reference: It's not always Fake Unicode that's at fault, and now that we're at 280 characters then it gets worse! (Because the tweet can be wider)

https://twitter.com/RoySocChem/status/928200456760852480

**Comment by Vistaus** [comment]
@IBBoard RoySocChem's tweet doesn't trigger horizontal scrolling for me.

**Comment by IBBoard** [comment]
I did wonder after I posted it whether I needed to add more info.

I'm using libpango v1.40.13. AFAIK they changed the wrapping behaviour recently and [it broke Nautilus](https://bugzilla.gnome.org/show_bug.cgi?id=789625). Maybe it'll be fixed by that bug fix and Corebird won't need to do anything.

**Comment by Vistaus** [comment]
@IBBoard I'm also using libpango 1.40.13, but as I said: I can't reproduce it.

**Comment by IBBoard** [comment]
Upgraded to libpango 1.40.14 and I can confirm that it wraps properly again - the Royal Society of Chemists tweet doesn't stretch the window and wraps in a square block.

**Comment by IBBoard** [comment]
I've *finally* managed to [cludge together a patch](https://build.opensuse.org/package/view_file/home:IBBoard:desktop/corebird/corebird-scroll-wide-tweets.patch?expand=1) that works well enough for me, and I've applied it to my custom build.

Basically, I wrap the tweet text in a scroll window, watch the text box "size-allocate" signals and set the height of the scroll box based on that. It means you get horizontal scroll bars for awkward tweets that don't wrap properly (mainly FakeUnicode these days, but previous Pango issues have triggered it on other tweets) and you never get vertical scrolling.

The only thing that I've not got working is that if you make your window narrow and then make it wide then the text label doesn't shrink back down to its minimum height. But, since I don't resize my window that often, I'm not too bothered.

Probably not a fix for the official build, but it Works For Me™. (See the middle two tweets, which are RIDICULOUSLY wide, because Pango follows Unicode rules and doesn't break on "format" characters, which Fake Unicode made a long string of).

![screenshot from 2017-12-09 12-01-43](https://user-images.githubusercontent.com/388582/33795417-c04c7e6c-dcd8-11e7-9a33-821e2f780661.png)

**Comment by Vistaus** [comment]
[**@IBBoard**](https://github.com/IBBoard) commented on [Dec 2, 2017, 12:05 PM GMT+1](https://github.com/baedert/corebird/issues/514#issuecomment-348684794 "2017-12-02T11:05:16Z - Replied by Github Reply Comments"):
> Upgraded to libpango 1.40.14 and I can confirm that it wraps properly again - the Royal Society of Chemists tweet doesn't stretch the window and wraps in a square block.

If it wraps properly again, this issue is resolved then?

**Comment by IBBoard** [comment]
Yes and no. It's 99.99% fixed, but there are still some corner cases that don't play nicely (see my last screenshot with my scrolling kludge).

I'd like to fix the kludge a bit. While it works, it causes everything to resize slightly, so if you're not auto-scrolling then the new tweets slowly cause the old tweets to drift down the display anyway (because they get rendered as normal, then the resize kicks in, then they get slightly bigger, and so everything moves).

I guess it depends on how much people care about the really odd edge cases as to whether this is closed or not.

**Comment by Vistaus** [comment]
Well, I for one, still can't reproduce it. So I don't really care if it gets fixed or not. It's not up to me, of course, but personally, I would close this issue and do a pull request once the patch fixes the last 0.1 percent.

**Comment by IBBoard** [comment]
It's only tweets like https://twitter.com/FakeUnicode/status/936926329001218048 now.

I'll close it on the assumption that most people are unlikely to encounter tweets where the Pango interpretation of the rules doesn't do a reasonable character break.

**Comment by IBBoard** [comment]
In case anyone wants it, I've now got an updated patch that does things "properly", which means that it a) appears to handle new tweets without everything slowly shifting down and b) scrolls the "tweet info" page (double-click a tweet)

ibboard/corebird@349f813 

It now basically looks like my last screenshot, but for all tweets (which hopefully covers DMs as well, but I haven't tested)
