### ISSUE TITLE
Provide corebird Linux app using AppImage 

### ISSUE THREAD

**Issue by kskarthik** [baedert/corebird#518]
Appimage helps packing apps which can run on all major Linux distributions based on concept of **one app = one file**

If corebird can be packed along with all its dependencies inside an appimage, users can simply download give permission & run the file. Appimage also supports Delta updates. 

Popular apps like subsurface, scribus, krita are also adopting this method to distribute their apps. It's easy to pack apps using AppImage. No extra knowledge required. 

Project repo: https://github.com/probonopd/AppImagekit

The developer @probonopd is happy to help you packing your app :)

**Comment by probonopd** [comment]
Can this be built on CentOS 6 and if so, how? Building on CentOS 6 makes the binaries runnable on most desktop distributions.

**Comment by baedert** [comment]
From a quick look over http://mirror.centos.org/centos/6/os/x86_64/Packages/ I'd say no. I don't see any gtk3 package in there but I think currently the newest dependency corebird has is gstreamer-plugins-bad for gtksink (so gstreamer 1.6 is needed, with enabled gtksink).

**Comment by probonopd** [comment]
Here is an experimental recipe that generates an AppImage from the trusty ppa:
https://github.com/probonopd/AppImages/blob/master/recipes/corebird/Recipe

Some fine-tuning might be necessary, but at least on my Ubuntu 16.04 system it seems to be running well. Would be great if you could use this as a basis for official, upstream-provided AppImages.

**Comment by kskarthik** [comment]
I will test on xubuntu

**Comment by baedert** [comment]
Yeah, so this won't happen.
