### ISSUE TITLE
Lists do not auto-update

### ISSUE THREAD

**Issue by nfshr** [baedert/corebird#523]
Unfortunately the Twitter-Lists do not auto-update on Corebird. It would be awesome if they could.

cheers
nfshr

edit: also, it would be great if one could hide the big grey block appearing at the top of the Lists column.

**Comment by baedert** [comment]
I know. List updates don't appear on the streaming connection.

**Comment by nfshr** [comment]
Hmm. So its on Twitter's end? Tweetdeck does it though..

**Comment by baedert** [comment]
Does it update them in real-time or does it poll?

**Comment by nfshr** [comment]
As far as i can tell its updating in real-time. Using it right now..

**Comment by baedert** [comment]
k, can't do that.

**Comment by nfshr** [comment]
k, thx
