### ISSUE TITLE
Make text always dark even when unfocused

### ISSUE THREAD

**Issue by axfelix** [baedert/corebird#524]
This might be a theming-only issue, but I'm not sure if you can fix it on your end too. See https://github.com/bsundman/Yosembiance/issues/20.

Since Corebird will usually be in the corner of a screen unfocused, it's easier on the eyes if the text is always as dark as possible.

If this isn't fixable on your end, would you happen to know which parameter I should edit in an existing theme to change this?

**Comment by baedert** [comment]
What you mean is the backdrop styling. That's a theme thig and there's no way for users or apps to disable it, so I can't disable it.

**Comment by axfelix** [comment]
OK, closing.
