### ISSUE TITLE
lots of warnings from libsoup-2.4.vapi during compilation

### ISSUE THREAD

**Issue by FadeMind** [baedert/corebird#526]
Full log: https://pastebin.com/raw/kDgBTT5v
ArchLinux x86_64
libsoup 2.54.0.1-1

@baedert 

During compilation I have lots line with warnings:

     
    XMLLINT=/usr/bin/xmllint /usr/bin/glib-compile-resources --target corebird-resources.c --generate --sourcedir=.. --c-name corebird ../corebird.gresource.xml
    libsoup-2.4.vapi:1134.3-1134.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1248.3-1248.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1898.3-1898.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1901.3-1901.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1904.3-1904.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1907.3-1907.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1910.3-1910.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1913.3-1913.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1916.3-1916.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1919.3-1919.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1922.3-1922.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1925.3-1925.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1958.3-1958.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1961.3-1961.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1964.3-1964.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2034.3-2034.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2038.3-2038.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2041.3-2041.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2044.3-2044.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2047.3-2047.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2050.3-2050.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2053.3-2053.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2056.3-2056.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2059.3-2059.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2062.3-2062.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2065.3-2065.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2069.3-2069.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:267.4-267.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:662.4-662.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:664.4-664.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:672.4-672.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:674.4-674.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gstreamer-1.0.vapi:4.2-4.13: warning: [Experimental] is deprecated. Use [Version (experimental = true, experimental_until = "")]
    Compilation succeeded - 33 warning(s)
    touch libcorebird_la_vala.stamp
    make  all-am
    make[3]: Entering directory '/tmp/makepkg/corebird-git/src/corebird/src'
    (...)
     CCLD     libcorebird.la
    ar: `u' modifier ignored since `D' is the default (see `U')
    libsoup-2.4.vapi:1134.3-1134.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1248.3-1248.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1898.3-1898.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1901.3-1901.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1904.3-1904.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1907.3-1907.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1910.3-1910.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1913.3-1913.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1916.3-1916.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1919.3-1919.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1922.3-1922.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1925.3-1925.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1958.3-1958.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1961.3-1961.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:1964.3-1964.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2034.3-2034.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2038.3-2038.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2041.3-2041.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2044.3-2044.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2047.3-2047.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2050.3-2050.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2053.3-2053.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2056.3-2056.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2059.3-2059.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2062.3-2062.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2065.3-2065.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    libsoup-2.4.vapi:2069.3-2069.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:267.4-267.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:662.4-662.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:664.4-664.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:672.4-672.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gee-0.8.vapi:674.4-674.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    gstreamer-1.0.vapi:4.2-4.13: warning: [Experimental] is deprecated. Use [Version (experimental = true, experimental_until = "")]
    Compilation succeeded - 33 warning(s)
    touch corebird_vala.stamp
      CC       main.o
      CCLD     corebird

Regards

Tomasz

**Comment by baedert** [comment]
Yup, you can safely ignore those; the libsoup vapi is shipped with vala, the one from gee with libgee and the one warning coming from the gstreamer-1.0.vapi could be fixed but not wthout depending on a newer valac afaik.

**Comment by FadeMind** [comment]
@baedert Thanks for quick reply. So, I closing this issue if this is not major.
