### ISSUE TITLE
Add a "reload" button/option

### ISSUE THREAD

**Issue by pbielefeldt** [baedert/corebird#528]
Hi & thanks for awesome Corebird! 
There's one thing Corebird imho could do better: After waking up from stand-by or after a network loss, I often get an empty timeline; Switching to an other account and back results in the timeline being re-loaded/refreshed, however, that's a bit tedious. – I'd love to see a "reload" button, maybe only if fetching the timeline doesn't work – or just s.th. to press all the time in order to trigger a refresh…

![Screenshot](https://cloud.githubusercontent.com/assets/13000622/14405277/6ca57548-fe8b-11e5-9f22-28ee161539f2.png)
_This screenshot shows the situation after waking up from stand-by._

 Cheers! 

--
Corebird 1.0.1
on openSUSE 42.1, Gnome Shell 3.16.2

**Comment by baedert** [comment]
Newer versions should already show a "retry" button in that case.
