### ISSUE TITLE
Build fails with "undefined reference to 'gtk_widget_set_focus_on_click'"

### ISSUE THREAD

**Issue by innir** [baedert/corebird#531]
Hi,

building corebird 1.2 on Debian unstable fails with this message:

`corebird-1.2/src/widgets/BadgeRadioButton.c:106: undefined reference to 'gtk_widget_set_focus_on_click'`

The whole build log is here: 

https://tests.reproducible-builds.org/rbuild/unstable/amd64/corebird_1.2-2.rbuild.log

Best,
Philip

**Comment by baedert** [comment]
That sounds like you have a newer vala version and an older gtk version (pre 3.20). `gtk_widget_set_focus_on_click` was introduced in gtk+ 3.20 but collided with the old `gtk_button_set_focus_on_click` from the vala perspective.

**Comment by innir** [comment]
So true:

libgtk-3-0 3.18.9-1
valac  0.32.0-1

So I just have to wait until libgtk-3-0 3.20 is uploaded.

Thanks for the quick help
