### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [baedert/corebird#532]
Could it be possible to make corebird available on Docker? It could an "easy" way to make it available on Windows

**Comment by baedert** [comment]
> Could it be possible to make corebird available on Docker?

I have no idea. Neither about docker nor whether that would help making it work easily on Windows.

**Comment by ZatsuneNoMokou** [comment]
Well, on Windows, docker use virtualization to have a linux base, so might not be much to do I guess. After never did it, I was just asking

**Comment by baedert** [comment]
> After never did it, I was just asking

That's just fine, I was just saying that I've never worked with Docker and it looks like you know more about it than I do ;) I don't have a Windows license so I can't even test it, which is why I don't port it to Windows.

**Comment by ZatsuneNoMokou** [comment]
I see, your twitter client is really good, and there's not much on Windows :)

**Comment by aregaz** [comment]
I'm not sure that Docker allows to run Linux app on any Windows. AFAIK you need Docker Engine to be installed on Windows (unless you are on the new Windows Server which is not a common case). So Docker won't help regular user to install Corebird on Windows.

**Comment by ZatsuneNoMokou** [comment]
Docker, on Windows, install a special virtual machine on virtualbox
