### ISSUE TITLE
Broken "add image" dialog window on Ubuntu 15.10

### ISSUE THREAD

**Issue by orschiro** [baedert/corebird#535]
Dear @baedert,

Just a minor thing that I have discovered while adding an image on Ubuntu 15.10 and Corebird 1.2. 

As you can see in the below screenshot, if I resize the window to the bottom, the content no longer properly wraps. This creates this empty grey area as shown.

Is this a bug of the GTK toolkit?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14525036/e4e6e9fc-023b-11e6-9bb4-b1135cc0bd36.png)

**Comment by baedert** [comment]
> Is this a bug of the GTK toolkit?

This is not a standard `GtkFileChooserDialog`, so shouldn't be a bug in gtk+. But it's not like I haven't been surprised by ubuntu's gtk package before.

I can't reproduce it here locally at least :/

Apart from the grey space at the bottom, why is the sidebar on the left cut off at the top? Is that just scrolled up?

**Comment by orschiro** [comment]
Hi @baedert,

  

I hope this screencast video makes it more clear:

  

https://share.riseup.net/#YYch9CzZcmpgI6gR_MjZ0A  

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 14 2016, at 1:15 pm, baedert &lt;notifications@github.com&gt; wrote:  

> > Is this a bug of the GTK toolkit?

>

> This is not a standard GtkFileChooserDialog, so shouldn't be a bug in gtk+.
But it's not like I haven't been surprised by ubuntu's gtk package before.

>

> I can't reproduce it here locally at least :/

>

> Apart from the grey space at the bottom, why is the sidebar on the left cut
off at the top? Is that just scrolled up?

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/baedert
/corebird/issues/535#issuecomment-209885876)![](https://github.com/notificatio
ns/beacon/AAKbw9hDTacjFcrcL2A7Izc7BtiMWKeqks5p3iHggaJpZM4IHOri.gif)

**Comment by baedert** [comment]
Okay, could reproduce it in a ubuntu vm, but setting vexpand=true on the filechooserwidget solved it. I'll cherry-pick the patch into the cb-1.2 branch, but not sure when a 1.2.1 will happen.

**Comment by orschiro** [comment]
Great you could resolve it!

  

It's not an urgent issue though. :-)

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 14 2016, at 3:10 pm, baedert &lt;notifications@github.com&gt; wrote:  

> Okay, could reproduce it in a ubuntu vm, but setting vexpand=true on the
filechooserwidget solved it. I'll cherry-pick the patch into the cb-1.2
branch, but not sure when a 1.2.1 will happen.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/baedert
/corebird/issues/535#issuecomment-209935032)![](https://github.com/notificatio
ns/beacon/AAKbw73-SgXgAfMJgnS2KlEU8Bw-X779ks5p3jyEgaJpZM4IHOri.gif)
