### ISSUE TITLE
Text of profile page's button misleads to that blocking it

### ISSUE THREAD

**Issue by tSU-RooT** [baedert/corebird#536]
I think the text of  block button of user profile page is hard to understand what means.
Normally, client user haven't block other user yet, but its text shows "Blocked"
that misleads client user.
Once, User blocks other users, check mark  appears at right of button and user will understand it soon. 
However, I think this specification is unkind.

**Not blocking**
![b_now01](https://cloud.githubusercontent.com/assets/1822861/14763004/d8891646-09c3-11e6-9fc1-ef120801755b.png)

**Blocking**
![b_now02](https://cloud.githubusercontent.com/assets/1822861/14763015/5725b7de-09c4-11e6-9053-ac6ddcd25e73.png)

**Comment by baedert** [comment]
I think this is a pretty bad design decision in your gtk+ theme, knowing what kind of action you perform (normal/action/radio) is pretty important in any case.

**Comment by tSU-RooT** [comment]
oh, sorry...
This problem is caused by my gtk+ theme. I will consider to change it.
Thank you for your response quickly.
