### ISSUE TITLE
Compilation fails when "gtk_widget_set_focus_on_click"

### ISSUE THREAD

**Issue by loopset** [baedert/corebird#537]
HI! Thanks for your great app. I'm trying to compile Corebird on Kaos GNU/Linux, but every time it gives me the same error (on the pastebin). The dependencies are the correct, only stand out that we are using gtk 3.18.9, vala 0.32 and glib 2.46 (other dependencies are correct, I also use libgee and librsvg). The full output of makepkg is here: [https://goo.gl/80BfvO](url)
Note that in Kaos we use libsoup and rest with this option on configure:--without-gnome
Thanks

**Comment by baedert** [comment]
The links is invalid, but I'm guessing it's the same issue as #531

**Comment by loopset** [comment]
Sorry,the URL is this: https://paste.kde.org/pfnmgvzh9/1te6sy
And yes, I think that it s the same problem! I will wait until 3.20 be in repos!
Thanks another time
