### ISSUE TITLE
Limit for caching images

### ISSUE THREAD

**Issue by Aisyk** [baedert/corebird#538]
Hi,

My installation of corebird has a 3.0 Go in its cache directory. Can i limit the space in this directory ?

Thanks

**Comment by baedert** [comment]
No you can't but newer versions of corebird do not cache images anymore.

**Comment by Aisyk** [comment]
Ok, I'm using 1.0 version, 1.1 version will not cache images ?

Thanks.

**Comment by baedert** [comment]
The release notes only mention it for 1.2 so I think 1.1 would still do it.

**Comment by Aisyk** [comment]
Oh, ok, i've see that i have 14.04 LTS of Ubuntu, so i'm limited to 1.0 version of Corebird due to gnome 3 specifications of the application...

**Comment by baedert** [comment]
Okay then. You can just close corebird, delete the cache folder and restart it again of course.
