### ISSUE TITLE
Garbled video on Ubuntu 16.04

### ISSUE THREAD

**Issue by jc00ke** [baedert/corebird#540]
I just upgraded 15.10 :arrow_right: 16.04 this afternoon and now videos are garbled. The audio is correct though.

![gifrecord_2016-04-27_160219](https://cloud.githubusercontent.com/assets/18191/14870815/c937a074-0c91-11e6-977d-3e13409be7b1.gif)

Running 7e1f1ac
Tweet https://twitter.com/BatLabels/status/725457590021439488

**Comment by baedert** [comment]
Can you....


1) Run `GST_DEBUG=6 corebird` (maybe do `GST_DEBUG=6 GST_DEBUG_NO_COLOR=1 corebird > log.txt 2>&1` for a text file), then post the ouput? The output file will be pretty large though.

2) Download one of the videos, e.g. [this one](https://mtc.cdn.vine.co/r/videos/DD044D51F21337976150236053504_5212060533e.15.0.13324819453611101519.mp4?versionId=viRJHVnTvt56q4sPvkEc6DDnbdquIiB8) and run `gst-play-1.0 --videosink=gtksink file.mp4`? Does that work or does it show the same garbled output?

**Comment by jc00ke** [comment]
1. [log file](https://docs.google.com/a/jc00ke.com/uc?id=0B6qwdumTHyNtT2x5aFlNWVhhZ0k&export=download)
1. That shows the garbled output.

**Comment by baedert** [comment]
There's a downstream bug report in gstreamer now: https://bugzilla.gnome.org/show_bug.cgi?id=765998

Can you try to work around the issue by uninstalling `gstreamer1.0-vaapi`?

**Comment by jc00ke** [comment]
Uninstalling `gstreamer1.0-vaapi` worked. I'll close for now, thanks for the workaround!
