### ISSUE TITLE
Tweet text highlighted

### ISSUE THREAD

**Issue by armaccloud** [baedert/corebird#541]
Hi,
I am using Corebird 1.1 on Ubuntu 16.04.
When opening a tweet, it often opens with the text highlighted.

![image](https://cloud.githubusercontent.com/assets/9272078/14915933/bd569356-0e16-11e6-983b-c58821645173.png)

It usually happens when opening a tweet, but not always.

**Comment by baedert** [comment]
I can't reproduce this, what's the used gtk+ version?
