### ISSUE TITLE
Search containing 2 characters doesn't complete

### ISSUE THREAD

**Issue by armaccloud** [baedert/corebird#542]
Hi,
I'm using Corebird 1.1 on Ubuntu 16.04.
When I perform a search that contains a two-character word (e.g. RT America), it never completes (loading...). Then I can only stop the search by closing Corebird and reopening again.

**Comment by baedert** [comment]
The problem isn't that it's 2 characters but that those 2 characters are "RT". The search in corebird automatically appends a "-rt" at the end of each search query so you are asking for retweets without retweets, which won't work, newer versions will show a (more or less helpful...) error message: http://i.imgur.com/bOwkXYs.png

**Comment by armaccloud** [comment]
Ah, in this case I am searching for Russia Today America. Which only goes by the name RT America on Twitter. I can add them through the web interface though.
Thanks for explaining.
