### ISSUE TITLE
Visual indicator of selected tweet

### ISSUE THREAD

**Issue by armaccloud** [baedert/corebird#543]
Hi,
I am using Corebird 1.1 on Ubuntu 16.04.
With they keyboard arrows up & down it is possible to navigate the home-section by selecting tweets and opening them. However there is no visual indicator what tweet is selected. The only way to find out, is to hit the enter-button which opens the tweet.
It would be a nice enhancement to show a subtle indicator of the selected tweet.

**Comment by baedert** [comment]
There's a focus outline if your theme doesn't screw up:
http://i.imgur.com/9WuNlgU.png

**Comment by armaccloud** [comment]
The outline is not visible in my overview. In this picture, the second tweet is selected.
![image](https://cloud.githubusercontent.com/assets/9272078/14934964/b8e0dbe6-0ec1-11e6-9ae9-0666840977d8.png)
Using the default Ubuntu theme.

**Comment by baedert** [comment]
Yeah, that's the "if your theme doesn't screw up" part. I don't have it on ubuntu either but I don't know how canonical handles focus outlines generally.
