### ISSUE TITLE
Unread mentions notification doesn't go away

### ISSUE THREAD

**Issue by jc00ke** [baedert/corebird#547]
![2016-05-12t17 25 13 438z](https://cloud.githubusercontent.com/assets/18191/15223995/fca43ca6-182b-11e6-99d5-de92463f3d9a.gif)

This is me clicking back and forth on 9912fcf

I expect the bubbles to disappear but they are persisting.

**Comment by baedert** [comment]
Umm, also why are the icons in the topbar dark?

**Comment by jc00ke** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9422789-118866928_5-s1-v1.png?palette=1&width=246)

Maybe it's the [Paper theme?](https://snwh.org/paper/theme)

**Comment by baedert** [comment]
It looks like this for me: http://i.imgur.com/mwQpc0f.png

Especially after the commit you mentioned, the color of those icons should be fixed.

**Comment by jc00ke** [comment]
I just pulled fresh and built from 360a31d and it looks like this:

![2016-05-12t19 00 19 912z](https://cloud.githubusercontent.com/assets/18191/15226825/4be2832e-1839-11e6-8350-1630e864ec13.gif)

**Comment by baedert** [comment]
In light of #548, are you also using gtk+ 3,18?

**Comment by jc00ke** [comment]
Yes, that's the default on Ubuntu 16.04.

**Comment by baedert** [comment]
Is this still happening or did the above commit fix it? (I can test again later today)

**Comment by jc00ke** [comment]
It only cleared the bubble after I scrolled down a bit.

Steps:
1. mentioned myself from gf's acct
1. saw unread bubble
1. switched to mentions, bubble stayed
1. switched to timeline, bubble stayed
1. switched back to mentions, bubble stayed
1. scrolled down a bit, bubble vanished

**Comment by baedert** [comment]
You have auto-scroll-on-new-tweets disabled, right?

**Comment by jc00ke** [comment]
Correct
