### ISSUE TITLE
topbar items wrong color

### ISSUE THREAD

**Issue by corebots** [baedert/corebird#548]
i've just updated to 1.2.1 but the topbar looks weird :/
![screenshot from 2016-05-13 01-07-17](https://cloud.githubusercontent.com/assets/12252430/15233281/b6913a76-18a7-11e6-84a7-392db7c941ed.png)

/dwnloaded from git, on updated F23

**Comment by baedert** [comment]
That's gtk 3.20 I presume, what gtk theme?

**Comment by corebots** [comment]
actually this is gtk3-3.18.9-1.fc23.x86_64, default gnome theme. I've tried in F24beta with gtk 3.20 and it's fine so must be 3.18 related.

**Comment by baedert** [comment]
Do you get any output about css errors/warnnigs when running from a terminal?

**Comment by corebots** [comment]
thank you!
