### ISSUE TITLE
Active/inactive window toolbar styles are inverted

### ISSUE THREAD

**Issue by robmv** [baedert/corebird#549]
Using 1.2.1 (on Fedora) the styles for the toolbar when the window is active or inactive are inverted. When the window is inactive, I can see the hearth perfectly shaped with a white fill over dark background. When the window is active, toolbar buttons switch to outlines, difficult to distinguish.

By the way, can this style change be removed instead of fix the switched states. I really don't like that a small window that can run side by side with another application (we have widescreen monitors now) can't show their icons enabled and identifiable.

![corebird-toolbar](https://cloud.githubusercontent.com/assets/1652983/15270257/b55abbbe-19e2-11e6-9b9c-cc8f4bc55c70.png)

**Comment by baedert** [comment]
Dup of #548, fixed in master.

**Comment by robmv** [comment]
Sorry for the dup, look like i didn't search well. What about the idea of removing the style change. I find the inactive icons to be unreadable, for example the envelope look like a download icon. When using it side by side with another application I think it is bad the need to select the window first in order to see the real shape of the icons.

Note: I am not a fan of GTK3/ GNOME different style changes for inactive and active windows, but in this case it makes the UI difficult to understand.

**Comment by baedert** [comment]
I have no clue what you mean, it just looks like this, focused or not: http://i.imgur.com/qy74PT2.png

I'm no icon designer, I can't create new ones but that's just the default symbolic mail icon from adwaita-icon-theme.

**Comment by robmv** [comment]
See the original image attached to the issue. Now that the style inversion is fixed. Notice the envelope on the active (after the fix will be inactive) and see it doesn't look like an envelope. I wish there is no style change and the toolbar always look like the image you attached

**Comment by robmv** [comment]
Ignore this for now. Will rebuild and test
