### ISSUE TITLE
Panel menu now "Unknown Application Name" on hover

### ISSUE THREAD

**Issue by jc00ke** [baedert/corebird#552]
Upper left-hand corner, built on 0c8c36b

![_workspace 1_004](https://cloud.githubusercontent.com/assets/18191/15519502/9c02dc2e-21b6-11e6-8011-31fdf6208d63.png)

**Comment by jc00ke** [comment]
Heh, looks like it was fixed in 88617c889c534cc557656227fde4387447d233f8

**Comment by andersbateva** [comment]
This is true for the last release version, 1.3!
@baedert

**Comment by baedert** [comment]
Umm, why? We're always setting the `title` property in `main-window.ui`. The fact that we later change the `title_label`'s contents shouldn't influence that.

**Comment by andersbateva** [comment]
I don't know why this happens, I only knows this happens.
