### ISSUE TITLE
Missing version bump for 1.2.2 configure.ac/about-dialog.ui

### ISSUE THREAD

**Issue by mulander** [baedert/corebird#554]
Last bump was for 1.2.1: https://github.com/baedert/corebird/commit/01528ce878363d2e7710de10b484cb4ad1d837f3

The latest release 1.2.2 still shows 1.2.1 in the about dialog:
https://github.com/baedert/corebird/commits/1.2.2

Don't think this warrants a new release. Just raising notice so it can be added to a release checklist, feel free to close the issue at will :)

**Comment by baedert** [comment]
about dialog was already fixed, configure.ac fixed by https://github.com/baedert/corebird/commit/3b555e1b58799856f0c661b2dad53d7b32d6450a
