### ISSUE TITLE
Support for Twitch Channel Feed

### ISSUE THREAD

**Issue by ivazqueznet** [baedert/corebird#559]
A few months ago Twitch introduced their [Channel Feed feature](https://blog.twitch.tv/attention-broadcasters-channel-feed-beta-is-now-available-28f7c3dff995) which integrates with Twitter. When a message is opened that has been generated by Channel Feed ([ex](https://twitter.com/Totalbiscuit/status/737658931309223936)) it would be handy if Corebird included the text of the feed in the details.

**Comment by baedert** [comment]
This is really out of scrope.
