### ISSUE TITLE
Allowed to send Direct Messages when I'm not really allowed

### ISSUE THREAD

**Issue by andersbateva** [baedert/corebird#562]
Hello. I tried to send a message to the Pope (@Pontifex) using Corebird, because this client showed me the option. But, after writing and clicking to send, I received the error message that I can't send Direct Messages to people that are not following me. The reality is: I can, if the account owner enabled Direct Messages for all (like I did), which wasn't the case. So, I needed to discard the message.

I think Corebird should detect when I really can send Direct Messages (both cases), and only make the option avaiable if I can. If I can't, it should make the option non-clickable.

**Comment by pontifex** [comment]
Confirmed. I haven't get the message from @andersbateva ;)

**Comment by andersbateva** [comment]
Sorry, I meant the Twitter Pontifex, not the GitHub Pontifex...
By the way, the fix was really quickly, I'm impressed!

Just one thing, @baedert : the comit is caled "Load frienship to see if DMs are even possible", but friendship is not the only way to make Direct Messages work...
