### ISSUE TITLE
The "Settings->Notifications->On New Tweets" is disabled and the default value is Never with grey

### ISSUE THREAD

**Issue by MengJueM** [baedert/corebird#568]
The platforms: Ubuntu 16.04, CoreBird: latest

Is that a intentional behaviour?

**Comment by baedert** [comment]
It's insensitive when you have auto-scroll-on-new-tweets enabled.

**Comment by MengJueM** [comment]
@baedert Thanks, it makes sense. It will be cool if any piece of documentation mentions it.
