### ISSUE TITLE
Protected accounts: loading, loading, loading

### ISSUE THREAD

**Issue by andersbateva** [baedert/corebird#570]
When visiting a protected account, like `@laurapoitras`, the tweet list appears as "loading", but it will never load, due to the user not being allowed to read them. So, the client is working wrong, should instead tell "protected". This "loading" appears also in the list of followers, and the list of following; same cause.

Also, the tweet count is 0, which is _really_ strange, but it's an error too: Corebird is not able to retrieve the tweet count, due to the account being protected. So showing "0" is an error.

**Comment by baedert** [comment]
http://i.imgur.com/Nrr2Sr3.png

And what version or Corebird are you running, exactly?

> Corebird is not able to retrieve the tweet count, due to the account being protected. 

That's just a guess. Corebird is displaying what the twitter API returns.

**Comment by andersbateva** [comment]
I'm running 1.1, because Ubuntu doesn't have 1.2.2. So, is this already fixed in 1.2.2?

**Comment by baedert** [comment]
Looks like it is, yes.

**Comment by andersbateva** [comment]
OK then.
But, if Corebird is able to recognize that the account is protected, wouldn't be good if it didn't show "0" in the tweet count? On the official Twitter site, there is no tweet counter for this protected account of the example, while there are for non-protected ones.

**Comment by baedert** [comment]
The 0 has nothing to do with the fact that it is protected, the user details object from the Twitter API has a tweet count field that we read and that's it. Other protected accounts show the number of tweets just fine: http://i.imgur.com/FymzWd6.png

**Comment by andersbateva** [comment]
Understood!

**Comment by andersbateva** [comment]
Compiled here the 1.2.2 (named 1.2.1...) version and saw that, indeed, it was already solved for the tweet list. But, for the following/followed lists, it still shows "loading" and not only this, it freezes and needs to be closed. Or the client closes itself.
