### ISSUE TITLE
click-to-play videos often corrupted

### ISSUE THREAD

**Issue by axfelix** [baedert/corebird#572]
I'm on Gnome 3.20, Linux 4.6.3, Haswell, Arch. Twitter videos (gifs?) play corrupted for me in Corebird about 2/3 of the time. Not sure if gstreamer is calling out to vaapi or what, but this machine usually performs fine on h264 hardware decoding.

**Comment by baedert** [comment]
Related to https://github.com/baedert/corebird/issues/540 ? What Corebird version?

**Comment by axfelix** [comment]
1.2.2-2 from the AUR. gstreamer-vaapi is `gstreamer0.10-vaapi 0.5.9-1` and most of the other gstreamer package versions are like `gst-libav 1.8.2-1`

**Comment by axfelix** [comment]
It does look exactly like the corruption in #540 though

**Comment by baedert** [comment]
Can you find one of those broken videos and get the url, then try playing it with `gst-play-1.0`?

**Comment by axfelix** [comment]
To my surprise, `gst-play-1.0 https:\/\/video.twimg.com\/ext_tw_video\/747773642000338945\/pu\/pl\/QStdLBbvkf8snLI-.m3u8` worked fine (sorry for the weird URL, just c/p'ed it out of the page source) whereas that's corrupted when playing in Corebird.

**Comment by baedert** [comment]
Does "from the AUR" mean you use `corebird-git` or `corebird`?
1.2.2 should never play .m3u8 files, it can only handle mp4.

**Comment by axfelix** [comment]
I've switched builds at times but right now I'm using the non-git.

**Comment by baedert** [comment]
Then can you try the mp4 url and add --videosink=gtksink to the gst-launch-1.0 line?

**Comment by axfelix** [comment]
Ah, sorry, I thought m3u8 was basically just a resolver to mp4/h264 content on twitter. I'll try in a bit.

**Comment by axfelix** [comment]
I'm having a hard time actually finding non-mp4 links, actually; here's another m3u8 that doesn't play properly in Corebird.

**Comment by baedert** [comment]
> I'm having a hard time actually finding non-mp4 links,

non-mp4 links or mp4 links?

> here's another m3u8 that doesn't play properly in Corebird

If you're using 1.2.2 and not master, the .m3u8 is not played. The mp4 is used.

**Comment by baedert** [comment]
Can you try just uninstalling gst-vaapi?

**Comment by axfelix** [comment]
This has been OK for me since I built master for long tweets support this week, I'll reopen this if I can duplicate again. Might've been an issue with the Arch stable builds somehow.
