### ISSUE TITLE
PageUp/PageDown to scroll stops working after clicking buttons

### ISSUE THREAD

**Issue by leonerd** [baedert/corebird#574]
To reproduce:
 * run corebird with multiple accounts
 * click the "switch accounts" button to switch to another account
 * press the `<PageDown>` key

Expected result:
 * The timeline scrolls down one page amount

Actual result:
 * Nothing happens

Reason being: the "switch accounts" button itself retains keyboard focus, so the button eats the PageDown key event. Some amount of clicking the mouse around the scroller eventually gives it back the focus, whereupon the PageUp/PageDown keys now resume their normal scrolling function.

**Comment by baedert** [comment]
That's just how keynav works (apart from the weird `focus-on-click` property)? You can just press Down twice to get the focus into the timeline again.

**Comment by leonerd** [comment]
Yes; indeed it seems I can. But why is that necessary? What possible use is it that the "Switch accounts" button itself retains keyboard focus? The only thing it can do is be pressed again on Space or Enter, but that's what Ctrl-K is for. It has no need to keep that focus; it should renounce it back to something that can handle PageDown sensibly.

**Comment by baedert** [comment]
That's just the default behavior. There are lots of buttons in the UI you could click that will take focus and not give it back to some other widget so it can handle some key.

**Comment by leonerd** [comment]
OK. That doesn't make the issue any better though :)

It's just inconvenient. I don't have a scroll wheel on my laptop keyboard, so I'm basically forced to use PageUp/PageDown to scroll the timeline. It would be nice if corebird made it easy for me to do that. Surely the fix is just one line of `otherwidget.SetFocus()` somewhere in the click handler for that button?

**Comment by baedert** [comment]
> Surely the fix is just one line of otherwidget.SetFocus() somewhere in the click handler for that button?

What button? Again, that's a general problem and not specific to that one button. The back/compose/menu buttons all behave the same, so do all the buttons in tweets.

**Comment by leonerd** [comment]
OK, so most buttons.

Open corebird. Press PageUp/PageDown. Notice how the keypress is eaten, ignored, the timeline doesn't scroll.

Click the switch-accounts button then click an account. Now press PageUp/PageDown. Notice how the timeline doesn't scroll.

Rightclick a tweet to bring up the menu then hit Fave/RT/etc... then return to the main timeline view. Now press PageUp/PageDown. Still no scroll.

In fact, about the only thing you can do that *doesn't* break the PageUp/PageDown keys for scrolling is entering an individual tweet then hitting the "back" button, that little `<` arrow. Because that button desensitises itself, it loses input focus, and now magically PageUp/PageDown *do* work just fine.

This all makes it very inconvenient to use corebird when your pointing device lacks a scroll wheel - such as most laptops.

**Comment by baedert** [comment]
> Because that button desensitises itself, it loses input focus, and now magically PageUp/PageDown do work just fine.

It doesn't always get insensitive obviously, we rather save the last row that was focused and restore that on join.

Keyboard shortcuts always depend on the keyboard focus. That's why pageup/down works again when double-clicking the Home button for example.

This is not a bug and forcing the keyboard focus to stay inside a listbox forever is not a solution.
