### ISSUE TITLE
"Copy Link" menu only does CLIPBOARD, not PRIMARY

### ISSUE THREAD

**Issue by leonerd** [baedert/corebird#578]
If you "Copy Link" then the link text does end up in the X11 CLIPBOARD, meaning you can Ctrl-V paste it elsewhere.

However, it doesn't additionally end up in the PRIMARY selection, meaning you can't middle-click paste it.

This might matter as e.g. most browsers have an easy middle-click "open a new URL from selection" option, and also most terminals only support paste from PRIMARY via middleclick and don't actually interact with the CLIPBOARD at all.

**Comment by baedert** [comment]
That's a gtk+ feature so you'll have to open a bug in their bug tracker.
