### ISSUE TITLE
GNU Social Support

### ISSUE THREAD

**Issue by taingra** [baedert/corebird#579]
Feature request: support for using [GNU Social](https://gnu.io/social/) with Corebird

**Comment by baedert** [comment]
But have you seen the [FAQ](http://corebird.baedert.org/#faq)?

**Comment by taingra** [comment]
If I added it myself would you accept the pull request?

**Comment by baedert** [comment]
Sorry for the delay. Generally i just shrug at such things, but I certainly do not want to support something I don't use at all; It's just support questions I can't answer and bugs I can't reproduce in the end.

**Comment by DamonGant** [comment]
@baedert It's the same API, you'd need to refactor the hostname to be set by the current account, dynamically set the OAuth endpoint and maybe add a combobox for the endpoint when setting up a new account, that's it.

https://gnusocial.no/doc/twitterapi

So the cost of implementation is miniscule and I think a lot of GNU social users are used to living without support.

**Comment by DeadSuperHero** [comment]
As a GNU Social user, I'd like to also chime in and say that I'd love to see support in CoreBird. This is probably one of the best Twitter apps I've seen for the Gnome desktop; I think a lot of people in the federated microblogging community would love it.

For what it's worth, the GNU Social platform is fairly comparable to Twitter in its format and usage. My profile, for example, [looks pretty much the same as Twitter.](https://quitter.no/deadsuperhero)

**Comment by romeofox** [comment]
GnuSocialSupportRequestCount++;
