### ISSUE TITLE
Cannot change to bigger fonts

### ISSUE THREAD

**Issue by doihara** [baedert/corebird#582]
I have Corebird running on a small laptop and the font size is too small for comfortable reading.
I changed my system fonts to larger size, but it didn't seem to have any effect in Corebird. I didn't find font-relevant setting options in Corebird either.   
Any suggestions? Thank you!

![screenshot_20160719_130716](https://cloud.githubusercontent.com/assets/20506319/16947912/150fe9be-4db2-11e6-87f2-4ce138a88cb2.png)

**Comment by baedert** [comment]
I'm not full aware how the interaction between kde and gtk works here but apparently gtk+ looks at some xsettings which KDE doesn't directly use but some distros patch it in. i.e. you probably have to ask someone using your distribution how to persistently change gtk3 fonts/font sizes, or at least someone using KDE.

**Comment by doihara** [comment]
Then I will look for solutions in KDE related forums. Thank you for the suggestion.
