### ISSUE TITLE
Favorite tweet should be Like

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#586]
Twitter changed favorites to likes a while ago and Corebird properly shows a heart icon now instead of a star. But the text, when one hovers over the heart icon, still says 'Favorite tweet' instead of 'Like'. Minor issue, I know and it doesn't bother me but for consistency, it would be nice if it the text got changed to 'Like' ;-)

**Comment by baedert** [comment]
We had #428 about that and #429 changed only the icons while leaving the text; which I thought is a good compromise. (Really, any word said about a change like that is a word too much.)
