### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#590]
I haven't seen an update to the translations in a long time on Transifex. I do see that you update the PO(T) files here. Aren't you using Transifex anymore?

**Comment by baedert** [comment]
They are "updated" aka `make update-po`. Transifex is still being used, but I don't translate anything myself. If you want to see changes in transifex, you need to change things yourself.

**Comment by Vistaus** [comment]
Yeah, but it still says it's 100% translated in Dutch (which is the translation I maintain). It says that for months now despite PO(T) updates on Github...

**Comment by baedert** [comment]
Yeah so transifex apparently thought the URL I pointed it to didn't exist (which it did of course) so it didn't automatically update the pot file while still saying that it did ("updated on Jul 20th", etc). I've removed the URL and readded it and it doesn't complain anymore, then I just updated the pot flie manually once. We'll see if that happens again...

**Comment by Vistaus** [comment]
Thanks for fixing it so quickly! I see updated translations now on Transifex. I'll close this for now (I can always re-open it should it happen again ;-) ).

**Comment by Vistaus** [comment]
I'm reopening this because the issue seems to have surfaced again. You updated the po files and I do see modified strings, but Transifex hasn't picked them up yet...

**Comment by baedert** [comment]
I manually updated the pot file again.

**Comment by Vistaus** [comment]
That worked! I just updated the translation on Transifex. Thanks! 😄
