### ISSUE TITLE
Corebird sometimes freezes computer upon notifications

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#595]
Sometimes when I get notifications, either for replies or DM's, it locks up the whole desktop (GNOME Shell 3.20.x) and I need to kill the X server to return to normal working state. It happens randomly so it's hard to reproduce and I couldn't really find any log with information regarding the crash.

**Comment by baedert** [comment]
I can't seem to reproduce this; what notification was it specifically and in what situation?

**Comment by Vistaus** [comment]
Notification for a reply. It happened a few times. Although I haven't experienced it since I filed this bug report... I'll post here if it happens again.

**Comment by Vistaus** [comment]
I can't seem to reproduce it anymore. I'll close this issue and open it again if needed.
