### ISSUE TITLE
Compose Message Box resizes incorrectly upon long texts

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#597]
I couldn't upload the screencast I made here so I've uploaded it to YouTube: https://www.youtube.com/watch?v=tK1HwWCL2V4&feature=youtu.be

Hope we can figure this out and fix this :)

**Comment by baedert** [comment]
Wait, is that just the overflow indicator? How that that look with Adwaita?

**Comment by Vistaus** [comment]
It seems to work right in Adwaita. Do you think it's a theme issue with the theme I'm using?

**Comment by baedert** [comment]
Yes, can you try opening the GTK inspector (running with `GTK_DEBUG=interactive` should work) and pasting

```
undershoot {
  background-color: red;
  background-image: none;
}
```
into the CSS tab and check if it works then?

**Comment by Vistaus** [comment]
I would love to, but I have no idea how to launch GTK+ Inspector. I've tried looking on Ask Ubuntu and there were a few questions about it but no shortcut or solution seems to work. Do you happen to know the command to launch GTK+ Inspector? (it must be something general cross-distro, right?)

**Comment by baedert** [comment]
`GTK_DEBUG=interative corebird` should work, for further documentation look at https://wiki.gnome.org/Projects/GTK%2B/Inspector

**Comment by Vistaus** [comment]
GTK_DEBUG=interative corebird
launches Corebird but I don't see the inspector popping up (and thus no CSS tab) :confused:

**Comment by baedert** [comment]
It's interactive, not interative...

**Comment by Vistaus** [comment]
Oops, you're right.

It resizes correctly after applying your CSS code. Although it does display red bars over the compose message box eventually.
![screenshot_2016-08-02_13-51-56](https://cloud.githubusercontent.com/assets/1716229/17327462/7279bd12-58b8-11e6-98c5-7a11f751ff78.png)

**Comment by baedert** [comment]
Of course, that's exactly what the css snippet does. replace `red` with `transparent` to remove them, but it would be better to file a bug against your theme of course, corebird isn't applying anything custom to the textview here.

**Comment by Vistaus** [comment]
Alright, I'll file a bug on the theme creator's Github. Thanks for all the help! :smile:
