### ISSUE TITLE
Saving images directly from Corebird

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#598]
It would be a great addition to Corebird if images could be saved directly saved from Corebird, just like on the Twitter website (right click menu ---> Save image as...) and official Twitter apps (overflow/popup menu ---> Save image) :smiley:

**Comment by baedert** [comment]
The menu entry for this has been removed in 1.2.1: https://github.com/baedert/corebird/releases/tag/1.2.1
We don't have the original image data in memory anymore, just a cairo surface. The only option would be to download the image again and save it on disk that way.

**Comment by Vistaus** [comment]
Would be awesometo have this feature again :smile:

**Comment by mulander** [comment]
I agree with @Vistaus even if this means re-downloading the content it's a nice feature to have. Currently I have to copy the URL and either open a terminal or a browser to download an image.

It would be even nicer if there was an option to grab the original upload (the :orig url ie. https://pbs.twimg.com/media/Cyre_NQW8AACD6-.jpg:orig).

**Comment by baedert** [comment]
That should work now in master (from timelines, should do the same when viewing media). .mp4 videos work as well but not .m3u8.

**Comment by Vistaus** [comment]
Thank you so much for implementing this! I've tested it and it works fine for photos (haven't tested videos, but I generally don't save videos so I'm taking your word for it that it works :wink: ) :smile:
