### ISSUE TITLE
Too many requests happens way too often

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#599]
Sometimes it even happens like 30 seconds after opening Corebird but often after a few minues. Sometimes I opened a few tweets, sometimes it just happens during scrolling. The exact error message is:
"Could not show information. Too many requests."

How come and can it be fixed?

**Comment by baedert** [comment]
Depends what you are doing. For most API endpoints, the Twitter API is simply rate-limted to 15 requests per 15 minute window.

**Comment by Vistaus** [comment]
But I doubt I've reached 15 requests right after opening Corebird (which happens sometimes, as I noted in the OP).

**Comment by baedert** [comment]
No idea, restarting the client doesn't affect the 15min window of course. You could configure with `--enable-debug`, which should print most requests made.

**Comment by Vistaus** [comment]
Strangely enough, I can't seem to reproduce it in debugging mode :/

**Comment by Vistaus** [comment]
I'll close this for now as it seems like you're right about it being something on the Twitter end.

**Comment by tassoman** [comment]
I'm having the same issue behind company proxy.
The option `--enable-debug` isn't working.
The only thing I'm able to do is starting corebird as server, then opening the gtk client i get this message:

> ** Message: DefaultTimeline.vala:358: Too Many Requests

**Comment by baedert** [comment]
> The option --enable-debug isn't working.

That just prints debug output, nothing else.

>  The only thing I'm able to do is starting corebird as server, then opening the gtk client i get this message:

"start it as a server"? The message won't disappear for a full 15 Minutes once it appears, that's the limit set by Twitter, so you have to make sure to wait.

**Comment by tassoman** [comment]
Yes, until now I'm waiting the annoying limit ends but in the past never happened.
I understand twitter have limited public usage.
Twidere Android client lets you define your custom api credentials, so I've created a twitter-app inside my account just used to drive the android client. Maybe would be a solution also for corebird?

**Comment by baedert** [comment]
>  Twidere Android client lets you define your custom api credentials, so I've created a twitter-app inside my account just used to drive the android client. Maybe would be a solution also for corebird?

I don't see how that would help you but you can set your own consumer key and consumer secret

**Comment by tassoman** [comment]
You mean I must recompile from source with custom consumer key/secret, is it? 
I think I gonna try.

**Comment by baedert** [comment]
No, you can use dconf-editor to set the org.baedert.corebird consumer-key and consumer-secret fields.

**Comment by tassoman** [comment]
Well, I did it. I've also removed `~/.config/corebird` directory but didn't helped. I bet the problem is because here I'm from behind a proxy. Maybe twitter is logging how many connection they have from the same IP address cause this problem isn't happening connecting from different locations.

**Comment by tassoman** [comment]
I've erased caches and configs. Then I've reinstalled my account by using `dconf-editor` and setting custom Twitter's api consumer key pairs. Now it's working and error has gone, can'say why/how.

Another thing emerged being behind proxy and I filed under: #673

**Comment by eddelbuettel** [comment]
I tried `dconf-editor` to just replace the two consumer fields (with what I believe to a valid pair I use [rarely] for a scripting tool) and I got authentication denied :-/   So back to defaults and running against this warning every hour or so.

**Comment by eddelbuettel** [comment]
This may be relevant, and sad:  https://www.patreon.com/posts/corebirds-future-18921328
