### ISSUE TITLE
APT Repository

### ISSUE THREAD

**Issue by 876974** [baedert/corebird#60]
For this moment this client an only be installed via the compiling.
BUT I would really like to see this client in such a distro like Debian/Ubuntu
Easy installation with APT repository already compiled the client.

**Comment by zedtux** [comment]
@EdwardBetts any chance to have an upper version than 0.7 in your Debian repo ?

**Comment by EdwardBetts** [comment]
@zedtux Will do.

**Comment by EdwardBetts** [comment]
I've updated my Debian package, version 1.0 is available here: http://edwardbetts.com/corebird/

**Comment by samdraz** [comment]
can you mention it in Readme ?

**Comment by zedtux** [comment]
Thank you @EdwardBetts

**Comment by TacoDelPaco** [comment]
Thank you!

**Comment by EdwardBetts** [comment]
Corebird is now available in Debian unstable: https://tracker.debian.org/pkg/corebird

**Comment by zedtux** [comment]
Awesome news ! Thank you @EdwardBetts.

**Comment by DanScharon** [comment]
great! any chance for getting it into jessie-backports?

**Comment by smdrz** [comment]
@DanScharon, corebird =>1.1 depends in 3.16, no way to backport it.
