### ISSUE TITLE
Retweets disabled show up in notifications

### ISSUE THREAD

**Issue by kajzersoze** [baedert/corebird#601]
When I check "Retweets disabled" for some user account, retweets from that user do not show up in timeline, but they appear in notifications.

**Comment by baedert** [comment]
in what notifications?

**Comment by kajzersoze** [comment]
I'm not sure what you mean by that, but when there's a new tweet you receive a desktop notification.
So, like I said .. if "Retweets disabled" for some account is checked I shouldn't get those retweets, and I don't (in timeline) , however I receive a notification with that retweet shown.

**Comment by baedert** [comment]
> when there's a new tweet you receive a desktop notification

So you get them because you you have notifications set  up for On New Tweets?

**Comment by kajzersoze** [comment]
Exactly.
Leave it be for now, might have been my mistake, kinda hard to reproduce.
I'll test it again soon and close this issue if I don't see it again, otherwise will let you know.

**Comment by baedert** [comment]
It's pretty simple to reproduce since I could use https://github.com/baedert/corebird-debug-tool, but what you said makes sense based on me staring at the code for some time, see that commit above.

**Comment by kajzersoze** [comment]
Ah I see, that commit makes sense, what I meant by "hard to reproduce" was that I'm busy with something else atm :) 
Anyway, in the meantime if you can reproduce it then commit it, otherwise I'll play with it a little later.
Thanks.

**Comment by kajzersoze** [comment]
I apologize for my confused posts, kinda rushed through them, anyway.. pulled up that commit and problem solved. I guess the same problem would happen with blocked and muted tweets, but I never used those (but I guess they would appear in notifications as well) and this commit is solving them as well.
