### ISSUE TITLE
Please release proper make distcheck tarballs

### ISSUE THREAD

**Issue by ikeydoherty** [baedert/corebird#602]
In your `configure.ac` you explicitly request an uncommon version of gettext, which is not mandatory fwiw, yet you don't release `distcheck` tarballs.

If you're going to use explicit gnu gettext versions, you need to then distribute the tarball on the GitHub releases mechanism (not just a GitHub autogenerated tarball), which will then *include* the relevant `m4` and `gettext` support assets for the version _you_ specify in `configure.ac`, thus nullifying a distribution issue.

Its very common that all distros have different versions of gettext. It should also be noted that `make distcheck` should be a part of normal build practices to ensure everything works as intended when using `autotools`, and you get a free distributable tarball as a result. There is no hosting cost to this either, you can just upload it to your releases on GitHub by editing a tag.

I strongly hope you consider this, and if you need advice on the best way in which to achieve this, I'm happy to help. I'd just rather not carry patches to `configure.ac` for every release of corebird we have in Solus. :)

**Comment by ikeydoherty** [comment]
(Edit: Even if there is reason for explicit minimum gettext version, the same problem exists going forward with new gettext releases, there needs to be tarballs to stop the configure issues)

**Comment by baedert** [comment]
> In your `configure.ac` you explicitly request an uncommon version of gettext, which is not mandatory fwiw, yet you don't release distcheck tarballs.

I need the minimum version *I think* so I don't need intltool anymore(?). Or is removing the requirement just going to fix everything?


> that make distcheck should be a part of normal build practices

Eh, make distcheck didn't work for me before those changes and did after :(

> if you need advice on the best way in which to achieve this, I'm happy to help. I'd just rather not carry patches to configure.ac for every release of corebird

Whatever I can do to touch autotools less is a good thing :P Do those patches to the configure.ac already exist and I can just upstream them or are they theoretical?

**Comment by ikeydoherty** [comment]
Oh if `make distcheck` is acting the bollocks I can understand, I'll try and dig through it when I get some spare time so we can make 'em work. Right now we're having different integration problems with corebird because we updated to Qt 5.6 so there's a bit of work to come from us yet I think

**Comment by baedert** [comment]
So would it be fine if I just an `make distcheck` here on my machine and then uploaded that tarball to the git tag (asking because I'd like to do a 1.3.1)?

**Comment by kalev** [comment]
Yes, this is exactly how it's done for gnome releases. A developer runs 'make distcheck' on their machine and then uploads the tarball.

**Comment by baedert** [comment]
Hmm ok there's one for 1.3.1 now.

**Comment by baedert** [comment]
Thanks kalev, I guess I can close this one now.

**Comment by kalev** [comment]
Thanks @baedert!

**Comment by ikeydoherty** [comment]
Oh wth I didn't get notifications for this. Sorry bud.
