### ISSUE TITLE
Loading Flickr images fails, breaks loading other images

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#603]
I've just updated to the latest Git Master (f04f1bd). pic.twitter.com images load fine, as does Vine, but if I see a Flickr image then the image tries to load (there's a space for it an "0%") but it never loads. Once it does that, all future images (including pic.twitter.com) don't load and show "0%".

I enabled debugging and get:

```
** (corebird:22344): WARNING **: Media is invalid.
```

and later:

```
(corebird:22344): GLib-CRITICAL **: g_ptr_array_remove_range: assertion 'index_ < rarray->len' failed
```

but nothing else.

This also seems to break prevent the app from closing.

Steps to reproduce:
- Update to f04f1bd
- Load Corebird
- Search "Flickr". See Flickr images try to load but just sit at "0%"
- Go back to main timeline
- Load older tweets to try and find some "normal" image tweets
- See images try to load but just sit at "0%"
- Try to close app
- Gnome eventually says "Corebird is not responding" (last debug message: "*\* (corebird:22344): DEBUG: Twitter.vala:351: Removing avatar with id 104 from cache (Now: 111)"

Expected behaviour: 
- Flickr images load
- Other images still load after loading Flickr images
- App doesn't refuse to close!

I'm going to poke the source and see if I can get more useful debugging from the right area.

**Comment by baedert** [comment]
Eh, I can search for flickr and the images load fine here.

**Comment by IBBoard** [comment]
Put in more and more debugging and eventually it started working without any code changes. Possibly just Flickr not responding at the time? At which point the bug may become "if a preview doesn't load, Corebird fails to load more previews and won't close".

I'll test again tomorrow.

**Comment by baedert** [comment]
So the waiting at the end basically seems to be GtkApplication waiting for all the GTasks to be finished.

**Comment by IBBoard** [comment]
I've put some debug in again and it looks like it basically never returns from soup_session_send_message() in MediaDownloader.c.

I've also had it happen when searching "Instagram" and "Vine" (just as a way to make images from those services appear). Anything using the word but with images on Twitter loads correctly, then the Instagram/Vine/Flickr ones load and the background download threads never make it past soup_session_send_message() for fetching the page to find the thumbnail URL.

The GTask data change doesn't seem to have altered the "shutdown after bug" behaviour either. Still hangs until you kill it.

**Comment by IBBoard** [comment]
Debugging this isn't getting any clearer. It looked like anything that needed a redirect/pre-fetch was breaking, but then http was working and https wasn't. I've just posted a HTTP Flickr image (https://twitter.com/IBBoard/status/767017215031930882) and it redirected to a HTTPS and loaded it without a problem, then I searched "Flickr ibboard" and it loaded, then "Flickr windsor" and it loaded, then "flickr" and it failed to load almost all of the Flickr images (but it loaded the Twitter ones).

It's almost as if it chokes when it has too many concurrent HTTPS connections or something.

The debugging statements I'm using are at https://gist.github.com/IBBoard/34febf7d1c9bf8900c5012b884917e11

**Comment by IBBoard** [comment]
I just recreated this by accident by swapping profiles. There were 15 tweets with images (including one tweet with 3 images and one tweet with 4 images, for 20 images in total) in the batch of tweets it showed. All of the images are stuck on "0%".

As I was already debugging, I ran ```killall -2 corebird``` to kick GDB to a breakpoint. The [backtrace](https://gist.github.com/IBBoard/64dfedbcbd293eece33770bfc3d593b9) shows that Soup is stuck on a g_cond_wait for something.

I don't know if that helps.

**Comment by baedert** [comment]
We should be cancelling all the downloads on app shutdown now, can you retry if the problem still exists?

**Comment by IBBoard** [comment]
I can't recreate the hanging at the moment (which I suspected was a GnuTLS/Soup thing), but if I close Corebird while images are still at 0% then I can confirm that it does now close rather than having to be killed.

I'll close this ticket for now and re-open it if the Flickr "0% loading - never finishes" issue comes back.
