### ISSUE TITLE
MainWindow gets bigger, when closing and opening again

### ISSUE THREAD

**Issue by spaghettic0der** [baedert/corebird#604]
Ubuntu Gnome. I think the geometry is wrongly saved or is wrongly loaded. 
I resize corebird to it's smallest. Close it. Open it again. Close it again. Reopen it. The windows get's a little bit bigger everytime.

**Comment by baedert** [comment]
That sounds like you use an old corebird version (say 1.1) with that gtk version that slightly changed the semantics of window sizing (say 3.20).

**Comment by Vistaus** [comment]
@spaghettic0der I'm also using Ubuntu GNOME (16.04), but with GTK 3.20 (upgraded to 3.20 using the GNOME 3 Team PPA) and always the latest Git version of Corebird. I can't reproduce this issue so @baedert is probably regarding to what you're using.

**Comment by max-wittig** [comment]
weirdly it fixed itself, aber updating to 16.10, but I also had the latest gnome 3 ppa installed
