### ISSUE TITLE
Twitter emoji support (display+selection in compose window)

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#607]
Could this library of official emojis be useful for implementation in Corebird for emoticon display and also for selection from the compose window?
https://github.com/twitter/twemoji

**Comment by IBBoard** [comment]
Have you tried the Twemoji font? It will only do colour in Firefox and outlines in other GTK apps (because GTK doesn't support full colour fonts yet) but it's part way there :)

https://github.com/eosrei/twemoji-color-font

**Comment by baedert** [comment]
Yes, emojis need support in lower layers. Also there's #197.

**Comment by Vistaus** [comment]
@IBBoard Switching fonts is annoying and not a solution because it's not what I proposed, which is an integrated option.

@baedert Ah, didn't know that. Thanks!

**Comment by IBBoard** [comment]
It doesn't switch fonts. It changes the fall-back font to one that *does* contain the emoji. In colour. And doing that gets you as close as you can as easily as possible without GTK/Pango (IIRC) updating to support colour fonts.

But to each their own.

**Comment by Vistaus** [comment]
But how does that work then? Say I'm just using my regular font to compose a tweet but I want to insert an emoji using that Twemoji font. How do I do that?

**Comment by IBBoard** [comment]
Depends. Basically it is like other characters. XCompose lets you define shortcuts (e.g. [I have Right-Win+":"+")" mapped to 😊 and Right-Win+"o"+"_"+"O" mapped to 😲](https://dev.ibboard.co.uk/repos/other/linux/file/tip/XCompose)). Other input methods probably have Windows-esque "Alt+character code". Android relies on the bespoke keyboard.

The idea is that not all fonts support all characters, and if a character isn't in a font then the OS looks down its fall-back list to see if any of the other fonts that are similar contain the character.

How do you enter emoji on Twitter? I can't see how to do it without Copy&Paste or XCompose combos.

**Comment by Vistaus** [comment]
Thanks, I'll look into it.

**Comment by Vistaus** [comment]
Seems like there's another way to enable emoji support, which even works in Corebird, according to the article: http://www.omgubuntu.co.uk/2016/08/enable-color-emoji-linux-google-chrome-noto

Maybe this could be used in the meantime until GTK3 supports it natively?

**Comment by baedert** [comment]
That's just changing the font, you can do that today but you need to install the font yourself (just like I've told people to install symbola in the past).

**Comment by Vistaus** [comment]
At long last, full color emoji support is now available in the Adwaita icon theme so it seems like it's supported by GTK now then!
https://git.gnome.org/browse/adwaita-icon-theme/commit/?id=aec89cdeefa5e700a7bb9a55f7c7af3cae5d0b19

**Comment by IBBoard** [comment]
Adwaita already has full-colour emotes - check ```/usr/share/icons/Adwaita/<size>/emotes/```:
![screenshot from 2016-10-18 10-57-31](https://cloud.githubusercontent.com/assets/388582/19473048/c6d92cb2-9521-11e6-8da6-13dd03baa4c7.png)
And if you look at the comparisons then there's barely any difference. In fact, looking at the diff on the SVG then I'd say it was mainly noise from the SVG being opened, the colours being tweaked slightly, and the editor reordering lots of attributes as it saved.

Also, unfortunately GTK emotes have nothing to do with fonts. Emotes are there for GTK widgets, whereas text is written (IIRC) by Pango using fonts (e.g. TTF files).

You also used to be able to apply emotes/symbols to files through Nautilus, but it seems that Gnome 3 dropped that.
