### ISSUE TITLE
Question about inappropriate content

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#608]
What exactly counts as inappropriate content?

**Comment by baedert** [comment]
Whatever people flag as such. It's a field in Twitter's tweet objects and you can set whether or not your images are inappropriate in the twitter settings.

**Comment by Vistaus** [comment]
I know that you can set that in the Twitter settings. The reason I asked this was because I thought that maybe Corebird had its own pattern for this. But I understand now that it just honors Twitter's pattern. Thanks for the quick reply! :smile:

**Comment by Vistaus** [comment]
I still have one question. I've set that particular setting in my Twitter settings and now it asks me every time if I want to view said media anyway. If I enable this setting in Corebird, will it ask me if I want to view it as well? If not, can you add that to Corebird please? :)

**Comment by baedert** [comment]
Not sure if I understand what you mean but it should ask you whether you want to see each image that is marked as inappropriate.

**Comment by Vistaus** [comment]
You've understood me correctly! Thanks :)
