### ISSUE TITLE
Increase tab height (a little bit)

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#609]
I was wondering if you could increase the height of the tabs by a bit? 'Cause I find them quite hard to accurately click on.

**Comment by baedert** [comment]
Dunno, seems fine to me although we're not fiddling with the padding in the app css here so  the actual height also depends on your theme, we even set `.image-button`, and it ends up being 32px high here.

**Comment by Vistaus** [comment]
I now see that the tabs are bigger with the theme Edge-Dark. But with all other themes I've tried (a lot!), including the default Adwaita (!), it does happen. I would've expected that at least Adwaita would work right but no cigar. So the only theme I can use is Edge-Dark then...

**Comment by baedert** [comment]
There's no wrong or right here, they just have a height and that varies. The current button strip is just 2px smaller than regular buttons in adwaita.

**Comment by IBBoard** [comment]
@Vistaus Maybe if you post screenshots comparing the themes then we can see why they differ?

**Comment by Vistaus** [comment]
I see that Adwaita works fine now. Maybe the last Adwaita update fixed the tab height somehow. I will close this issue for now. Thanks to all the participants! :smile:
