### ISSUE TITLE
Inactive accounts doesn't appears as such

### ISSUE THREAD

**Issue by andersbateva** [baedert/corebird#613]
When viewing inactive and active accounts, the difference isn't clear... For example, the date of the last tweet appears as "26 Jul" or "11 Aug" without revealing that the year is, respectively, 2012 and 2013. See `@marchamaconhafp` and `@MarchaMaconhaAL`. This requires the user to click on the last tweet to view more detailed information. Couldn't be shown more directly? I don't like to interact with inactive accounts...

**Comment by Vistaus** [comment]
I like that it it's fixed 'cause I didn't like it either, but just FIY: Twitter does this as well on their website so it's something they decided to design. But again: I don't like it so thanks @baedert for fixing it! :)
