### ISSUE TITLE
Blocked account still shows up on timeline

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#615]
I blocked a couple of accounts last week but they still show up on my timeline in Corebird. They don't show up on twitter.com Not sure what happens here and not sure if this is a Corebird problem, but I'm reporting just in case it is.

**Comment by baedert** [comment]
Are they in the bunch of tweets that get downloaded on startup or do they appear later on?

**Comment by Vistaus** [comment]
Both.

It's something that didn't happen until at least a few days ago. So either one of the latest commits triggered this or something's wrong on the Twitter API end.

**Comment by baedert** [comment]
That should both be pretty much impossible since *blocking* implies unfollowing which means that their tweets should not appear in any of the calls to the Twitter API concerning your account.

**Comment by Vistaus** [comment]
Then I don't know how this could've happened. I'll monitor it for a few days, see if it happens again.

**Comment by Vistaus** [comment]
Can't seem to reproduce it anymore now. Will re-open this if it start happening again.

**Comment by Vistaus** [comment]
It just happened again. Guess it's a bug in the Twitter API? Sorry if it's a dumb question but is there any place I can report bugs to Twitter regarding their API?

**Comment by baedert** [comment]
https://twittercommunity.com/ lets you at least ask about things like that.
