### ISSUE TITLE
Can't tell when I've retweeted

### ISSUE THREAD

**Issue by allanday** [baedert/corebird#617]
There's a strip of buttons at the bottom of each tweet "page" - retweet, like, reply. When I pressed the retweet button it wasn't clear whether it had been successful or not. I pressed again to see if it had an effect and couldn't see any noticeable difference between the retweeted and not retweeted state.

**Comment by baedert** [comment]
Well the retweet icon is green if you've retweeted it (or it should be), is that not distinguishable enough?

**Comment by allanday** [comment]
Going back to the tweet, i can see that it's a different colour. I definitely wasn't able to see that when I pressed it though (I actually tried pressing it repeatedly to check). I'll see if I can reproduce.

Either way, the green and the grey do look a bit too similar to me:

![image](https://cloud.githubusercontent.com/assets/213068/18271057/24b93162-7428-11e6-90fa-4910e4bb9a07.png)

One of the issues here is that the icons are relatively small, which makes the use of different colours less easy to distinguish.

**Comment by allanday** [comment]
The colour of the favourite heart is also rather subtle:

![image](https://cloud.githubusercontent.com/assets/213068/18282839/bae498fc-745a-11e6-9eb1-9ed804b97e6e.png)

**Comment by baedert** [comment]
Can't really think of a better way to indicate this (apart from just using `GtkToggleButton`'s default `:checked` style), the colors are pretty ok on my display but making them brighter doesn't really help a lot IMO, especially for the retweet button which just doesn't have  a lot of area: http://i.imgur.com/RE2oLjw.png

The only other option I came up with is http://i.imgur.com/PWFoUCf.png and that looks kind of horrible as well.

**Comment by allanday** [comment]
The general approach seems fine. The main issues are the colours, the size of the icons, and your retweet icon which looks a bit fuzzy.

Here's a couple of experiments:

![corebird-buttons](https://cloud.githubusercontent.com/assets/213068/18320939/de57f0c6-7523-11e6-8751-d90abbab57c7.png)

On the left I've changed the colours and used a retweet icon that is aligned to the pixel grid. On the right I've increased the size of the icons a bit (in addition to the recognition issue they seem a bit small as click targets to me).

**Comment by baedert** [comment]
Played with the retweet icon a bit: http://i.imgur.com/MtzMSH9.png

**Comment by allanday** [comment]
> Played with the retweet icon a bit: http://i.imgur.com/MtzMSH9.png

Got the svg so I can take a closer look?

**Comment by allanday** [comment]
> Yup, it's at https://github.com/baedert/corebird/blob/master/data/symbolic/apps/corebird-retweet-symbolic.svg

I'm no icon expert, but that doesn't look right to me. It's not 16x16 pixels, it doesn't look grid aligned, and there are loads of nodes where you don't need them.

Here's two SVGs I've made - one is similar in style to yours, and one is more in a GNOME style.

https://dl.dropboxusercontent.com/u/5031519/corebird-retweet-symbolic1.svg
https://dl.dropboxusercontent.com/u/5031519/corebird-retweet-symbolic2.svg

**Comment by Vistaus** [comment]
I agree that the icons are way too small. They should be bigger. Or maybe offer an option to show a right-click menu with the available options instead? (the official Twitter app on my phone does offer menu options when I press and hold a tweet, I do like that)

**Comment by baedert** [comment]
> I agree that the icons are way too small.

I don't get that, the buttons have the usual `.image-button` size.

> Or maybe offer an option to show a right-click menu with the available options instead? (the official Twitter app on my phone does offer menu options when I press and hold a tweet, I do like that)

Inside a timeline, you can right-click tweets to get the same rt/fav/quote options but I don't see how that helps with small non-recognizable icons.

**Comment by baedert** [comment]
@allanday I couldn't test the second icon due do that recoloring issue (and I couldn't figure out why it was broken either...). I didn't really like the first one since the arrows are so slim and the heart next to that icon is so fat.
This is what I have now locally: http://i.imgur.com/4m6p78S.png (that's the first icon you posted a little modified)
(One could argue now that the reply arrow is also too slim...)

Is that readable enough on your screen (and the icon now too ugly)?

**Comment by the-kyle** [comment]
I'm having somewhat similar trouble knowing when I have retweeted using the keyboard tt shortcut, but this is accessibility related rather than an indistinguishability between icon colors. I would need a spoken accessible indicator of some sort to let me know I have retweeted or favorited a tweet. If this comment doesn't belong to this issue, I can move it to a new issue. Thanks.

**Comment by baedert** [comment]
Should be clearer now.
