### ISSUE TITLE
git master fails to build on Fedora Rawhide

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#618]
Current git master fails to build on Fedora Rawhide with following errors:
>MainWindow.vala:340.7-340.32: error: The name `popup' does not exist in the context of `Gtk.Popover'
      this.account_popover.popup ();
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
MainWindow.vala:87.9-87.31: error: The name `popdown' does not exist in the context of `Gtk.Popover'
        account_popover.popdown ();
        ^^^^^^^^^^^^^^^^^^^^^^^
MainWindow.vala:106.9-106.31: error: The name `popdown' does not exist in the context of `Gtk.Popover'
        account_popover.popdown ();
        ^^^^^^^^^^^^^^^^^^^^^^^
MainWindow.vala:227.7-227.29: error: The name `popdown' does not exist in the context of `Gtk.Popover'
      account_popover.popdown ();
      ^^^^^^^^^^^^^^^^^^^^^^^
MainWindow.vala:244.7-244.29: error: The name `popdown' does not exist in the context of `Gtk.Popover'
      account_popover.popdown ();
      ^^^^^^^^^^^^^^^^^^^^^^^
MainWindow.vala:255.7-255.29: error: The name `popdown' does not exist in the context of `Gtk.Popover'
      account_popover.popdown ();
      ^^^^^^^^^^^^^^^^^^^^^^^
MainWindow.vala:355.7-355.29: error: The name `popdown' does not exist in the context of `Gtk.Popover'
      account_popover.popdown ();
      ^^^^^^^^^^^^^^^^^^^^^^^
MainWindow.vala:357.7-357.27: error: The name `popup' does not exist in the context of `Gtk.Popover'
      account_popover.popup ();
      ^^^^^^^^^^^^^^^^^^^^^
widgets/LazyMenuButton.vala:25.5-25.17: error: The name `popup' does not exist in the context of `Gtk.Popover'
    popover.popup ();
    ^^^^^^^^^^^^^
Compilation failed: 9 error(s), 0 warning(s)

**Comment by baedert** [comment]
That happens when you have gtk+3.21 but not an updated vala that actually binds `gtk_popover_popup` and `gtk_popover_popdown`.

**Comment by HeikoAdams** [comment]
Rawhide and Fedora 25 are shipping vala 0.32.1

**Comment by baedert** [comment]
*sigh* Looks like there's no vala release with the updated `gtk-3.0.vapi`...

**Comment by HeikoAdams** [comment]
_strange_ building on my local Fedora 25 works fine

**Comment by HeikoAdams** [comment]
So that means I've to wait until there's a vala release shipping that gtk-3.0.vapi and Fedora ships that release before I can again successfully built corebird git-snapshots on Fedora 25/Rawhide?

**Comment by baedert** [comment]
I can also just revert b8131eee8c2e18e0f8ecf7611cddee12bc5e4f18 and 8aadeea191b873a37e5a3cbcb5db019f342bf971 for the time being until there's a new vala release.

**Comment by baedert** [comment]
Can you tell me when the new vala release hits rawhide?

**Comment by HeikoAdams** [comment]
I'll try to do so
