### ISSUE TITLE
Feature request: Remove Tweet option after clicking on own tweet

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#619]
I can remove a tweet by right-clicking on it and choosing to delete it from the menu under the arrow icon (which, btw, I don't see the point of as the window even at its smallest is wide enough to hold the icon separately, but that's a different matter). It would be nice if I could remove a tweet after clicking on it as well, alongside the other options (RT, Fav, etc.). Sometimes I copy my own tweet if I tweeted too fast and realized I made a stupid typo or other mistake. So it would be nice to be able to remove it directly after copying instead of having to go back to my timeline and right-click on it.

**Comment by baedert** [comment]
yes, this is totally doable but a little weird UI-wise. You'd have to delete tweet -> go back (wherever "back" is) -> modify the history (since now going forward would lead to a tweet info page for a non-existing tweet)

**Comment by Vistaus** [comment]
Thank you so much! :smile:
