### ISSUE TITLE
Support new "longer" tweets

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#620]
[According to The Verge](http://www.theverge.com/2016/9/12/12891562/twitter-tweets-140-characters-expand-photos), it is less than a week until Twitter rolls out "longer" tweets (media attachment URLs and quoted tweets won't count to character count). It'd be good for Corebird to support this behaviour.

I don't know whether Twitter has any proper API docs about this. The original [blog post](https://blog.twitter.com/express-even-more-in-140-characters) had some details.

**Comment by baedert** [comment]
There's #556  already.

**Comment by IBBoard** [comment]
I did think it was odd it wasn't already here, but I was searching "long", so didn't find it. Sorry for the noise.
