### ISSUE TITLE
Some tweets are showing up empty...

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#621]
...even though they aren't empty when I go to my timeline on the Twitter website. Also, one tweet I favorited also showed up empty even though it wasn't empty when I read it and clicked the Favorite button.

I made a screenshot to show the problem on my timeline (but like I said, it happens on my Favorites tab as well).
![screenshot from 2016-09-20 11-22-27](https://cloud.githubusercontent.com/assets/1716229/18664875/d452f7dc-7f24-11e6-9621-b0a76229df7e.png)

**Comment by baedert** [comment]
That's from the new tweet stuff which should be optional as far as I understand the docs (and it's fine here).

**Comment by baedert** [comment]
Ah now i see some breakage too, I have a fix for that to just switch to the new `extended` tweet mode but I can't merge it since the tweets appearing on the streaming connection don't contain the promised `extended_tweet` field...

**Comment by Vistaus** [comment]
Re-compiled with the latest commits and it *seems* like the issue is solved. Btw, what exactly is 'extended tweet mode'?

**Comment by baedert** [comment]
All the changes mentioned on https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by Vistaus** [comment]
Thanks! :smile: 

Since this problem seems solved, I'll close this issue.
