### ISSUE TITLE
Long tweets support?

### ISSUE THREAD

**Issue by axfelix** [baedert/corebird#622]
I know you're probably aware of it, wondering if there's a fix planned now that I'm seeing so many twitter links at the end of tweets.

**Comment by baedert** [comment]
Displaying tweets should already be fixed in master.

**Comment by arthurlogilab** [comment]
@baedert cool any ETA fora  1.3.2 that includes this ? am using the ubuntuhandbook1 PPA

**Comment by baedert** [comment]
Hmm not sure, a proper release should probably also include the changes to tweet composing, but then again I'm kind of busy right now and don't know when that will be properly finished (especially considering how error prone it is...).

**Comment by axfelix** [comment]
Just built master from the AUR package and it seems to be working fine. Thanks!

**Comment by baedert** [comment]
So https://dev.twitter.com/overview/api/upcoming-changes-to-tweets claims that "@names that auto-populate at the start of a reply Tweet will not count towards the character limit" yet I still see that in the twitter web interface and now I'm not sure whether to implement that or not.

The rest of the changes are in master and `cb-1.3` as well so if that doesn't hurt anyone I'll just make a release this weekend or something.

**Comment by baedert** [comment]
Aaaand 1.3.2 released.

**Comment by juanfra684** [comment]
@baedert the long tweets don't work on lists.

**Comment by juanfra684** [comment]
@baedert thanks!, the patch fixed the problem.

**Comment by Vistaus** [comment]
@baedert Twitter always has a strange release model when it comes to new features or changes like this. They usually update their clients in the following sequence:
1 Android and iOS
2 Web interface (and sometimes Tweetdeck, but sometimes #3)
3 BlackBerry 10 and Windows Phone
4 BlackBerry OS 7
5 MacOS
6 Windows
7 Nokia
