### ISSUE TITLE
Create more views

### ISSUE THREAD

**Issue by HumanG33k** [baedert/corebird#624]
Hello,

I think it's awesome if we have some others views for corebird.
Users could activate it in preferences. Each account could have one different.

One in order to look like tweetdeck, for community manager.
https://tweetdeck.twitter.com/

an other to look like the old G+, for more than one column. example.
twt 1 | twt 4
twt 2 | twt 5
twt 3 | twt 6

**Comment by IBBoard** [comment]
I don't think this will happen - see #443 

Although, would an extra button in the grey bar be sufficient? One view at a time, but customisable list of views?

**Comment by HumanG33k** [comment]
Ok ...

Yes a new view with it's own button can be a solution. For me the "how many columns" should depend from the display size.
 I understand the why but with the multi columns maybe more CM use it and so more people maintain it.

thx IBBoard.

**Comment by Vistaus** [comment]
I am in favor of this. I don't mind the single view at all as I don't ever maximize Corebird but people who do will get a waaaay stretched out view so multi-column (at least 2 or 3) would improve that.

**Comment by baedert** [comment]
Yeah, not gonna happen.
