### ISSUE TITLE
DMs don't word-wrap

### ISSUE THREAD

**Issue by LakesGeek** [baedert/corebird#625]
When typing a DM assuming you have Corebird in a fairly narrow view - as you type your sentence, the window gets wider and wider to accommodate your typing.

I think it would be a much better user experience for the window to remain the size the user had stretched/shrunk it to, and for the text to visually wrap instead.  (Actual line breaks in the DM would still be induced by pressing return on the keyboard)

**Comment by baedert** [comment]
GTK+ Bug: https://bugzilla.gnome.org/show_bug.cgi?id=766822
