### ISSUE TITLE
Crash related to glib error

### ISSUE THREAD

**Issue by marxistvegan** [baedert/corebird#630]
Running this on Debian Stretch and started experiencing this after an upgrade to 1.3.2

The application starts and works but eventually crashes. 

below is the output from running it from terminal to show the error. 

`(corebird:10593): Gtk-WARNING **: Theme parsing error: style.css:14:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:10593): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:10593): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

** (corebird:10593): WARNING **: Corebird.vala:353: Could not add window for account ''

** (corebird:10593): WARNING **: Twitter.vala:129: Not Found

** (corebird:10593): CRITICAL **: twitter_ref_avatar: assertion 'surface != NULL' failed

** (corebird:10593): WARNING **: Twitter.vala:129: Not Found

** (corebird:10593): CRITICAL **: twitter_ref_avatar: assertion 'surface != NULL' failed

(corebird:10593): GLib-ERROR **: /build/glib2.0-_naT8o/glib2.0-2.50.0/./glib/gmem.c:100: failed to allocate 18446744073709551594 bytes
Trace/breakpoint trap`

**Comment by baedert** [comment]
That has already been fixed via #627 and Corebird 1.3.3.
