### ISSUE TITLE
Tweet window blocks settings window

### ISSUE THREAD

**Issue by Knepherbird** [baedert/corebird#633]
If I open a tweet window (new/reply/quote) and then open the settings window (in the case that I encountered it, I wanted to look up the snippets), the settings window cannot be interacted with until the tweet window is dismissed.

**Comment by Vistaus** [comment]
I can confirm this. OTOH though, you can simply cancel the tweet as Corebird saves whatever you were typing. So just hit Ctrl+N again when you're done interacting with the settings window and finish your tweet.
