### ISSUE TITLE
Improve resume-from-suspend behaviour

### ISSUE THREAD

**Issue by axfelix** [baedert/corebird#634]
Virtually my only criticism of Corebird at this point is that it still frequently needs to be restarted after resuming from suspend -- after resuming and making the next few requests in the main timeline, it occasionally will only display a single tweet and stop making any more requests, and even without this longstanding bug, I often want to see what I've missed between suspends, and because Corebird doesn't automatically merge the static timeline history with the streaming timeline in cases like this the way that some clients do (at least, this is the way I understand this behaviour to work), I usually just wind up restarting it.

Frankly, it's not a huge issue, but it's definitely an issue (I'd be surprised if anyone else running Corebird on a machine that suspends frequently doesn't have the same behaviour). Are there any plans for this?

**Comment by baedert** [comment]
> after resuming and making the next few requests in the main timeline, it occasionally will only display a single tweet and stop making any more requests

I've never seen this before. How long was it suspended before that?

> because Corebird doesn't automatically merge the static timeline history with the streaming timeline 

What?

**Comment by axfelix** [comment]
Re: the first point -- in some cases it would've been suspended for up to a couple days.

Re: the second -- Corebird doesn't automatically "catch up" the history like some clients do when it resumes from suspend; it just starts retrieving tweets again, so that the newest tweet might be timestamped 30s ago and the second-newest several hours ago.

**Comment by baedert** [comment]
> Re: the second -- Corebird doesn't automatically "catch up" the history like some clients do when it resumes from suspend; it just starts retrieving tweets again, so that the newest tweet might be timestamped 30s ago and the second-newest several hours ago.

No, it will erase the entire timeline, load the few newest tweets and restart the stream (or at least that's what happens here and is supposed to happen).

**Comment by axfelix** [comment]
Ah, looks like I'm just having weird behaviour then!

**Comment by Vistaus** [comment]
I don't encounter said issue here. Corebird loads all tweets after resuming from suspend. It does take a couple of seconds for Corebird to load the new tweets but it does work right.

I'm using Arch Linux btw (with GNOME 3.22.x)

**Comment by Vistaus** [comment]
Do you still encounter this issue?

**Comment by baedert** [comment]
Ok, closing now. Please reopen if the problem happens again.
