### ISSUE TITLE
Retweet with comment

### ISSUE THREAD

**Issue by the-kyle** [baedert/corebird#640]
I'm not sure if this is supported in the API, but it would be awesome to have a feature where we can add an optional comment to a retweet, similar to what we can do on [twitter.com](https://twitter.com/). A pop-up could be shown that is opened when clicking the retweet button or using the keyboard shortcut that could have the optional comment in a textbox along with a retweet confirmation for those tweets where no comment is desired, or for those who simply want the extra retweet/close confirmation step.

**Comment by baedert** [comment]
That's what "quoting" is.

**Comment by the-kyle** [comment]
OK in that case, it's possible that I didn't see how to properly quote. 
My retweets don't get quoted, and I couldn't find a button or a key 
shortcut that would do this.

**Comment by baedert** [comment]
The button to quote a tweet is in the menubutton next to the other ones, both in tweet rows and in the tweet info page.

**Comment by the-kyle** [comment]
Ah OK then I did miss it. Could a key shortcut be added to quote, 
similar to the retweet tt shortcut? These shortcuts do help screen users 
like myself very much, as some of the buttons for some reason don't 
always tell us what they do. Thanks much.

**Comment by baedert** [comment]
Just added a 'q' accelerator one can use for quoting.
