### ISSUE TITLE
Deleted DM's still appear in Corebird

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#641]
I've deleted some DM's in the last few months but they all still appear in Corebird. I've attached two screenshots to compare: one of Corebird and one of the Messages hub on twitter.com.
![screenshot from 2016-10-27 17-34-15](https://cloud.githubusercontent.com/assets/1716229/19774021/fd959e74-9c6b-11e6-8489-0e08bee8f324.png)
![screenshot from 2016-10-27 17-34-09](https://cloud.githubusercontent.com/assets/1716229/19774022/fd9b29a2-9c6b-11e6-8592-86249a987af5.png)

**Comment by baedert** [comment]
There's no way to solve this; we have to download a batch of DMs initially (when you create a new account) and then later we just download all from that point on, there's no way for us to get a list of deleted DMs. The Twitter API for DMs is simply not laid out for this.

**Comment by Vistaus** [comment]
Wow, what a crap decision by Twitter to limit the API like that. Thanks for the explanation though! I hope you do implement it if Twitter ever adds this functionality to said API :v:
