### ISSUE TITLE
Reply to Direct Message causes window resize, before multiple lines of input used.

### ISSUE THREAD

**Issue by karl-denby** [baedert/corebird#643]
If corebird windows is narrow, it will grow in size as you type a dm reply, the window will get larger for each additional character until it finds a word (or a space) and can wrap down to the next line.  The result is your window size was changed by replying to a DM.

If you write a string of letters such as aaaaaaaaaaarrrrrrrrrgggggggggghhhhhh, the window will keep growing until you hit space instead of wrapping the text.

Tested on Version 1.3-1 under Arch Linux with Gnome 3.22.1

**Comment by baedert** [comment]
gtk bug: https://bugzilla.gnome.org/show_bug.cgi?id=766822
and worked-around in master: https://github.com/baedert/corebird/pull/632
