### ISSUE TITLE
Blocking and disabling retweets doesn't work anymore

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#644]
I've blocked a whole lot accounts and disabled retweets on some but everything re-appeared today and when I block them/disable retweets again, Corebird does nothing. Even if I try to block/disable retweets of new people Corebird still does nothing. Everything's fine in the official Twitter app on my phone so it's definitely a Corebird issue.

**Comment by baedert** [comment]
It seems to work just fine here.

**Comment by Vistaus** [comment]
It seems to work fine again here as well. Maybe the culprit was Twitter's 3rd party API. I'll close it for now and re-open it if it ever comes back.

**Comment by Vistaus** [comment]
It just happened again. I did notice though that when I clicked one of those accounts I previously blocked and then returned to my timeline, the account I clicked on had disappeared. But others still appeared until I clicked them and returned.
So it does seem like a Corebird issue.
