### ISSUE TITLE
Pull new translations from Transifex

### ISSUE THREAD

**Issue by akrosikam** [baedert/corebird#645]
I translated Corebird to Norwegian Bokmål (nb) on Transifex on Aug 28th. As of this post, it appears nothing has been committed into the po-folder since Jul 31st even though there have been a few (point) releases.

Is there any chance you could pull new translations from Transifex before committing the next release?

Either way, thanks for making Corebird.
I use and enjoy it daily.

**Comment by Vistaus** [comment]
The point releases didn't add any new strings to the po files. But great to see that you translated it to nb and I do hope @baedert will commit it! :smile_cat:

**Comment by baedert** [comment]
I'm not exactly planning on a 1.3.4 release...

**Comment by akrosikam** [comment]
@baedert Never mind your versioning scheme. Will you pull new translations from Transifex before the next one or not?

**Comment by baedert** [comment]
I will pull them in for 1.4 like I always do.
