### ISSUE TITLE
Switch pages with numpad support

### ISSUE THREAD

**Issue by Streppel** [baedert/corebird#646]
I'm using corebird on a 15 inch laptop with a numpad running ElementaryOS Loki 0.4.

### Expected result:
Pressing alt + num (1-7 from numpad) would switch pages just as nums from main keybard

### Actual result:
When I try to switch pages using alt + num (from numpad), nothing happens. 

Anyone else with the same problem?

**Comment by baedert** [comment]
I'm baffed about why you would use the numpad for this. It's supposed to be a simple one-handed way of switching pages.

**Comment by Vistaus** [comment]
Are you sure that you're using the right keyboard layout for numpad use? I don't have a numpad on my Chromebook but the ChromeOS specific keys work just fine in Corebird, proving that Corebird does support more than just the basic keys so numpad shouldn't be a problem then either.

**Comment by Streppel** [comment]
@baedert I see your point, and that's mostly how I use it as well. It happened to me while I was going to do a switch for the seventh page while holding alt with my left hand, so I (muscle memory) pressed 7 on the numpad. I guess we the numpad people have odd expectations sometimes, lol

@Vistaus mm, it works effectively for other applications (such as web browsers), so I think the layout is right.

This issue can be closed if it's not considered a bug, then.

**Comment by baedert** [comment]
I just thought about implementing this but I forgot I don't have a numpad on any of my computers :)
Going to close it for now then.

**Comment by Streppel** [comment]
No problem, thank you for the feedback
