### ISSUE TITLE
gspell-1 not found

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#647]
Today I've switched from Arch to Solus 1.2.1 and I'm trying to compile Corebird from git master, just like I did on Arch all the time. But for some reason something goes wrong. I've installed gspell and -devel from the Solus Software Center and autogen reports that it has found gspell so I don't know how to solve this.

```
[18:30:06] vistaus@solus /run/media/vistaus/MicroSD/Apps/corebird (0) 
> make -j3
make  all-recursive
make[1]: Entering directory '/run/media/vistaus/MicroSD/Apps/corebird'
Making all in src
make[2]: Entering directory '/run/media/vistaus/MicroSD/Apps/corebird/src'
error: Package `gspell-1' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
Makefile:1193: recipe for target 'libcorebird_la_vala.stamp' failed
make[2]: *** [libcorebird_la_vala.stamp] Error 1
make[2]: Leaving directory '/run/media/vistaus/MicroSD/Apps/corebird/src'
Makefile:436: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/run/media/vistaus/MicroSD/Apps/corebird'
Makefile:367: recipe for target 'all' failed
make: *** [all] Error 2
[18:30:09] vistaus@solus /run/media/vistaus/MicroSD/Apps/corebird (2) 
> 
```

How to solve this?

**Comment by baedert** [comment]
Does any of those gspell packages really provide a `gspell-1.0.vapi`?

**Comment by Vistaus** [comment]
Hmm, mlocate can't find such file. :confused: 

> locate gspell-1.0.vapi
[19:49:16] vistaus@solus /run/media/vistaus/MicroSD/Apps (1) 
> 

Pretty strange...

**Comment by Vistaus** [comment]
Does anyone else have a (possible) solution? I really want to use gspell in Corebird on Solus.

**Comment by baedert** [comment]
Have you tried asking in the Solus community about that?

**Comment by Vistaus** [comment]
I hadn't, but I just posted a question on the Solus Google+ page.

**Comment by Vistaus** [comment]
Solved! :)
https://plus.google.com/+HeimenStoffels/posts/eLww5RTLzQL
