### ISSUE TITLE
Error solving "api.twitter.com" (exception when there isn't Internet connection)

### ISSUE THREAD

**Issue by JuanjoSalvador** [baedert/corebird#648]
It is not a problem itself, but it's an improvement I think Corebird needs. When I lost my Internet connection, Corebird shows an error alert with a Vala exception. This could be more friendly for common users, like "Can't load Twitter now, check your connection" or something like this.

Line with error is: ComposeJob.vala:149 (when I tried to send a tweet without connection).

**Comment by baedert** [comment]
master checks for network connectivity and disables sending tweets based on that, but the problem is of course more general than that, the error dialog when the request can't be completed might not be ideal but it's a good compromise IMO.
