### ISSUE TITLE
Compose tweet character counting can't handle Wikipedia URLs

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#651]
I've just found an awkward URL that Corebird's character counting doesn't handle, but the Twitter UI does.

If a URL includes some symbols (e.g. brackets in many Wikipedia URLs) then Corebird thinks the URL has ended and everything else is text. This then takes you over the character count.

With a URL (copied and pasted from Wikipedia in Firefox) it counts -49 characters left:
    Here is a message that should be able to fit with a URL at the end but the character count doesn't like the symbols! https://en.wikipedia.org/wiki/Glob_(programming)#DOS_COMMAND.COM_and_Windows_cmd.exe

But with URL-encoded symbols it counts it correctly and says 0 characters left:
    Here is a message that should be able to fit with a URL at the end but the character count doesn't like the symbols! https://en.wikipedia.org/wiki/Glob_%29programming%29#DOS_COMMAND.COM_and_Windows_cmd.exe

Expected behaviour is that both have a "characters left" count of zero.

RFC1738 [does appear to allow brackets in URLs](http://www.blooberry.com/indexdot/html/topics/urlencoding.htm), but I can also see that it's tricky to get the right behaviour for (what about if I hadn't put the anchor on that URL? what about if the URL is at the end of a sentence that's just in brackets and so the bracket _isn't_ part of the URL?)

**Comment by Vistaus** [comment]
I can reproduce this. +1

**Comment by baedert** [comment]
Should work now
