### ISSUE TITLE
When you compose in private messages, window width increases

### ISSUE THREAD

**Issue by somenxavier** [baedert/corebird#652]
I atacched the window preview. It grows meanwhile I'm typing content
![twitter](https://cloud.githubusercontent.com/assets/89915/21082319/b6b43934-bfd9-11e6-9d1e-944c2409006c.gif)

**Comment by baedert** [comment]
gtk bug: https://bugzilla.gnome.org/show_bug.cgi?id=766822
and worked-around in master: #632

**Comment by somenxavier** [comment]
Thanks. Perhaps you could release a new version
