### ISSUE TITLE
CoreBird doesn't open browser when "Request Pin" is clicked

### ISSUE THREAD

**Issue by hiraethmarkb** [baedert/corebird#654]
Related to closed issue https://github.com/baedert/corebird/issues/470

I am seeing the same issue on XFCE (Fedora 25), following the steps outlined in the above ticket.

I have my default browser set, running exo-open --launch WebBrowser opens whatever has been set as the default (I have even tried changing it to other browsers, Firefox, Chrome, Opera, etc).

In all cases, whatever is set as default is opens when running exo-open --launch WebBrowser.

Regardless of the browser set as default, clicking 'Request Pin' returns no error either in the console or in the gui.

Corebird installed from Flatpak.

**Comment by baedert** [comment]
Do you have the `xdg-deskop-portal` and `xdg-desktop-portal-gtk` packages installed? These are needed for urls to work outside of the sandbox (also for clicking any link later).

**Comment by hiraethmarkb** [comment]
Actually, I don't. Bare with me while I give them a go.

**Comment by hiraethmarkb** [comment]
That has done the job. Thank you very much!

**Comment by baedert** [comment]
No problem. Remember that the flatpak version isn't very well tested at the moment and I'm still working on making it more sandboxed, so please file issues if you have any more problems.
