### ISSUE TITLE
Segfault when clicking “Mark read” in a notification popup

### ISSUE THREAD

**Issue by lithm** [baedert/corebird#658]
How to reproduce:

*  Have notifications for mentions enabled.
* Get mentioned.
* Click “Mark read” in the notification popup.

Output:
```
libra@kuehlschrank ~ % corebird

(corebird:4338): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(corebird:4338): Gtk-WARNING **: Theme parsing error: style.css:14:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:4338): Gtk-WARNING **: Theme parsing error: style.css:225:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:4338): Gtk-WARNING **: Theme parsing error: style.css:231:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:4338): Gtk-WARNING **: Theme parsing error: style.css:232:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:4338): GLib-GIO-WARNING **: /home/libra/.local/share/applications/defaults.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.

(corebird:4338): GLib-CRITICAL **: g_variant_unref: assertion 'value->ref_count > 0' failed
[1]    4338 segmentation fault (core dumped)  corebird
```

**Comment by baedert** [comment]
Can't reproduce, works fine with the mention from https://github.com/baedert/corebird-debug-tool/blob/master/baedert-mention.json. Does that happen with every mention for you? What version are you using?

**Comment by Vistaus** [comment]
And aside from the Corebird version, what OS (and OS version) are you using? And what DE (GNOME Shell, I assume?).

**Comment by lithm** [comment]
Yes, as far as I remember, this happens with all mentions I get. I'm only able to test this on my desktop though, and I'm currently 700 km away from it.

I'm using Arch Linux with kernel 4.8.13 and Xfce 4.12. Corebird version should be 1.3.3, the newest non-AUR version in Arch's repos.

**Comment by lithm** [comment]
Since I fixed the broken notification daemon on my laptop I'm able to reproduce the bug there as well. It runs the same OS and Xfce versions, but with corebird-git 9ea32320.

**Comment by baedert** [comment]
And the notification daemon is what? `xfce4-notifyd`?

**Comment by lithm** [comment]
Yes, version 0.3.4 to be precise.

**Comment by baedert** [comment]
Can reproduce,seems like a problem in glib's fdo notification backend.

**Comment by baedert** [comment]
Okay, bug report and patch here: https://bugzilla.gnome.org/show_bug.cgi?id=777478

**Comment by baedert** [comment]
Upstream bug is closed now.
