### ISSUE TITLE
Blurry icon in app cycle window

### ISSUE THREAD

**Issue by PaulsBarkans** [baedert/corebird#659]
When pressing alt+tab to fast swith apps, Corebird's icon appears low quality.

Adding `StartupWMClass=corebird` to the .desktop file solves the problem, although I'm not sure that this is the best solution.

Desktop: Cinnamon 3.2.7  
Distro: Linux Mint 18.1 Serena

![corebird-alt-tab](https://cloud.githubusercontent.com/assets/1485739/21580844/6a0b2f9a-d01c-11e6-8cc9-7af15be3ffcf.png)

**Comment by baedert** [comment]
Impossible for me to say why your app switcher decides to use and upscale that icon version (apart from the fact that I'm not sure this is the one I ship myself and not the version from another icon theme...).

**Comment by bil-elmoussaoui** [comment]
@baedert i think the best solution is to add StartupWMClass, i know it shouldn't be used anymore but some desktop env still uses it to detect the running application and assign it to the correct destkop file

**Comment by baedert** [comment]
It looks like it already knows what icon to use, it just picks the wrong size. Where is the upstream bug report against whatever cinnamon component that is?

**Comment by PaulsBarkans** [comment]
I've [reported the issue](https://github.com/linuxmint/Cinnamon/issues/6205) to Cinnamon maintainers.

**Comment by Vistaus** [comment]
Seems like someone else also reported it to Cinnamon (see the linked bug report) on Manjaro, so I think it's safe to say that it's a Cinnamon issue rather than a Corebird issue.
