### ISSUE TITLE
GStreamer plugin when start Corebird

### ISSUE THREAD

**Issue by JuanjoSalvador** [baedert/corebird#660]
Here is the error log. I'm using Corebird when Debian testing and GNOME 3.21

```
ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstclutter-3.0.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```

**Comment by baedert** [comment]
That plugin has nothing to do with corebird of course. Does `gst-launch-1.0 fakesrc ! gtksink` work? Otherwise you'd have to file a bug against the distro package of whatever provides `libgstclutter-3.0.so` or just remove that file (if nothing needs it...).

**Comment by JuanjoSalvador** [comment]
`libgstclutter-3.0.so` is provided by GStreamer, so I think there is an issue with that... I've reinstalled the package (`gstreamer-1.0` on Debian repos) and still doen't work :(

**Comment by baedert** [comment]
Yeah but I just can't help you with that at all. Again, try gst-launch-1.0 or any other way of reproducing that problem without corebird (which should work since it's not using that at all...) and report a bug to gstreamer or the maintainer of the debian package.

**Comment by JuanjoSalvador** [comment]
Okey, I just fixed it.

This is my workaround:

* Remove /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstclutter.so
* Download gstreamer-1.0 deb package and extract files. I use this package from Ubuntu repos
> http://packages.ubuntu.com/trusty/amd64/gstreamer1.0-clutter
* Instead of install the package, extract the files into `gstreamer1.0-clutter.deb/data.tar.xz`. You will find some folders.
* Inside the folders there is a `libgstclutter.so` file. Place it into `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/`

And fixed!
