### ISSUE TITLE
socks5代理

### ISSUE THREAD

**Issue by omaidb** [baedert/corebird#661]
希望开发组有中国大陆的成员，那么您看到这个iss一定会明白我在说什么。
这个程序很好用我很喜欢，但是对于中国大陆用户来说，用socks5代理已经是必备和常态，希望下一版本更新时可以使用socks5代理哦。谢谢。
如果有翻译组的人的话，希望能将需求翻译成英文。学渣拜谢。

**Comment by baedert** [comment]
English please...

**Comment by omaidb** [comment]
Please try to use machine translation to read this article


在 2017年01月03日 17:34, baedert 写道:
> English please...

**Comment by Vistaus** [comment]
@baedert As far as I understand from the machine translation (although I agree that @omaidb should've posted it using machine translation himself), he asks you to add support for socks5 proxy.

> This program is very easy to use I like, but for users in mainland China, with socks5 proxy is essential and normal, hope that the next version can be used to update socks5 agent Oh. Thank you.

**Comment by baedert** [comment]
So it's a duplicate of #144 then?

**Comment by Vistaus** [comment]
@baedert #144 seems to be the same indeed.

**Comment by baedert** [comment]
ok, thanks.
