### ISSUE TITLE
1.4 release compile error on ubuntu 16.04

### ISSUE THREAD

**Issue by PandaJim** [baedert/corebird#662]
Hi, I'm trying to build the new release into PPA, successfully compiled Corebird 1.4 on Ubuntu 16.10, but failed on Ubuntu 16.04.

* Ubuntu 16.04 with GTK 3.18.9, 
* Valac 0.34.4 (via Vala PPA)
* --disable-spellcheck

Not sure what's the problem, may be this line:

    BadgeRadioButton.c:(.text+0x25d): undefined reference to `gtk_widget_set_focus_on_click'

And here's the link to the build log:

https://launchpadlibrarian.net/301477914/buildlog_ubuntu-xenial-i386.corebird_1.4-0build3~ubuntu16.04_BUILDING.txt.gz

**Comment by baedert** [comment]
See https://github.com/baedert/corebird/issues/531. Your valac generates code your gtk+ version can't handle.

**Comment by PandaJim** [comment]
Hi, I've tried to build with default GTK and valac versions:

* Ubuntu 16.04 with the default GTK 3.18.9
* valac 0.30 

but still get problems:

    SearchPage.vala:68.34-68.37: warning: Argument 2: Cannot pass null to non-null parameter type
    tweet_list.bind_model (null, null);
                                 ^^^^
    widgets/FollowButton.vala:48.5-48.26: error: Property `Gtk.Stack.interpolate_size' is read-only
    stack.interpolate_size = true;
    ^^^^^^^^^^^^^^^^^^^^^^

**Comment by PandaJim** [comment]
And in Ubuntu 16.10 failed to build with spellcheck enabled,

* gtk 3.20 (default)
* valac 0.32 (default)
* spellcheck enabled (default)

Error:

    widgets/CompletionTextView.vala:103.5-103.40: error: The name `set_enable_language_menu' does not exist in the context of `Gspell.TextView'
    gspell_view.set_enable_language_menu (true);

**Comment by baedert** [comment]
So I guess you only have gspell < 1.2 in both versions?

The interpolate_size error doesn't make sense to me, `gtk_stack_set_interpolate_size` existed since 3.18. I wonder if the binding is just broken and using `set_interpolate_size` instead of the property syntax would work. Can you paste the `/usr/share/vala-0.30/vapi/gtk+-3.0.vapi`?

**Comment by PandaJim** [comment]
Yes, used gspell 1.0.3 in the 16.10 build. But disabled spellcheck in 16.04 since it's not available by default in Ubuntu 16.04's main archive.

See the attached file:

[gtk+-3.0.vapi.zip](https://github.com/baedert/corebird/files/691444/gtk.-3.0.vapi.zip)

**Comment by baedert** [comment]
Can you confirm that these commits fix the issue before I do a 1.4.1?

**Comment by PandaJim** [comment]
Thank you. The commits work!

**Comment by baedert** [comment]
Ok I released 1.4.1 with these changes, thanks for reporting back!
