### ISSUE TITLE
SIGSEGV from Cairo surface

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#665]
I managed to reliably crash Corebird a few times due to an odd tweet. It appears to be due to some kind of Cairo issue.

Steps:
1) Follow SwiftOnSecurity/find https://twitter.com/SwiftOnSecurity/status/818486118467440640
2) Referenced tweet doesn't show (it did at first, but it doesn't now since first crash)
3) Click referenced tweet link to show just the NinjaEconomics tweet - https://twitter.com/NinjaEconomics/status/818481397409071105. Tweet loads correctly and shows two images.
4) Click back button
5) Click referenced tweet link again
6) Click back button

Expected behaviour: Get back to main list

Actual behaviour:

    Thread 1 "corebird" received signal SIGSEGV, Segmentation fault.
    INT_cairo_surface_reference (surface=surface@entry=0x7ffff4cc1d80 <g_free>)
        at cairo-surface.c:933

I'm trying to diagnose this with debug symbols.

Running 1.4.1 (custom build from Git Master)

**Comment by IBBoard** [comment]
[CrashStackTrace.txt](https://github.com/baedert/corebird/files/694009/CrashStackTrace.txt) - there's a lot there and it all looks like GTK that I saw. Hopefully it is useful.

**Comment by baedert** [comment]
That ^ commit fixes the crash for me but I've seen a different stack trace than you. The bug should always surface (*hah*) when a tweet link gets clicked (not a tweet in a timeline) and that tweet has media attached. Going back will then free the tweet(and its media) and the media button has an unowned reference to an invalid object.

**Comment by Vistaus** [comment]
I just followed the steps and I successfully got back to the main list, no crash here.
Using Corebird from git master on Solus (Linux).

**Comment by IBBoard** [comment]
Got this built and installed at last. Double-clicked a tweet quoting a tweet with an image, clicked the tweet link, clicked back and it didn't crash. I'll give it a day, but I think it is fixed.

**Comment by IBBoard** [comment]
Seems fine. Thanks.
