### ISSUE TITLE
Feed Not Refreshing When Very Busy

### ISSUE THREAD

**Issue by paulmadore** [baedert/corebird#669]
I got bombarded on Twitter yesterday because of a tweet about fascism. 73 notifications went to my text messages on my phone, but only about 20 of them made it to Corebird. I noticed it wasn't updating them at all. Haven't determined if this could be related to my local settings or not. Investigating on my fork during this week sometime.

**Comment by Vistaus** [comment]
That probably has something to do with the rate-limited API requests: https://github.com/baedert/corebird/issues/599#issuecomment-237181984

**Comment by baedert** [comment]
We are not poling anywhere, I assume "notifications" here means replies/mentions, and those come from the streaming API (which we can't control either, it works or it doesn't).

**Comment by paulmadore** [comment]
This is also my conclusion, so I'm closing this issue.
