### ISSUE TITLE
Missing icon on Gnome when building from source

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#670]
When building corebird from latest git master the icon for the corebird desktop entry is missing. Refreshing the icon cache doesn't fix this
![bildschirmfoto von 2017-01-29 12-44-54](https://cloud.githubusercontent.com/assets/1418818/22403739/ee599d76-e620-11e6-8210-c6d71a422bc9.png)

**Comment by Vistaus** [comment]
Can't reproduce that here on Solus Budgie (which is also based on GTK). What distro are you using?

**Comment by HeikoAdams** [comment]
Fedora 25 with Gnome 3.22

**Comment by baedert** [comment]
Does `ls /usr/share/icons/hicolor/128x128/apps | grep corebird` list anything?

**Comment by HeikoAdams** [comment]
```
$ ls /usr/share/icons/hicolor/128x128/apps | grep corebird
corebird.png
```

**Comment by Vistaus** [comment]
Strange. I suggest installing Menulibre and changing the icon yourself using that app.

**Comment by bil-elmoussaoui** [comment]
Maybe the icon cache was not updated?

**Comment by baedert** [comment]
@bil-elmoussaoui "refreshing the icon cache doesn't fix this" from the inital report

@HeikoAdams have you installed the flatpak version in between? I've seen the same problem in that case but iirc a logout/login cycle fixed it.

**Comment by HeikoAdams** [comment]
Okay guys, I think I found why the icon is missing.
The desktop file contains the following line
`Icon[de]=Corebird`
but the line should be
`Icon[de]=corebird`

**Comment by baedert** [comment]
> But since the icon is not language-specific there could also be just one general icon specification
Icon=corebird

That's a problem with the desktop file specification currently. There's a translator comment right above that entry telling translators to not translate it but until not so long ago that comment didn't show up in transifex and the German icon name got translated.

I've updated the translations in master now so that shouldn't be a problem anymore.
