### ISSUE TITLE
No easy way to switch beetween multiple images

### ISSUE THREAD

**Issue by medeotl** [baedert/corebird#671]
Consider a tweet with 2+ images

Click on first image.

If I use the mouse, I can scroll the image (usually you have to scroll images, in particular vertical one) but I can't switch (with the mouse) to the next one

If I use keyboard, I can easily switch images with cursor keys, but there's no way to scroll images (with keyboard)

**Comment by Vistaus** [comment]
Confirmed.

**Comment by baedert** [comment]
Added some next/previous buttons in master

**Comment by Vistaus** [comment]
Thanks, @baedert ! It works awesome! Although on some photos the buttons tend to be a little bit too transparent, making them a little harder to spot. But overall they work fine :smile:

**Comment by baedert** [comment]
With what theme?

![screenshot from 2017-03-13 17-15-15](https://cloud.githubusercontent.com/assets/887764/23863541/60828848-0810-11e7-9e66-301216a9175b.png)

**Comment by Vistaus** [comment]
@baedert Deepin GTK theme, which I use on Solus (Budgie). Maybe it's a theme bug rather than a Corebird bug?

**Comment by baedert** [comment]
Probably, `.osd` should work across backgrounds IMO, it's used bei eog and totem as well to overlay buttons on random videos/images.

**Comment by Vistaus** [comment]
Your latest commit does seem to have improved the visibility of the buttons.

**Comment by baedert** [comment]
Well yeah but only whether they are at all visible and not whether they are good so see on dark backgrounds.
Anyway, I guess this bug is fixed.
