### ISSUE TITLE
Some Tweets in Timeline are Non-Clickable, i.e. Cannot be Interacted With

### ISSUE THREAD

**Issue by prometx** [baedert/corebird#676]
There are tweets from some followed accounts that appear in the timeline, but all links are "dead" when moused over or clicked on. Has anyone else experienced this? This is on Ubuntu 16.04 (amd64).

**Comment by baedert** [comment]
That's how deleted tweets are indicated.

**Comment by prometx** [comment]
Ahhh, roger that...thanks!
