### ISSUE TITLE
Can't close media dialog anymore by clicking outside of the window

### ISSUE THREAD

**Issue by baedert** [baedert/corebird#677]
Regression from porting to `GtkGesture`.

**Comment by Vistaus** [comment]
I can't reproduce this anymore in latest git master whereas I could reproduce this earlier this year. So I think this is fixed, no?

**Comment by baedert** [comment]
It's not fixed but the fix is non-trivial and nobody seems to care a lot and the feature is only "important" for smaller images where clicking inside the actual media dialog is more work, so I'm just closing this anyway.

**Comment by Vistaus** [comment]
Oh, but if it's not fixed, then how come I don't experience this issue anymore then?

**Comment by baedert** [comment]
No idea. I can reproduce it perfectly fine here.
