### ISSUE TITLE
Quoted tweets not included in mentions

### ISSUE THREAD

**Issue by lowescott** [baedert/corebird#680]
I've noted that Corebird does not include in the Mentions view tweets that include a link to one of my tweets (as a form of quoting tweets). Is this expected behavior?

**Comment by baedert** [comment]
> Is this expected behavior?

Yes, the mentions tab is made up of entries from `1.1/statuses/mentions_timeline.json` as well as the mentions that appear on the streaming connection.

**Comment by lowescott** [comment]
@baedert Thanks. I know that some other clients (on other platforms) include these tweets in the Mentions tab. Has there been any consideration of adding this as a feature? (I don't know the level of effort that would be required.)

**Comment by baedert** [comment]
> Has there been any consideration of adding this as a feature? 

No, but it also hasn't been filed as a bug report yet. There's no way to query the quoted tweets of a user from the Twitter API (other than those from people you follow, which appear on the streaming connection). Therefore, I think it's the same situation as #317.

**Comment by lowescott** [comment]
@baedert Thanks for the reply. I mentioned it here only because some Twitter clients on other platforms have this feature. Since there's no API to get that information from Twitter (and you'd have to resort to one of the methods listed in #317), I'll go ahead and close this issue.
