### ISSUE TITLE
Corebird icon does not show up in some docks

### ISSUE THREAD

**Issue by simonszu** [baedert/corebird#682]
Hi, 
i am using Docky to have a mac OS-like dock experience. However, Corebird does not show up in Docky with its icon, but rather with a default application icon. It seems it has some missing resources. 
The terminal output of docky looks like this:
```
[Info  18:28:17.900] [DrawingService] Could not find 'Corebird', using fallbackof 'application-default-icon'.
[Info  18:28:17.900] [DrawingService] Could not find 'application-default-icon', using fallback of 'application-x-executable'.
[Info  18:28:17.916] [DrawingService] Could not find 'Corebird', using fallbackof 'application-default-icon'.
[Info  18:28:17.916] [DrawingService] Could not find 'application-default-icon', using fallback of 'application-x-executable'.
```

So i tried another dock application, namely DockbarX, which shows Corebird's icon on the default icon-size which is around 30px - way too small. I increaded the size, and Corebird's icon was replaced by a default icon as well. The terminal output of DockbarX looks like this:

```
(corebird:5748): Gtk-WARNING **: Theme parsing error: style.css:14:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:5748): Gtk-WARNING **: Theme parsing error: style.css:225:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:5748): Gtk-WARNING **: Theme parsing error: style.css:231:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:5748): Gtk-WARNING **: Theme parsing error: style.css:232:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:5748): Gtk-WARNING **: Theme parsing error: style.css:237:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
```
I am using all these applications on xfce4 which should use gtk3

**Comment by Vistaus** [comment]
Which distro do you use?

**Comment by simonszu** [comment]
Arch Linux.

**Comment by baedert** [comment]
German locale?

**Comment by Vistaus** [comment]
Hmm, sounds like it's related to https://github.com/baedert/corebird/issues/670

**Comment by simonszu** [comment]
@baedert Yes, german locale. 
@Vistaus Yeah, sounds related - but @baedert did fix #670 and i am using 1.4.2-2 which looks like it is the most recent version - until the fix of #670 didn't make it to the latest release yet.

**Comment by baedert** [comment]
Nope, that's not in 1.4.2. That's why your console output shows it's trying to load an icon called `Corebird` instead of `corebird`.

**Comment by simonszu** [comment]
Okay. I'll wait for the next release then. Thanks for helping.
