### ISSUE TITLE
image and video splitted on two monitor system

### ISSUE THREAD

**Issue by kimifish** [baedert/corebird#683]
When opening image or video, preview window appears strictly in the middle of virtual screen space, thus splitted between two monitors. Very uncomfortable to view anything, especially considering that there is no chance to move it.

**Comment by baedert** [comment]
Sound a lot like something your window manager is doing. It appears centered on the window it's transient to.

**Comment by kimifish** [comment]
Yep, sorry. Fixed in compiz settings.
