### ISSUE TITLE
Vine preview/view fails

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#687]
I think Vine have changed something in their UI, so the preview for Vine is always a [picture of the Vine app](https://vine.co/assets/images/meta/vine_screencap-0b4ef888c2882624abcca774862cde77.png) (not the video) and playing the video fails with "Error: Could not get real URL".

This is mainly bad behaviour on Vine's part, because they've kept the `og:image` meta tag but replaced the useful content with something rubbish.

I've only just poked this and not investigated enough to see if we can work around it, but an initial skim suggests not (at least not trivially).

**Comment by Vistaus** [comment]
Something has changed for sure... 2 months ago: https://en.wikipedia.org/wiki/Vine_(service)#Discontinuation_of_Vine_service

**Comment by baedert** [comment]
> I've only just poked this and not investigated enough to see if we can work around it, but an initial skim suggests not (at least not trivially).

Same here and I don't have a huge problem with removing vine support.

**Comment by IBBoard** [comment]
@Vistaus Yes, Vine announced they were shutting down. They didn't announce that they were altering their HTML to still *pretend* to give you a thumbnail that's actually a picture of the Vine app, and to remove the URL from the meta tags (using the Facebook OpenGraph standard, IIRC).

Removing Vine support seems like the best way to go, but this is a good example of why I wrote #457 - when the "click preview to watch Vine" functionality broke, I wouldn't have been able to see the Vine link from the tweet (without double-clicking on it, which just seems like unnecessary extra effort)
