### ISSUE TITLE
Favovites, replies and RT's not showing sometimes

### ISSUE THREAD

**Issue by kajzersoze** [baedert/corebird#689]
There's a problem not being able to see replies, favs and RT's after just few minutes.
When that happens you can't fav a tweet as well.
You can, if you right click on a tweet and then fav it, then it shows 0 RTs and 1 Fav (in reality there are more)
While I'm at it, there's also one more problem, sometimes when you leave it open for some time, it auto-scroll to the top (auto scroll is disabled in settings) and when you scroll down only few tweets are shown (no more than 10) and you can't go any further. The only way out of that is to exit from corebird and start it again.

**Comment by Vistaus** [comment]
I haven't really experienced this yet in Corebird but I do frequently experience this in the official Twitter client on my phone (and I know people on other OS's have complained about it as well with the official client so it really seems like a Twitter bug).

**Comment by kajzersoze** [comment]
Can you please link to some discussion about that ?
I tried to google it but wasn't able to find a single one.

**Comment by baedert** [comment]
For the record, this used to happen to me too, but I never figured out why (and writing a minimal test case didn't help). It affected all rest API calls, but not the streaming connection. I could not find any trigger other than just waiting for it to happen. It eventually stopped without me doing anything about it and I concluded it was probably a temporary server-side problem. See also e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1325853

**Comment by kajzersoze** [comment]
Yeah interesting indeed, actually this issue made me start writing my own client from scratch.
REST API only for now, I'm not getting this problem there. I'll try with streaming api soon.
Also, I had official tweetdeck client open for many hours and it didn't happen once.
I would rule out temporary server-side problem as this happens **every time** after just few minutes, then you exit from it, start it again and it seems like never ending.
Kinda hard to imagine that kind of server problems, especially when nobody seems to talk about it anywhere.
Not trying to say that there's something wrong with Corebird regarding that problem, I'm just not sure at this point.

**Comment by baedert** [comment]
> Also, I had official tweetdeck client open for many hours and it didn't happen once.

Stop using tweetdeck as a comparison. It's owned by Twitter.

> I would rule out temporary server-side problem as this happens every time after just few >minutes, then you exit from it, start it again and it seems like never ending.

"Temporary" meant a few months in my case.

>Kinda hard to imagine that kind of server problems, especially when nobody seems to talk
>about it anywhere.

That's what I thought as well.

> Not trying to say that there's something wrong with Corebird regarding that problem

That's kinda exactly what you're saying. It could very well be a bug in corebird or librest or even libsoup, but so far the only error message I've seen is a connection time out after I-don't-know-how-long after issuing one of the rest api calls in a situation like that. And nowadays I can't reproduce anymore anyway.

**Comment by baedert** [comment]
Yeah so what version of all the dependencies are you using?

**Comment by kajzersoze** [comment]
sqlite - 3.16.2
glib - 2.48.2
json-glib - 1.2.2
libgee - 0.18.1
libsoup - 2.54.1
rest - 0.8.0
vala - 0.34.7

**Comment by baedert** [comment]
The only relevant versions that differ from my system version are libsoup and glib (gee is not a dependency btw). I can't reproduce the issue so far, after letting it run for several ours (and several times).

**Comment by kajzersoze** [comment]
It's probably just me for some weird reason so I'm gonna close this.
