### ISSUE TITLE
inflates the memory used by corebird, well start with 150 Mb, then 240 Mb, then 500 Mb, ultimately 1.9 Gb why not recycled news.

### ISSUE THREAD

**Issue by ijann** [baedert/corebird#692]
Okay app, but inflates too much memory, once get to have 1.9 Gbs, that seems absurd, but you need a garbage collector for the news in the timeline, I'm from android, there is known as recyclerview which list shows what is on the screen, the rest is recycled both top and bottom, not is as it will be in python, if there will be something for them to implement it here in the application, thus will not inflate memory.

As the application does not give me problems, not closes and only the problem is memory, I use archlinux x86.

just like not yet mastered python mention that someone who supports this app can see what can do, since their experience is better than the experience I have, thank you.

**Comment by baedert** [comment]
#314 I guess.
