### ISSUE TITLE
Support new "@reply is in header, not body" messages

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#693]
Twitter have announced their new ["@reply no longer counts for 140 characters" 'feature'](https://blog.twitter.com/2017/now-on-twitter-140-characters-for-your-replies). Corebird already supports "images and quoted URLs don't count in 140 characters", so it'd be good to do the same for the @-replies.

Hopefully there is some better technical documentation on what the rules are and how the new JSON message is structured than [this](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets#what-does-this-look-like).

I don't know what a usable UI might look like, though.

I don't know whether this needs to be two separate tasks either - one for sending and one for displaying in the timeline.

**Comment by baedert** [comment]
It seems like it's all "backwards compatible" so far, so nothing breaks really. I couldn't really figure out a way of sending a tweet with lots of people mentioned however, just prepending the mentions to the tweet doesn't seem to work, which I would've expected.

> I don't know whether this needs to be two separate tasks either - one for sending and one for displaying in the timeline.

yes, just displaying them in the timeline shouldn't be *that* hard, worst case is just using a label saying "in reply to <name>, <name>, ..." but dunno if we want to ellipsize or wrap that one. Or where to put it, or if there should be an icon next to it, etc.

For composing we'd need the same thing but editable, so about a million times worse and all in a supposedly simple and small window.

**Comment by baedert** [comment]
So, it's actually mentioned on https://dev.twitter.com/overview/api/upcoming-changes-to-tweets how this works:

>the REST API endpoints that create new Tweets (statuses/update) will accept a new boolean parameter when a Tweet is sent as a reply to a conversation: auto_populate_reply_metadata (true to enable, false to disable, false being the default). The existing in_reply_to_status_id must also be set. The leading @mentions will subsequently be looked up from the original Tweet, and added to the new Tweet from there. In cases where the original Tweet has been deleted, the reply will fail. This is a change to existing behaviour, where it has been possible to reply to a deleted Tweet ID.

>For older clients that are not updated for the auto_populate_reply_metadata option, mentions will continue to be included in the body of the Tweet and the server will decide on how to render the new Tweet.

>The auto_populate_reply_metadata option will append @mentions into the metadata as a reply chain grows, until the limit on @mentions is reached. In order to edit down the list of handles, an additional option, exclude_reply_user_ids, will enable specific IDs (apart from the leading one) to be excluded from a reply. This parameter is an optional, comma-separated list of user ids which will be removed from the server-generated @-mentions prefix.

And I'm working on it in the `replies` branch.

**Comment by IBBoard** [comment]
I'm running the `replies` branch locally for testing.

At least there are some docs. Seems quite clear (although the client end won't be as pretty as their simple server-side/API description!).

One thought so far: Is it possible to make replies more obvious? I know there's the icon in the top-left, but the new "don't see usernames" version makes it easier to miss compared to "@-me blah blah blah". I'm not sure what would work, though. Maybe an equivalent to the "RT by" line?

**Comment by baedert** [comment]
> Maybe an equivalent to the "RT by" line?

That's the plan, yes. Or something similar, dunno.

**Comment by IBBoard** [comment]
I'll have to get used to the new layout, but it looks readable with the "Replying to" line.

I know it's a WIP, but two quick things I noticed as of b2054e7c:
 * Old-style replies still say "Replying to" but don't show a name
 * The "Replying to" doesn't wrap, which effectively re-introduces #514 - and with up to 50 users, it could be bad!
 * It seems to show "Replying to [self]" quite a bit, when the threading shows it is a reply to someone else and Twitter web shows "replying to [someone else]" (e.g. https://twitter.com/_r00k_/status/853989606429216770 incorrectly shows "replying to _r00k_", but the reply at https://twitter.com/hacks4pancakes/status/853989706819936256 shows the correct "replying" line)

And a couple of thoughts:
 * Is it worth keeping the old icon as well? It helps cover the "old reply" situation without having to make up a bit of filler text
 * If a user is only replying only to themselves (threading tweets) is it better to treat it like an old reply and ignore the "Replying to" line?

**Comment by baedert** [comment]
Ah perfect, some tweets have  a `display_range` that starts after the first mention, but that mention is not part of the `entities`. Great.

**Comment by baedert** [comment]
@IBBoard 

> Old-style replies still say "Replying to" but don't show a name

Should be fixed.

> The "Replying to" doesn't wrap, which effectively re-introduces #514 - and with up to 50 users, it could be bad!

I don't really see a point in listing all of them (of course), but so far I think it's not really useful to see even more than 3 of the users a tweet replies to. The current approach shows up to 2 and then starts with showing just the user directly replied to and then "and X others".

> It seems to show "Replying to [self]" quite a bit, when the threading shows it is a reply to someone else and Twitter web shows "replying to [someone else]" (e.g. https://twitter.com/_r00k_/status/853989606429216770 incorrectly shows "replying to r00k", but the reply at https://twitter.com/hacks4pancakes/status/853989706819936256 shows the correct "replying" line)

Pretty sure that's also fixed (and I think I looked at that tweet specifically yesterday, to make sure)

> Is it worth keeping the old icon as well? It helps cover the "old reply" situation without having to make up a bit of filler text

Not sure about that. We can't put it to the left of the label with its current position and it looks kind of disconnected to the label in the upper right.

> If a user is only replying only to themselves (threading tweets) is it better to treat it like an old reply and ignore the "Replying to" line?

I don't think that makes sense. It could make sense so treat self-replies special in some sense and instead use "replying to themselves" or something similar but I'm not sure how well that would work.

I think I currently just want to focus on getting something working well without too many experiments so I can make an already overdue release.

**Comment by IBBoard** [comment]
Just updated and rebuilt. Looking good so far 😊

>I don't really see a point in listing all of them (of course), but so far I think it's not really useful to see even more than 3 of the users a tweet replies to. The current approach shows up to 2 and then starts with showing just the user directly replied to and then "and X others".

Agree. Hopefully that keeps it short enough to not cause wrapping issues. It _might_ be useful to have a way to see all of the names (maybe on the single-tweet view?) in some situations, but it'll probably just be noise 99% of the time.

Interestingly, the new behaviour means that https://twitter.com/hacks4pancakes/status/854399651805638656 shows "Replying to EFF and 2 others" but Twitter web UI just shows a threading line (possibly because I follow both EFF and Lesley). Probably too much of a niche case to care about.

>> Is it worth keeping the old icon as well? It helps cover the "old reply" situation without having to make up a bit of filler text
>
>Not sure about that. We can't put it to the left of the label with its current position and it looks kind of disconnected to the label in the upper right.

There's still a "RTed" icon next to the time stamp. I thought it might fit to leave the "it's a reply" icon there. It would look detached from the "replying to", but it'd keep a consistent old marker that's (potentially) easier to spot.

>>    If a user is only replying only to themselves (threading tweets) is it better to treat it like an old reply and ignore the "Replying to" line?
>
> I don't think that makes sense. It could make sense so treat self-replies special in some sense and instead use "replying to themselves" or something similar but I'm not sure how well that would work.

That suggestion was on the (seemingly incorrect) assumption that old-replies got "Replying to" with no name because it couldn't be determined, and that it'd be possible to use the old "reply" icon.

I completely understand about getting something working rather than experimenting. Better to get a base version out and get comments back.

**Comment by IBBoard** [comment]
Actually, I found a bad tweet: https://twitter.com/Ben_garrod/status/853990508326252550

Shows as "Replying to jjdesmond", but tweet data (and Twitter WebUI) has it also replying to _UBRAS_  and seven others. Also, the link doesn't appear to be a link for some reason. I'm guessing it may be related, as other tweets show links okay.

(Aside: I'm not sure what the person silhouette and list of names is about on https://twitter.com/jjdesmond/status/853925036696141824, below the photo - some additional kind of person-tagging?)

**Comment by baedert** [comment]
> Interestingly, the new behaviour means that https://twitter.com/hacks4pancakes/status/854399651805638656 shows "Replying to EFF and 2 others" but Twitter web UI just shows a threading line (possibly because I follow both EFF and Lesley). Probably too much of a niche case to care about.

Yeah, I see "eff and 2 others" in corebird and all 3 screen names on twitter.com when clicking that link.

> Shows as "Replying to jjdesmond", but tweet data (and Twitter WebUI) has it also replying to UBRAS and seven others.

I'll look into that one. It shows up here as "replyinh to jjdesmond and 9 others" but the number seems off anyway.

The broken links are a known problem, looking into that one as well.

**Comment by baedert** [comment]
Okay that tweet now shows up as "replying to jjdesmond and 8 others", so the number should be fine and the link looks good as well.

thanks for testing btw!

**Comment by baedert** [comment]
I'm currently not sure which of these 3 to use, they all look kinda weird to me or interrupt the reading flow I think.

![screenshot from 2017-04-19 11-10-41](https://cloud.githubusercontent.com/assets/887764/25172549/ae3d7fae-24f1-11e7-9b87-f287b83dabc8.png)
![screenshot from 2017-04-19 11-12-07](https://cloud.githubusercontent.com/assets/887764/25172550/ae45655c-24f1-11e7-9cfb-5a73a66b3276.png)
![screenshot from 2017-04-19 11-16-14](https://cloud.githubusercontent.com/assets/887764/25172551/ae4925c0-24f1-11e7-88d9-eaa4031a6408.png)

**Comment by IBBoard** [comment]
Twitter goes for "below the username", but then they put RT *above* the username so they're not the best example!

Personally, I think the third one, as it is now. The grey (but clickable) names lose just enough focus and it keeps a moderate amount of natural flow to it: "Person (Replying to Other Person): blah blah blah" (a bit like stage directions). The author name is most prominent, then the reply context is there if necessary, and then the content.

**Comment by baedert** [comment]
Just merged this into master, let's go  from there. I'm not sure about the TweetInfoPage view. Also, if anyone sees a tweet that mentions *a lot* of people to test this with, please post a link.

**Comment by IBBoard** [comment]
I've built and published it for openSUSE 😊

With the TweetInfoPage, I think it looks fine for one line of names, but would it be better to top-align the "replies" icon rather than middle-aligning? It just looks a little odd sat next to the middle of three lines of usernames. Also, could the names be clickable, like in the main timeline?

I can't think of anything better to do with the list of handles. Putting it above keeps consistency with the rest of the UI, and there's not quite enough space to indent it beside the avatar (plus it'd look odd with a large margin when there are multiple lines!)

**Comment by baedert** [comment]
> With the TweetInfoPage, I think it looks fine for one line of names, but would it be better to top-align the "replies" icon rather than middle-aligning?

Eh yes, I couldn't even find one with that many.

> Also, could the names be clickable, like in the main timeline?

That's the plan

**Comment by IBBoard** [comment]
Replies to StopFundingHate tweets where they call out companies seem to be my best source. Other than that then I tend to only get one or two handles in a tweet.

e.g. https://twitter.com/pwsimerimiaw/status/855753815240441856

**Comment by IBBoard** [comment]
I just noticed - quoted tweets don't show the "Replying to" line in the main timeline. There's a limit on how many usernames will show, but will it make the UI too busy to show the "Replying to…" context there as well, somehow?

**Comment by baedert** [comment]
That's what I'm currently looking into, it's also broken for retweets of replies.

**Comment by baedert** [comment]
Okay, retweets of replies should be fixed, I reworked the entire reply handling to be per-`CbMiniTweet`, so showing a reply label for quotes should at least be easy.

**Comment by baedert** [comment]
Ookay, quoted tweets now also get their reply label. So all the reply issues *should* be fixed now, leaving this open for some time so people can report remaining problems.

**Comment by IBBoard** [comment]
Just poking around with it now. First things I've noticed (possibly all related) are that
 a) archillinks tweets seem to have space where the "replying to" should go, but not text
 b) the archillect tweet that archillinks quotes/references also seems to have a space but no text (plus, it isn't actually a reply to anything)
 c) double-clicking an archillinks tweet crashes Corebird (segfault). Other tweets show TweetInfoPage correctly

Trying to explore/understand/fix at the moment. Hopefully I'll have more info soon (or maybe tomorrow morning)

**Comment by baedert** [comment]
https://github.com/baedert/corebird/commit/6396a95c2e147949a77b97e854c455df38957c58 Should fix the missing reply text. Downside is that the .@replyname is not a link now.

**Comment by IBBoard** [comment]
Seems to fix a and c. Maybe it's just me, but b still seems to be there, though - there's more space between Archillect name and the picture when quoted by Archillinks than when viewing the Archillect tweet unquoted (https://twitter.com/archillect/status/858048184232357888 has the image just under name as a TweetListEntry item, but when quoted by https://twitter.com/archillinks/status/858048186862141443 as a TweetListEntry item then there's a gap about wide enough for a reply line)

Just noticed that TweetInfoPage seems to miss the space after the "and". Seems to be missing the `.append_c (' ')` after line 491 adds the translated "and".

**Comment by baedert** [comment]
That space is just the result of quoting a tweet with media attached but without any text it seems. Should've looked the exact same before the reply work.

**Comment by baedert** [comment]
Ok, the missing reply link with .@username replies should be fixed and the space from the empty quote tweet text label should be gone.

**Comment by baedert** [comment]
Let's consider this fixed then.
