### ISSUE TITLE
Select Text in Direct Messages

### ISSUE THREAD

**Issue by charlesay** [baedert/corebird#695]
If I am not mistaken, it's not possible to select text in DMs. Is there a reason for that to be the case?

**Comment by Vistaus** [comment]
The reason is that this pull request isn't merged yet:
https://github.com/baedert/corebird/pull/510

**Comment by baedert** [comment]
Consistency with the normal tweet timeline mostly.

**Comment by charlesay** [comment]
Ok but then like for tweets there should be a level on which getting text out of there is possible

**Comment by baedert** [comment]
yeah I agree, I just don't use DMs very much and the API is so stupid that implementing anything is a pain (and really, encrypting something and sending it over twitter DMs has got to be a joke).

**Comment by charlesay** [comment]
i frequently have to switch to tweetdeck to do that, like when i want to tell someone else the same thing i already wrote in an other dm, just to illustrate a use case

**Comment by Vistaus** [comment]
Thank you for committing that branch! I don't use DM's all too much either but when I do this could come in handy! :smiley:
