### ISSUE TITLE
use Notify-OSD

### ISSUE THREAD

**Issue by mDfRg** [baedert/corebird#696]
Is it possible to configure corebird to use Notify-OSD native notification system? It's really annoying to click through all those pop-ups, having it disabled it's not a option either.

**Comment by baedert** [comment]
it already uses native notifications. I don't know what you mean by pop-ups.

**Comment by mDfRg** [comment]
![002_2017-04-04](https://cloud.githubusercontent.com/assets/11591703/24675285/d5fc28de-197e-11e7-8611-36f4b6a0560c.jpg)

![003_2017-04-04](https://cloud.githubusercontent.com/assets/11591703/24675372/3231b2ae-197f-11e7-9875-fd2b02717a56.jpg)

**Comment by Vistaus** [comment]
Not sure what system you're using but I've never seen a pop-up like that. I always see a native notification like you're notify-OSD notification...

**Comment by mDfRg** [comment]
Ubuntu 16.04 from ppa ubuntuhandbook1/corebird using corebird 1.4.2. Back in days when I compiled 1.2.1 from source I was getting same sort of window-type notifications.

**Comment by baedert** [comment]
Apparently this happens on ubuntu when a notification has actions attached.

**Comment by IBBoard** [comment]
Ubuntu 18.04 is apparently dropping Unity and going back to standard Gnome. Gnome 3 handles notifications properly. "WON'T FIX"? 😊

**Comment by mDfRg** [comment]
I see, so it's not a corebird issue then. @IBBoard jokes on you, I will have been sticking with unity7 by the time ubuntu gnome is the thing (16.04 LTS till 2021 <3)

**Comment by Vistaus** [comment]
@mDfRg Joke's on you most likely as Corebird will up the required GTK version at some point, making it impossible to use newer versions on 16.04

**Comment by Vistaus** [comment]
@mDfRg Aaaand it has already happened with Corebird 1.5 The new gspell package requires 3.20 which means that if you want spell checking, then you need to either take the risk and update to GTK 3.20 on 16.04 or disable spell checking when compiling.

**Comment by mDfRg** [comment]
:(. Hope the snap version would have the needed libraries...
