### ISSUE TITLE
No corebird icon

### ISSUE THREAD

**Issue by haecker-felix** [baedert/corebird#700]
I'm using corebird 1.4 (flatpak nightly), and there is no icon.

GNOME 3.24
Fedora 26
German Language

![corebird](https://cloud.githubusercontent.com/assets/6001248/24764795/cd8feaf0-1af5-11e7-842e-fde9146ea1c9.png)
![corebird2](https://cloud.githubusercontent.com/assets/6001248/24764794/cd8f0f54-1af5-11e7-966a-d1e0b3ae492c.png)

**Comment by baedert** [comment]
> German Language

uh yeah, someone wrongly translated the "corebird" as "Corebird" in German so the icon doesn't show; I've since fixed the translator comments to actually make their way into the .po file.

I'm just going to manually fix the po file and rebuild the flatpak, one moment...

**Comment by haecker-felix** [comment]
Mhm which information I can provide? There was a corebird flatpak update, but nohting changed.

**Comment by baedert** [comment]
Yeah I rebuilt the master one earlier, I do that every once in a while. I'm going to look into it.

**Comment by baedert** [comment]
Wait, are you saying you had it installed before yesterday and the icon showed up fine before?

**Comment by baedert** [comment]
Oh and can you paste the output when running `flatpak run org.baedert.corebird` from a terminal?

**Comment by baedert** [comment]
Ok, so the icon translation in master is correct (i.e. it's not translated at all) but flatpak renames the icon from `corebird` to `org.baedert.corebird`, but then forgets the translated icon fields in the desktop file, that's a flatpak bug and here's a merge request to fix it: https://github.com/flatpak/flatpak/pull/692

This works locally so I'm just going to rebuild and push to the repo with that patch applied and hope that it fixes the problem.

**Comment by haecker-felix** [comment]
I will test it later. But why it does only affect Germany and not other languages / translations too?

**Comment by baedert** [comment]
That's wrong, current *stable* is affected when using German only (since only in that language -- and Korean I think -- has the icon name been translated). This problem is in flatpak generally. The exported desktop file with translations contains a handful of wrong icon names.

**Comment by Vistaus** [comment]
@haecker-felix Regarding Corebird in general: because it was wrongly translated only in German. Regarding Corebird Flatpak: who says it only affects German? I don't see any other reports on the Flatpak version so who knows...

**Comment by haecker-felix** [comment]
Yep. It works now. Icon is here. But a symbolic icon is missing :P

**Comment by baedert** [comment]
Yep, see https://github.com/baedert/corebird/issues/435
