### ISSUE TITLE
Request PIN page is confusing

### ISSUE THREAD

**Issue by pwithnall** [baedert/corebird#713]
When starting Corebird for the first time, it shows a page with a ‘PIN’ entry and a ‘Request PIN’ button. It’s not clear what a PIN is (twitter.com doesn’t mention one anywhere), and it looks like you need to get a PIN to put in the ‘PIN’ entry before you can press the button.

That’s actually not the case — you press the button to go to twitter.com to get a PIN to put in the entry.

It might be clearer if the initial page just displayed some text and a ‘Request PIN’ button, with no entry. The text would briefly describe that the button was going to take you to twitter.com to log in and request a PIN. Once the button’s clicked, it would open twitter.com, and change Corebird to display the ‘PIN’ entry and ‘Confirm PIN’ button.

(Version 1.4.2, flatpak.)

**Comment by baedert** [comment]
Yep, that UI is no ideal.

**Comment by baedert** [comment]
First revision:

Intial window:
![screenshot from 2017-04-29 13-35-23](https://cloud.githubusercontent.com/assets/887764/25555239/d4a7b8ca-2ce0-11e7-9298-3352811bb325.png)

After clicking "request PIN":
![screenshot from 2017-04-29 13-35-34](https://cloud.githubusercontent.com/assets/887764/25555240/de22d2b8-2ce0-11e7-95b1-9f2bac01c703.png)

**Comment by pwithnall** [comment]
Looks good. A few minor comments. On the first screen:
 * s/with the Account/with the account/ (capitalisation seems a bit unnecessary)
 * s/Don't have an account yet?/Don’t have an account on twitter.com?/ (to make it more obvious that the account is on the website, not part of Corebird)

Second screen:
 * s/Paste or type the PIN into the text field below:/Enter the PIN from twitter.com:/ (user doesn’t care that the thing below is a ‘text field’)

I guess the whole process could be streamlined a little more by embedding a WebKit web view, loading twitter.com in it when the user presses ‘Request PIN’, allowing the user to log in and authorise Corebird, then scraping the PIN out of the web view and proceeding automatically. That’s quite a lot more work though, and more maintenance overhead (prone to breaking if Twitter changes the layout of their confirmation page).

**Comment by Vistaus** [comment]
@pwithnall Why not "Don't have a Twitter account yet?"

Agreed about the rest.
