### ISSUE TITLE
"icon" Localized in .desktop File for German (and potentially other languages)

### ISSUE THREAD

**Issue by weltenweber** [baedert/corebird#715]
After installing Corebird the .desktop-file contains localized strings for the `icon` property in German (and probably other languages). For German the 'C' is capitalized, causing the icon not to be found.

**Comment by Vistaus** [comment]
This has been fixed in the latest version, 1.4.2: https://github.com/baedert/corebird/issues/682

Please update your Corebird installation to 1.4.2

**Comment by weltenweber** [comment]
Thanks for the heads up and sorry for the double report!
