### ISSUE TITLE
RFE: Restore the 'this is a reply' balloon marker for tweets that are replies

### ISSUE THREAD

**Issue by siebenmann** [baedert/corebird#716]
In Corebird 1.4.2 and older versions, tweets that were replies were marked by a black balloon thing just to the left of the date. As a solid black blob this stood out pretty well even when quickly scanning tweets, to let you know that the tweet didn't necessarily stand on its own and I might want to expand it. In current git tip corebird, this has been replaced by a much less visually obvious light grey 'Replying to ...' text below the user's name and handle. So I'd like to request that the balloon marker return for such reply tweets in addition to the current light grey text, so it's easier to see at a glance that this is a reply.

(I think that making the light grey text the same colour as the regular text would make it too obtrusive, so I agree with its current colour. I'd just like a more obvious 'this is a reply' marker. I don't think it needs to be over on the right side the way it used to be; I'm just picking that because it's the way it used to be.)

**Comment by Vistaus** [comment]
I'm not disagreeing with you or anything, but I just wanted to let you know the reason behind the change: https://github.com/baedert/corebird/issues/693

**Comment by baedert** [comment]
I agree that it's a little hard to see what's a reply and what's not at a glance.

> I'm not disagreeing with you or anything, but I just want to let you know the reason behind the change: #693

Yes, the exact rationale is:


> >Is it worth keeping the old icon as well? It helps cover the "old reply" situation without having to make up a bit of filler text

>Not sure about that. We can't put it to the left of the label with its current position and it looks kind of disconnected to the label in the upper right.

**Comment by IBBoard** [comment]
I've got my own patch to do exactly this (and a bit more).

My builds personal builds (also publicly available for openSUSE) use [this patch](https://build.opensuse.org/package/view_file/home:IBBoard:desktop/corebird/corebird-no-reply-combined.patch?expand=1) to re-instate the icon and remove the user from "Replying to" when they're replying to themselves. It makes "reply to self" chains much more compact, but still indicates that they're replies to something!

**Comment by baedert** [comment]
Yeah I don't really like that icon anymore for the reasons stated in #693, and I think it's unlikely to reappear since I can't come up with a design that doesn't have those problems, sorry.
