### ISSUE TITLE
Wrong month name

### ISSUE THREAD

**Issue by bdmbdsm** [baedert/corebird#717]
I'm using Corebird on Ubuntu 16.04 with xfce4 desktop environment.
There is ukrainian names of months marked red on the screenshot, and they are incorrect.
**'бер'** stands for 'March', but now is May, and the label must be **'тра'** in ukrainian.
Number of the day is correct.
![corebird screenshot](https://cloud.githubusercontent.com/assets/7142689/25608852/4aafa97e-2f25-11e7-8852-f3060cf4a89e.png)

**Comment by Vistaus** [comment]
I'm not Ukrainian so I'm not 100% sure, but I think one of the latest commits fixed this already by using Unicode: https://github.com/baedert/corebird/commit/4c09357d539b1f76e3afe061acd8064f9ae92944

**Comment by bdmbdsm** [comment]
I will test it now

**Comment by baedert** [comment]
No that's just the May/March mixup and fixed by https://github.com/baedert/corebird/commit/55dbcd88bb16549901695d9b55e7422daea191a8. I'll try and release 1.5 as soon as possible.
