### ISSUE TITLE
Position image viewer content based on position clicked on preview

### ISSUE THREAD

**Issue by lazka** [baedert/corebird#719]
1) See a preview image
2) Be interested in a particular portion of the image
3) Click on that part of the image
4) The larger image gets shown in a new window

Actual: The visible section is the top left corner of the image, the interesting part of the image isn't visible and scrolling is needed (I guess this is easier with a touchscreen..)

Expected/Preferred: It should try to center the big image based on the preview image click coordinates.

v1.4.1, gnome 3.22

**Comment by baedert** [comment]
Never thought about this but it makes sense.

**Comment by lazka** [comment]
Thanks.

another thought: Just centering the viewer would probably cover 90% of the cases. The interesting bits tend to be in the center.
