### ISSUE TITLE
Corebird 1.5 compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by Slater91** [baedert/corebird#720]
I tried compiling the package under Mint 18.1 (Ubuntu 16.04) but I got an error at compile time. I got no errors nor warnings on autogen using the "--disable-spellcheck" option.

This is the output (partially in Italian):

> riccardo@Hades ~/dev/corebird-1.5 $ make

> make  all-recursive

> make[1]: ingresso nella directory "/home/riccardo/dev/corebird-1.5"

> Making all in src

> make[2]: ingresso nella directory "/home/riccardo/dev/corebird-1.5/src"

> window/ComposeTweetWindow.vala:146.24-146.27: warning: Argument 3: Cannot pass null to non-null parameter type

>                    null,

>                    ^^^^

> SearchPage.vala:69.34-69.37: warning: Argument 2: Cannot pass null to non-null parameter type

>   tweet_list.bind_model (null, null);

>                                               ^^^^

> Corebird.vala:197.5-197.34: error: The name 'ensure' does not exist in the context of 'GLib.Type'

>    typeof (LazyMenuButton).ensure ();

>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

> Compilation failed: 1 error(s), 2 warning(s)

> Makefile:1212: set di istruzioni per l'obiettivo "libcorebird_la_vala.stamp" non riuscito

> make[2]: *** [libcorebird_la_vala.stamp] Errore 1

> make[2]: uscita dalla directory "/home/riccardo/dev/corebird-1.5/src"

> Makefile:447: set di istruzioni per l'obiettivo "all-recursive" non riuscito

> make[1]: *** [all-recursive] Errore 1

> make[1]: uscita dalla directory "/home/riccardo/dev/corebird-1.5"

> Makefile:379: set di istruzioni per l'obiettivo "all" non riuscito

> make: *** [all] Errore 2

I have no clue as to what I need to do or what information may be needed, so please provide me guidance in retrieving all necessary details. Thanks!

**Comment by baedert** [comment]
```
Corebird.vala:197.5-197.34: error: The name 'ensure' does not exist in the context of 'GLib.Type'
typeof (LazyMenuButton).ensure ();
```


meh. Looks like `g_type_ensure` wasn't in the vapi of the `vala` version you have installed.
That's just a small optimization though, you can replace that line with `new LazyMenuButton ();` and it should work.

**Comment by Slater91** [comment]
That indeed worked. I also issued the "make install" command (with sudo) without issues. The app won't launch now, though: this is the output.

`riccardo@Hades ~/dev/corebird-1.5/src $ ./corebird 

(corebird:26899): GLib-GIO-ERROR **: Settings schema 'org.baedert.corebird' is not installed

Rilevato trace/breakpoint`

**Comment by baedert** [comment]
As always, you have to install and compile the gsettings schemas, which a `make install` would do.(iirc it compiles the schemas?)
