### ISSUE TITLE
Enhancement Request: Smooth scroll

### ISSUE THREAD

**Issue by heydemoura** [baedert/corebird#721]
It will be a big improvement on user experience if the timeline has a smooth scrolling effect.

Smooth Scroll is all over the web, it brings a nicer look & feel and improves the user experience upon using any application.

Also, could be an option for scrolling each tweet for each tick on the mouse wheel, bringing the next tweet to the top of the list smoothly.

I think this is a huge visual improvement that is worth implementing, we need smoother visuals on Linux Desktop applications.

**Comment by Vistaus** [comment]
IIRC smooth scrolling is implemented by default in GTK since a couple of releases ago. Corebird and other GTK apps scroll very smoothly on my laptop.

**Comment by baedert** [comment]
It's not smooth (i.e. interpolated between scroll steps) if you use a mousewheel. In any case, this is a GTK+ thing and a related upstream bug report is here: https://bugzilla.gnome.org/show_bug.cgi?id=774261
