### ISSUE TITLE
Certain themes make header bar icons incorrect (?)

### ISSUE THREAD

**Issue by FireStarW** [baedert/corebird#722]
Using ubuntu 17.04, Cinnamon 3.4.0, with the menta theme (which I believe comes with ubuntu?) causes the home and search icons to change to non-matching icons, while all other themes I have tried do not change the header icons.
If this is intended behavior, this should be noted somewhere,and  the other icons do not change as well.

Example:
![screenshot from 2017-05-08 16-13-40](https://cloud.githubusercontent.com/assets/11762725/25823717/e5fa9954-340a-11e7-89ff-a3fdae29da0c.png)

**Comment by baedert** [comment]
It's not. The icon theme you chose just doesn't provide a symbolic variant of those icons.

**Comment by FireStarW** [comment]
Can you elaborate? 

Do I need to add syn links to some icons in the themes folder?

**Comment by baedert** [comment]
I can tell you that the symbolic icons your icon theme is missing are `user-home-symbolic` and `edit-find-symbolic`. Your icon theme just doesn't provide a `-symbolic` variant of these.

**Comment by Vistaus** [comment]
Have you solved this problem in the meantime?

**Comment by FireStarW** [comment]
Me? No, I grep'd the folders in /usr/share/themes for those icons and didn't get any hits, I was thinking I needed to make sym links. Honestly, the icons should probably just be included with the program

**Comment by baedert** [comment]
Your distribution package should contain a dependency on some icon theme that makes it look alright. Icon themes are so fucked up that there's no other way of making things work.
