### ISSUE TITLE
Incorrect Month Display 

### ISSUE THREAD

**Issue by nedrichards** [baedert/corebird#726]
As you can see from the screenshot Corebird is showing the date of each tweet as '23rd Mar' rather than '23rd May'. You can also see from my lovely GNOME locale settings that it should be showing May.

![screenshot from 2017-05-23 15-05-33](https://cloud.githubusercontent.com/assets/302677/26358158/8b238a34-3fc9-11e7-85e1-d2ee71cc2773.png)

Not a world ending bug but it did make me think I'd slightly lost my mind for a few minutes.

**Comment by Vistaus** [comment]
That bug is fixed in Corebird 1.5: https://github.com/baedert/corebird/issues/717

Please update to 1.5

**Comment by baedert** [comment]
What @Vistaus says. Or wait a few more days ;)

**Comment by nedrichards** [comment]
Thanks! Sounds like I actually need to send a PR to Flathub, since that's on 1.4.2 ;-)

**Comment by Vistaus** [comment]
@nedrichards You definitely should! But in the meantime, you could also try baedert's own Flatpak: https://github.com/baedert/corebird-flatpak
Haven't tested it, but judging by https://github.com/baedert/corebird-flatpak/commit/c60032ae9141b0b37aa1a60304379fa53a7ef17a it should result in a Flatpak of 1.5
