### ISSUE TITLE
Corebird not showing my own profile pic anymore

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#727]
It's not the worst thing in the world (I don't like looking at my own pic anyway lol), but of course, this shouldn't happen.

![screenshot from 2017-05-24 10 27 13](https://cloud.githubusercontent.com/assets/1716229/26393977/0b4422f0-405b-11e7-9791-44bd5626daa2.png)

![screenshot from 2017-05-24 10 27 02](https://cloud.githubusercontent.com/assets/1716229/26393988/11926f68-405b-11e7-8e60-b781c181c737.png)

![screenshot from 2017-05-24 10 26 53](https://cloud.githubusercontent.com/assets/1716229/26393989/11aa30d0-405b-11e7-9cbb-6a7755c71fce.png)

Even more weird is that, as you can see, other avatars are showing up just fine.

OS: Solus
DE: Budgie 10.3.1
Corebird: latest Git Master

**Comment by baedert** [comment]
Any console output? Does restarting fix it?

**Comment by Vistaus** [comment]
Restarting doesn't fix it. Not even a full computer reboot fixed it.

There's no console output.

**Comment by Vistaus** [comment]
Hmm, now it is back though. Guess the issue's on Twitter's end.
