### ISSUE TITLE
Corebird doesn't open a page for me to get the PIN

### ISSUE THREAD

**Issue by facundobatista** [baedert/corebird#728]
First time ever using Corebird, installed it from the Snap store.

It starts, I click on "Request PIN", it goes to a second screen saying "Enter PIN from twitter.com below", but where should I get that PIN from?

My best guess is that Corebird thinks it's opening my browser to authenticate in Twitter, but that is not happening. Probably this line I see in the terminal is relevant:

    Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.SafeLauncher was not provided by any .service files

Is there an alternative way to authenticate? Thanks!

**Comment by diddledan** [comment]
Hi, presently snaps require the apt package called `snapd-xdg-open` to be able to launch your web browser. Installing that package should get you going :-)

**Comment by facundobatista** [comment]
Worked like a charm, thanks!

**Comment by jerdog** [comment]
Also had this issue and running `sudo apt install snapd-xdg-open` solved it

**Comment by julientaq** [comment]
please put this information in the readme. Thanks!

**Comment by Vistaus** [comment]
> please put this information in the readme. Thanks!

Snap isn't officially supported by Corebird.

**Comment by phnahes** [comment]
Gtk-WARNING **: Unable to show 'http://twitter.com/signup': Operation not supported

Solve installing gvfs

sudo apt install gvfs

**Comment by Vistaus** [comment]
@phnahes If you needed to install gvfs on a Debian-based system, then I think it's safe to say your system was broken as gvfs is installed by default on most distros and esp. on Debian-based distros.
