### ISSUE TITLE
The color of the star that indicates if a tweet has been favorited or not should change to distinguish between these two states.

### ISSUE THREAD

**Issue by pmop** [baedert/corebird#729]
The color of the star that indicates if a tweet has been favorited or not stays the same regardless of "favorite" state in Corebird 1.1. The star color should change accordingly to "favorite" state so the user can distinguish a tweet that he has favorited from a tweet that he has not.

**Comment by Vistaus** [comment]
Wow, Corebird 1.1, that's a really, really old version. In recent versions your issue is not present so I suggest upgrading Corebird.

**Comment by baedert** [comment]
And I consider 1.1 to be unsupported.
