### ISSUE TITLE
I do not see comments and replies to tweets from those I am following

### ISSUE THREAD

**Issue by truckerboy** [baedert/corebird#731]
I do not see comments or replies to the tweets from folks I follow when I double click the tweet on Corebird. Is this intentional or is there an enhancement planned to add this in the future? Apologies if there is an obvious explanation but this does seem like a very basic feature to me which seems to be missing.

**Comment by baedert** [comment]
If there's a blue strip on top, you can scroll up to see up to 5 replies.

**Comment by truckerboy** [comment]
Thanks, but what does this "blue strip" signify? I find the replies missing on almost every tweet which is quite annoying to be honest. Replies to tweets are as integral to Twitter as the tweets themselves.

**Comment by baedert** [comment]
It signifies that our call to the search API returned at least 1 tweet that seems like a reply to the one you're currently viewing. There is no Twitter API to query the replies to a tweet which is why replies will often incomplete or missing entirely.

**Comment by truckerboy** [comment]
aah, I see, I was sure there was a rational explanation for such a basic feature being missing, thanks again baedert.
