### ISSUE TITLE
Issue with meson+ninja build

### ISSUE THREAD

**Issue by tglman** [baedert/corebird#733]
Hi,
Trying to build corebird with mason+ninja get some error after install.
build steps
```
mkdir build
cd build
meson ../
ninja
sudo ninja install
```
This works correctly but when running the program I get:
```
corebird: error while loading shared libraries: libcorebird.so: cannot open shared object file: No such file or directory
```

environment debian testing (stretch), the old build autogen+make still work

Bye

**Comment by baedert** [comment]
Yes, the meson build doesn't work as well (it'll also install a few `Makefile.am` files into the icon dir). The problem here is that I don't want to use a static library for debug builds since that's slow to link, but I do want a static lib for release builds. Could just install the shared lib in debug builds of course.

**Comment by baedert** [comment]
There are some severe regressions with meson 0.41 and vala, so just don't use the meson build for now.

**Comment by Vistaus** [comment]
Yeah, Solus also rolled back the Meson update to 0.40 because of Vala regressions. Not sure who's at fault, but some fixin' needs to be done :/

**Comment by Vistaus** [comment]
Lately I've seen some commits regarding Meson. What's the current status? (I know 0.41 is still regressed, but I have 0.40 on Solus)

**Comment by baedert** [comment]
Yeah, 0.41 is still broken, the corebird meson build should "work" as long as you don't install it, so fine for the local edit/compile/run workflow.

**Comment by tglman** [comment]
Hi,

I tried today with meson 0.42 and still the same problem is anyone trying to fix the install issue ?

Bye

**Comment by baedert** [comment]
Not really, why do you care?

**Comment by Vistaus** [comment]
@tglman @baedert What is there to fix? 'Cause it works fine for me with Meson 0.42.0 I've just compiled and installed the latest Corebird git master with it.

**Comment by baedert** [comment]
meson+vala works again with meson 0.42, the corebird build is still broken since we don't install the shared library (and shouldn't). simply chaning the shared lib to a static lib should fix the problem but it increases the compile times.

**Comment by Vistaus** [comment]
Ah, I understand.

**Comment by baedert** [comment]
You can already fix the build just by using `meson configure -Ddefault_library=static` and that works. I'll probably just switch the library back to a `static_library` at some point and it will simply work, but it's still slower for me to compile stuff that way.

>  I'm assuming you want to switch away from autotools sometime?

Eh, yes, but I haven't really tested the meson build that well, especially the tarballs it produces. And the autotools build works so it's not really urgent.

**Comment by tglman** [comment]
Hi,

I guess that for a while this can be a good solution: https://github.com/baedert/corebird/pull/769

Bye

**Comment by Vistaus** [comment]
meson configure -Ddefault_library=static

returns that it's not a Meson build directory, so it doesn't seem like that solution works :/
