### ISSUE TITLE
Settings option missing from app header in 1.5

### ISSUE THREAD

**Issue by jerdog** [baedert/corebird#738]
Installed Corebird via `sudo snap install corebird` and it seems this version removes the Settings option which existed in 1.4. The only way to get to settings is to use the keyboard shortcut of `Ctrl + Shift + p`. This doesn't feel like a good UI/UX move.

**Comment by Vistaus** [comment]
I have the settings button in the headerbar in 1.5 baedert didn't remove it, so it's gotta be a bug or maybe you're missing something. What DE are you running, Unity?

**Comment by jerdog** [comment]
Ubuntu Gnome 17.04

---
*Jeremy Meiss*

*"**In the beginning the Universe was created. This has made a lot of
people very angry and been widely regarded as a bad move.**" - *Douglas
Adams

LinkedIn <https://www.linkedin.com/in/jeremymeiss> / Website
<https://jmeiss.me> / PGP Key <https://keybase.io/jerdog/>

**Comment by diddledan** [comment]
I can confirm this behaviour. Restarting the application after logging into twitter fixes it. It's unclear whether I've made a mistake in packaging the snap (to be tracked at my repo: [diddledan/corebird-snap](https://github.com/diddledan/corebird-snap/issues)) or if this is an upstream issue in corebird itself (for here).
