### ISSUE TITLE
Corebird not honoring GTK_THEME variable

### ISSUE THREAD

**Issue by carmelo12341** [baedert/corebird#739]
I'm trying to use the adwaita theme only on corebird since some parts of the layout don't have a nice view

![screenshot_20170613_212325](https://user-images.githubusercontent.com/9203764/27112751-9c0b17c0-507e-11e7-95c8-aa4adb232540.png)

With adwaita

![screenshot_20170613_212540](https://user-images.githubusercontent.com/9203764/27112800-e5f15a84-507e-11e7-92a5-811ff0195f46.png)

Corebird honors the variable when starting it from a terminal, but when starting it from a .desktop file it doesn't honor the variable.

This is how I try to use the variable in the .desktop file

![screenshot_20170613_212931](https://user-images.githubusercontent.com/9203764/27112952-958cb218-507f-11e7-8a02-18ff8181d3b4.png)
Edit: There is a typo there, even after fixing it, still doesn't work

It **works** with other applications the same way, but corebird doesn't

**Comment by Vistaus** [comment]
Works fine for me from a .desktop file, no tweaking required. In fact, it's been working fine for years now.

**Comment by carmelo12341** [comment]
How did you manage to do it? what do you have in your .desktop file?

**Comment by Vistaus** [comment]
I never have to touch the .desktop file, it honors the GTK theme automatically. What OS+DE/WM are you using and how did you install Corebird?

**Comment by carmelo12341** [comment]
I use a light theme by default, the problem is that I want to use the variable GTK_THEME in order to use **another** theme with corebird.
Other applications do honor the variable, corebird just ignores it.
I'm using Arch with Gnome btw

**Comment by baedert** [comment]
Corebird doesn't do anything special regarding the gtk+ theme. This might be related to the dbus activation.

**Comment by carmelo12341** [comment]
huh? what do you mean?

**Comment by baedert** [comment]
So, after some testing, the snippet you showed works just fine *sometimes*, dunno if gnome-shell has some caching going on or what you use.

**Comment by carmelo12341** [comment]
It works for you? lol
It doesn't even work with a shell script god dammit

**Comment by baedert** [comment]
With what shell script doesn't it work? If it works from the command line, corebird clearly honors the environment variable and shell scripts work here too.

**Comment by carmelo12341** [comment]
I thought that maybe using a script in the desktop file it may work
![screenshot_20170615_111051](https://user-images.githubusercontent.com/9203764/27190848-67a3135a-51bb-11e7-8efe-5da6aa92d476.png)
I have that file as /usr/bin/corebird.sh
Still doesn't work.

**Comment by carmelo12341** [comment]
I think I just found the problem, it was this line in the desktop file
```
DBusActivatable=True
```
Commenting it fixes the issue with the theme, but, will there be any problems if that line is commented?
Why was it there in the first place?
Anyway, thanks for the help.
^_^
