### ISSUE TITLE
feature-request: ubuntu-ppa

### ISSUE THREAD

**Issue by murpyslaw** [baedert/corebird#742]
As a user I'd like to be able to simply install this client under ubuntu 14.04 LTS  without having any technical knowledge.

**Comment by baedert** [comment]
And you didn't like https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/corebird/ ?

**Comment by Vistaus** [comment]
What baedert says. Besides, if you don't have any technical knowledge, why don't you just issue

sudo snap install corebird

to get the latest version?

**Comment by monsanto** [comment]
It isn't clear that PPA is official (isn't mentioned in the README, isn't mentioned on the website), and it often crashes for me on Ubuntu 16.04 LTS. The snap command isn't mentioned anywhere either.

To be clear, the only installation instructions given are "Check your distribution's package manager." To me this means "apt-get install corebird", and on my OS this is corebird 1.1. Perhaps "distribution's package manager" also means snap in this case, if so I think you are overstating the degree to which people are familiar with snap

**Comment by Vistaus** [comment]
@monsanto 

"if so I think you are overstating the degree to which people are familiar with snap"
Please point me to where I said that you have to be familiar with Snap? 'Cause I'm pretty sure I only provided you the easiest alternate method of installing the latest Corebird, I never said that you have to be familiar with it.

"Perhaps "distribution's package manager" also means snap in this case"
It kinda does. Canonical is pushing Snap forward as the new method of installing apps on Ubuntu, so this kind of is the "new package manager". Again: you don't have to be familiar with it, but you should if you want to keep using Ubuntu in the future.

---

Btw, speaking of overstating: aren't you overstating as well? 'Cause you say you don't have much technical knowledge, yet you found your way to GitHub, a platform mostly aimed at *developers*.

**Comment by baedert** [comment]
> It isn't clear that PPA is official (isn't mentioned in the README, isn't mentioned on the website),

It's not official in any way. Neither are any of the other packages you can find in any distribution.

> The snap command isn't mentioned anywhere either.

It's not official either.

> The only installation instructions given are "Check your distribution's package manager." To me this means "apt-get install corebird", and on my OS this is corebird 1.1.

Yes, 1.1 is probably the best you'll get with a system-wide installation using your package manager, given that your entire OS is over three years old.

> Perhaps "distribution's package manager" also means snap in this case, if so I think you are overstating the degree to which people are familiar with snap

It doesn't and those two things are entirely unrelated; those instructions existed before snap.

**Comment by monsanto** [comment]
@baedert I feel like there is some miscommunication here. I took the original post as asking for an official PPA. You replied with one of unknown provenance, I pointed that out, and you confirmed that it was unofficial. OK, glad we got that out of the way... but the request still stands for this project to have a PPA. Are you against this? 

Personally I would have found this helpful, which is why I bothered to chime in. I found corebird to be difficult to build, I don't like using mystery PPAs from people I don't know, and the snap version doesn't support GTK themes. Your project, though

**Comment by baedert** [comment]
> I feel like there is some miscommunication here. I took the original post as asking for an official PPA. You replied with one of unknown provenance, I pointed that out, and you confirmed that it was unofficial. OK, glad we got that out of the way.

My point is that that ppa is as trustworthy as any other package in your system.

> but the request still stands for this project to have a PPA. Are you against this?

Basically, yes. I won't create one, just like I won't maintain packages for any other distribution. pandajim is doing good work with his PPA and keeps it up to date whenever I make a new release.

**Comment by Vistaus** [comment]
@monsanto Pandajim has been doing this for a few years now and lots of people in the community use his PPA. So mystery person or not, he's proven himself to be trustworthy.

There's also a Flatpak version if you still don't trust Pandajim. (and Flatpak does integrate with your GTK theme if you install one of the Flatpak GTK theme packages)

**Comment by monsanto** [comment]
> My point is that that ppa is as trustworthy as any other package in your system.

I disagree. The security of system packages is tied to the reputation of the distribution. There is nobody to hold accountable for PPAs found in the wild.

> Pandajim has been doing this for a few years now and lots of people in the community use his PPA. So mystery person or not, he's proven himself to be trustworthy.

Then he should get a shout out in the installation instructions, thus tying corebird's reputation to that PPA.

> There's also a Flatpak version if you still don't trust Pandajim. (and Flatpak does integrate with your GTK theme if you install one of the Flatpak GTK theme packages)

You're missing the point. I am using corebird just fine and I don't need help installing it. I'm saying the installation process is a pain in the ass and it would improve this project if this was addressed. What I'm hearing is that you all don't care, so I'm done advocating for it.

**Comment by baedert** [comment]
> I'm done advocating for it.

Alrighty then

**Comment by Vistaus** [comment]
@monsanto No, *you're* missing the point. Snaps are the future of Ubuntu and that GTK theming issue is about to be resolved by Canonical. And as for DEB packages: it's a distro's responsibility to keep an app up-to-date. Clearly Ubuntu doesn't care that some packages in LTS versions break because they are deprecated upstream (and in cases like this, it's on Twitter's because they've changed stuff which Corebird needed to keep up with).
