### ISSUE TITLE
g_utf8_offset_to_pointer(): corebird killed by signal 11

### ISSUE THREAD

**Issue by EdwardBetts** [baedert/corebird#747]
See https://bugzilla.redhat.com/show_bug.cgi?id=1466954

I'm having the same problem. This is from GDB:

Core was generated by `corebird'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  g_utf8_offset_to_pointer (
    str=0x55ad000ce0f0 "nitedutilities @AliDriverUK @RoryStewartUK replied to GM last night with this Guy, some work IS already happening through #WoodlandTrust, 65k trees planted: https://t.co/igufpf0rRV 🌳", offset=4294238837) at ././glib/gutf8.c:351

**Comment by baedert** [comment]
This should be fixed in 1.5.1.

**Comment by EdwardBetts** [comment]
Thanks.
