### ISSUE TITLE
Can't install on Arch

### ISSUE THREAD

**Issue by fakeid30** [baedert/corebird#748]
When trying to install corebird on arch from AUR : https://aur.archlinux.org/packages/corebird/

I am seeing this error : 

checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for valac... /usr/bin/valac
checking whether /usr/bin/valac is at least version 0.28.0... yes
./configure: line 12422: syntax error near unexpected token `0.16'
./configure: line 12422: `  PKG_PROG_PKG_CONFIG(0.16)'
+ exit 1
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by baedert** [comment]
Install `pkg-config` or something?
I don't maintain that package so this is the wrong place to ask.

**Comment by fakeid30** [comment]
Got it , needed base-devel
