### ISSUE TITLE
Segfault after initialization: Settings schema 'org.baedert.corebird' does not contain a key named 'media-visibility'

### ISSUE THREAD

**Issue by innir** [baedert/corebird#749]
Hi,

I got a bug report in Debian which I can not reproduce and I need your help to fix it:

Corebird segfaults after initialization.

`Settings schema 'org.baedert.corebird' does not contain a key named 'media-visibility'`

Even though:

```
#~ cat /usr/share/glib-2.0/schemas/org.baedert.corebird.gschema.xml | grep media-
  <enum id="org.baedert.corebird.media-visibility">
    <key name="max-media-size" type="d">
    <key name="media-visibility"
enum="org.baedert.corebird.media-visibility">
```
I tried reseting the schema with: `dconf reset -f /org/baedert/` with no luck.

The original bug report is at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867552

**Comment by Vistaus** [comment]
Does recompiling the schemas help (using glib-compile-schemas)?

**Comment by baedert** [comment]
Another issue could be that the `org.baedert.corebird.gschemas.xml` file exists both in `/usr/share/glib-2.0/schemas` and `/usr/local/share/glib-2.0/schemas`, but the one in `/usr/local/` is old and does not contain that settings key.

**Comment by dfranganillo** [comment]
Hi, I'm the one that opened the bug at Debian's bugtracker.

I have no other schema file on either /usr/local or ~/.local/ (my user's prefix). BUT I already used corebird installed by myself (and uninstalled before trying Debian's) Maybe there're some traces left?
What I should do with glib-compile-schemas?

**Comment by innir** [comment]
@dfranganillo I think you should do a

`sudo glib-compile-schemas /usr/share/glib-2.0/schemas`

You probably need to restart you gnome session afterwards.

**Comment by innir** [comment]
Could you check all the directories listed in

`echo $XDG_DATA_DIRS`

(you need to add `/glib-2.0/schemas`) if there is a `org.baedert.corebird.gschema.xml` file

or just search for it

`find / -name org.baedert.corebird.gschemas.xml`

**Comment by dfranganillo** [comment]
As root:
```
:~# find / -name org.baedert.corebird.gschema.xml
/usr/share/glib-2.0/schemas/org.baedert.corebird.gschema.xml
```

As my user:
```
~$ echo $XDG_DATA_DIRS
/usr/share/gnome:/usr/local/share/:/usr/share/
```

```
~$ XDG_DATA_DIRS="$XDG_DATA_DIRS:/usr/share/glib-2.0/schemas/"
~$ echo $XDG_DATA_DIRS
/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/glib-2.0/schemas/
```

Still trapped:

```
~$ corebird 

(corebird:5980): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:5980): Gtk-WARNING **: Theme parsing error: style.css:232:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:5980): Gtk-WARNING **: Theme parsing error: style.css:238:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:5980): Gtk-WARNING **: Theme parsing error: style.css:239:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:5980): Gtk-WARNING **: Theme parsing error: style.css:244:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:5980): GLib-GIO-ERROR **: Settings schema 'org.baedert.corebird' does not contain a key named 'media-visibility'
`trap' para punto de parada/seguimiento
```

**Comment by innir** [comment]
OK, I have no further idea, maybe @baedert oder @Vistaus can help you get rid of the left overs of your former corebird installation.

**Comment by dfranganillo** [comment]
I uninstalled it, I said that *MAYBE* there are leftovers. Anyway, I updated today to `corebird_1.5.1-1_amd64.deb` and is still happening.

**Comment by Vistaus** [comment]
I'm pretty sure that the leftovers could be the problem. I suggest you start all clean.

- Uninstall Corebird 1.5.1
- Install mlocate (if not installed)
- Issue `sudo updatedb`
- When that's done, issue `locate corebird` and remove all of the Corebird files/folders mentioned

**Comment by dfranganillo** [comment]
I've purged corebird, and updatedb'ed:

```
# locate corebird
/var/cache/apt/archives/corebird_1.5-1_amd64.deb
/var/cache/apt/archives/corebird_1.5.1-1_amd64.deb
```
Thanks

**Comment by Vistaus** [comment]
If you've removed all of Corebird's leftovers, then reinstall Corebird.

**Comment by innir** [comment]
@dfranganillo try `sudo find / -name *corebird*` to see where corebird files are still left on your system. And please delete (or move) `~/.config/corbird` and `~/.local/share/corebird`

**Comment by dfranganillo** [comment]
@Vistaus I already did that, still trap.
@innir Are we running in circles? As locate shows, I deleted cache and config before running it.

Purged corebird, deleted cache&config:

```# LC_ALL=C find / -iname *corebird*
/var/cache/apt/archives/corebird_1.5-1_amd64.deb
/var/cache/apt/archives/corebird_1.5.1-1_amd64.deb
find: '/run/user/1000/gvfs': Permission denied
```

**Comment by Vistaus** [comment]
@innir locate shows the same thing as find, including the hidden files/folders ;)

@dfranganillo Just to make sure I got it right from the bug report, you are running Debian Unstable? And what DE are you using?

**Comment by baedert** [comment]
Did you recompile the schemas in `/usr/local` as well after uninstalling the schemas file from there?

This entire issue is just us guessing what you might've done in the past, so a waste of time. We don't even know if anything has been installed anywhere besides `/usr` or how you uninstalled it.

**Comment by baedert** [comment]
I think checking with
`gsettings --schemadir /usr/local/share/glib-2.0/schemas list-recursively org.baedert.corebird`
and comparing that to
`gsettings --schemadir /usr/share/glib-2.0/schemas list-recursively org.baedert.corebird`
could work, but depends on whether anything has been installed into `/usr/local` at some point... or somewhere else.

**Comment by Vistaus** [comment]
@baedert But he did use locate to search for Corebird stuff. If that schema was still in /usr/local, locate would've listed it.

**Comment by baedert** [comment]
Yes, but the xml file gets compiled into the `gschemas.compiled` file. And if you then remove the xml file... it's still compiled.

**Comment by Vistaus** [comment]
@baedert Ah, didn't know that. Thanks.

**Comment by dfranganillo** [comment]
@baedert You got it! I've removed that gschemas.compiled and it is working now...
What a clusterfuck is this schema's thing.

Thanks to everybody!

**Comment by innir** [comment]
OK, great you found the problem. I'll close the Debian bug :-).
