### ISSUE TITLE
could not  finish make on windows with msys2 

### ISSUE THREAD

**Issue by zhou0** [baedert/corebird#751]
$ make
make  all-recursive
make[1]: 进入目录“/d/github.com/baedert/corebird/archive/corebird-1.5”
Making all in src
make[2]: 进入目录“/d/github.com/baedert/corebird/archive/corebird-1.5/src”
XMLLINT=/mingw32/bin/xmllint /mingw32/bin/glib-compile-resources --target corebird-resources.c --generate --sourcedir=.. --c-name corebird ../corebird.gresource.xml

this commandline never finish. I leave the computer running for a day and the make command still could not finish and there is no other outputs.

**Comment by baedert** [comment]
I don't have windows, I can't help you with that.
