### ISSUE TITLE
Non-landscape video can overflow screen

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#754]
I just recently noticed that clicking videos and clicking pictures results in different behaviour. If you click a picture then it aligns it with the middle of Corebird (vertically) and centre aligns it *if* that doesn't result in the image leaving the desktop. If it would leave the desktop (e.g. you've got Corebird on the left of your screen) then it moves the picture to the right so that it is all visible.

If you click a landscape-proportioned video then the same thing happens, but for non-landscape (e.g. [square](https://twitter.com/nowthisnews/status/890184489716129797) or portrait videos from phones) then it only ever centre aligns and so the content can get lost.

Tested with Git Master. Hopefully the pictures explain.

Landscape videos get shifted if they hit the screen edge:
![corebirdvideoalignmentbug-landscapewithspace](https://user-images.githubusercontent.com/388582/28714129-fff93950-7389-11e7-8f43-59865fc79798.jpg)
![corebirdvideoalignmentbug-landscapewithoutspace](https://user-images.githubusercontent.com/388582/28714132-fffb1018-7389-11e7-8cb6-943a76628f22.jpg)

Square/portrait videos don't:
![corebirdvideoalignmentbug-squarewithspace](https://user-images.githubusercontent.com/388582/28714131-ffface00-7389-11e7-89c7-a2660a223949.jpg)
![corebirdvideoalignmentbug-squarewithoutspace](https://user-images.githubusercontent.com/388582/28714130-fffa798c-7389-11e7-9395-b990439d6e07.jpg)

**Comment by baedert** [comment]
Corebird doesn't control the window placement of course. I guess the problem is more that the window gets resized to a size bigger than the monitor in the first place and mutter just bails out of such calculations in that case.

**Comment by Vistaus** [comment]
It's not only limited to videos. Square photos overflow the screen as well.

**Comment by IBBoard** [comment]
Really? Any examples? Because I thought I'd only had it happen with square and portrait videos. I'd never noticed it with pictures.

If this is a window manager issue rather than a Corebird issue, is there anything that we can do to debug/prove it so that we can write an upstream bug report that might get fixed?

**Comment by Vistaus** [comment]
@IBBoard Yes, I have my own pictures as an example 'cause my phone takes square pictures by default (I can change it, but I like 'em square :-) )

![screenshot from 2017-07-28 14 44 48](https://user-images.githubusercontent.com/1716229/28717777-71656d16-73a3-11e7-94a1-4ecd361a864b.png)
![screenshot from 2017-07-28 14 44 40](https://user-images.githubusercontent.com/1716229/28717778-716b406a-73a3-11e7-9429-cf48d30fc577.png)

**Comment by IBBoard** [comment]
Is it losing anything off the left-hand side? If you move Corebird to the middle of your screen, is the overlap on the right spread evenly between the left and right sides?

Top and bottom cropping is expected with Corebird (it does vertical scroll) but the shadow on the left in the clicked version appears to match the shadow on the left in the version in the timeline (which isn't cropped).

**Comment by baedert** [comment]
We probably just shouldn't use a size for the dialog that doesn't fit in the screen at all, vertically or horizontally. That would also fix/work-around the issue of portrait mode phone videos.
