### ISSUE TITLE
Starting DM thread causes invalid self-thread in list

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#764]
In the latest Git Master, if you send the first DM to a recipient then Corebird gets the threading wrong and creates a thread for you (which is then empty).

Steps to recreate:
 1. Find a user you haven't DMed
 1. Start a new thread by sending them a DM from Corebird
 1. Go back to the DM Threads page

Expected result:
 1. DM thread to that user containing your initial DM

Actual result:
 1. DM thread to yourself that claims to contain your initial DM, but actually shows up as empty if you click on it

If you don't have a cooperative friend to test this with, create a test account. After testing once, you'll need to delete the DMs from your account on Twitter and then open the sqlite database and delete all `dm_threads` rows where the `user_id` is your ID or their ID, and all of the `dm` rows where `from_id` or `to_id` is their ID.

After logging and debugging the problem, I found that the problem is in [DMManager.vala ~L199](https://github.com/baedert/corebird/blob/master/src/DMManager.vala#L199-L214) - it correctly detects the `thread_user_id` but then just creates a `DMThread` object using the sender's ID. When you create the thread by sending the first DM then the sender us you!

**Comment by IBBoard** [comment]
[Diff for additional logging](https://github.com/baedert/corebird/files/1272212/debugging-corebird-dm.txt)

[Example logging for good and bad thread creation](https://github.com/baedert/corebird/files/1272214/notes.txt) - note the difference at `DMThreadsModel.vala` line 63.

I've got a fix for this, but I don't know whether it is better to do more extensive changes (pull out the right info earlier and change the whole function) or make smaller changes (three lines commented out in my logging diff in the `DMThread` creation section, which include a couple of ternaries)

**Comment by Vistaus** [comment]
Isn't https://github.com/baedert/corebird/commit/6e6777e680fc9ec93263496839183a328ec0ea3c supposed to fix that?

**Comment by IBBoard** [comment]
Don't think so - that's about duplicates with self-replies. This is about starting new threads and using the wrong details to create the thread.
