### ISSUE TITLE
Saving picture results in unusable 0kb file

### ISSUE THREAD

**Issue by Vistaus** [baedert/corebird#768]
Steps to reproduce:

1 Right-click a picture in the home timeline
2 Click Save as...
3 Save the picture
4 Picture isn't truly saved as it ends up as a unusable 0kb file

Distro: Solus
Corebird: latest git master

**Comment by baedert** [comment]
When do you check that the picture is 0kb? It has to be downloaded first, so there needs to be some time between saving and inspecting the file.

**Comment by Vistaus** [comment]
I check after several minutes.

**Comment by baedert** [comment]
I can't reproduce this here. Does it happen with every image? Is there any console output when you save an image and get a 0kb file?

**Comment by Vistaus** [comment]
It seems to happen with Instagram images. I know you can't technically directly save images from Instagram unless the app implements a workaround (like many 3rd-party Instagram apps do). So you should either implement a such a workaround or maybe not offer the Save as option for Instagram images ;)

**Comment by Vistaus** [comment]
I can confirm it's fixed now. Thank you!!! :)
