### ISSUE TITLE
Make command failes

### ISSUE THREAD

**Issue by foger** [baedert/corebird#771]
Hello. I installed all dependencies.

Glib verion: 2.49
GTK+ version: 3.21.4

autogen.sh result is OK:

                Corebird  1.6
                  Prefix: /usr/local
           Vala Compiler: valac    --pkg gtk+-3.0   --pkg json-glib-1.0   --pkg sqlite3   --pkg libsoup-2.4   --pkg glib-2.0   --target-glib=2.44                  -D VIDEO                  --pkg gstreamer-video-1.0 -D SPELLCHECK --pkg gspell-1
           valac version: Vala 0.30.1
              C Compiler: gcc -g -O2
               Debugging: no
           Video enabled: yes
       Gst check enabled: yes
   Spellchecking enabled: yes

'make' command ends with:

> make  all-recursive
make[1]: Entering directory '/opt/corebird'
Making all in src
make[2]: Entering directory '/opt/corebird/src'
gstreamer-1.0.vapi:741.75-741.77: warning: Gst is experimental
gstreamer-1.0.vapi:1504.76-1504.78: warning: Gst is experimental
gstreamer-1.0.vapi:1055.110-1055.112: warning: Gst is experimental
gstreamer-1.0.vapi:3315.163-3315.165: warning: Gst is experimental
gstreamer-1.0.vapi:3317.128-3317.130: warning: Gst is experimental
gstreamer-1.0.vapi:3319.176-3319.178: warning: Gst is experimental
widgets/MediaButton.vala:272.27-272.47: error: The name `FileChooserNative' does not exist in the context of `Gtk'
    var filechooser = new Gtk.FileChooserNative (title,
                          ^^^^^^^^^^^^^^^^^^^^^
widgets/MediaButton.vala:272.9-276.61: error: var declaration not allowed with non-typed initializer
widgets/MediaButton.vala:278.5-278.15: error: The name `filechooser' does not exist in the context of `MediaButton.save_as_activated'
    filechooser.set_current_name (Utils.get_media_display_name (_media));
    ^^^^^^^^^^^
widgets/MediaButton.vala:279.9-279.19: error: The name `filechooser' does not exist in the context of `MediaButton.save_as_activated'
    if (filechooser.run () == Gtk.ResponseType.ACCEPT) {
        ^^^^^^^^^^^
widgets/MediaButton.vala:280.42-280.52: error: The name `filechooser' does not exist in the context of `MediaButton.save_as_activated'
      var file = GLib.File.new_for_path (filechooser.get_filename ());
                                         ^^^^^^^^^^^
widgets/MediaButton.vala:283.43-283.53: error: The name `filechooser' does not exist in the context of `MediaButton.save_as_activated'
      debug ("Downloading %s to %s", url, filechooser.get_filename ());
                                          ^^^^^^^^^^^
widgets/ReplyIndicator.vala:36.5-36.16: error: The name `set_css_name' does not exist in the context of `ReplyIndicator'
    set_css_name ("replyindicator");
    ^^^^^^^^^^^^
widgets/FavImageView.vala:152.27-152.47: error: The name `FileChooserNative' does not exist in the context of `Gtk'
    var filechooser = new Gtk.FileChooserNative (_("Select Image"),
                          ^^^^^^^^^^^^^^^^^^^^^
widgets/FavImageView.vala:152.9-156.61: error: var declaration not allowed with non-typed initializer
widgets/FavImageView.vala:161.5-161.15: error: The name `filechooser' does not exist in the context of `FavImageView.new_fav_image_button_clicked_cb'
    filechooser.set_filter (filter);
    ^^^^^^^^^^^
widgets/FavImageView.vala:163.9-163.19: error: The name `filechooser' does not exist in the context of `FavImageView.new_fav_image_button_clicked_cb'
    if (filechooser.run () == Gtk.ResponseType.ACCEPT) {
        ^^^^^^^^^^^
widgets/FavImageView.vala:166.44-166.54: error: The name `filechooser' does not exist in the context of `FavImageView.new_fav_image_button_clicked_cb'
        var file = GLib.File.new_for_path (filechooser.get_filename ());
                                           ^^^^^^^^^^^
widgets/FavImageView.vala:58.24-58.27: warning: Argument 3: Cannot pass null to non-null parameter type
                       null,
                       ^^^^
window/ComposeTweetWindow.vala:288.27-288.47: error: The name `FileChooserNative' does not exist in the context of `Gtk'
    var filechooser = new Gtk.FileChooserNative (_("Select Image"),
                          ^^^^^^^^^^^^^^^^^^^^^
window/ComposeTweetWindow.vala:288.9-292.61: error: var declaration not allowed with non-typed initializer
window/ComposeTweetWindow.vala:299.5-299.15: error: The name `filechooser' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
    filechooser.set_filter (filter);
    ^^^^^^^^^^^
window/ComposeTweetWindow.vala:301.9-301.19: error: The name `filechooser' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
    if (filechooser.run () == Gtk.ResponseType.ACCEPT) {
        ^^^^^^^^^^^
window/ComposeTweetWindow.vala:302.22-302.32: error: The name `filechooser' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
      var filename = filechooser.get_filename ();
                     ^^^^^^^^^^^
window/ComposeTweetWindow.vala:302.11-302.48: error: var declaration not allowed with non-typed initializer
      var filename = filechooser.get_filename ();
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
window/ComposeTweetWindow.vala:303.28-303.35: error: The name `filename' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
      debug ("Loading %s", filename);
                           ^^^^^^^^
window/ComposeTweetWindow.vala:306.42-306.49: error: The name `filename' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
      var file = GLib.File.new_for_path (filename);
                                         ^^^^^^^^
window/ComposeTweetWindow.vala:313.40-313.47: error: The name `filename' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
        warning ("%s (%s)", e.message, filename);
                                       ^^^^^^^^
window/ComposeTweetWindow.vala:329.18-329.25: error: The name `filename' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
      } else if (filename.has_suffix (".gif") &&
                 ^^^^^^^^
window/ComposeTweetWindow.vala:337.48-337.55: error: The name `filename' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
        this.compose_image_manager.load_image (filename, null);
                                               ^^^^^^^^
window/ComposeTweetWindow.vala:338.46-338.53: error: The name `filename' does not exist in the context of `ComposeTweetWindow.add_image_clicked_cb'
        this.compose_job.upload_image_async (filename);
                                             ^^^^^^^^
window/AccountDialog.vala:344.27-344.47: error: The name `FileChooserNative' does not exist in the context of `Gtk'
    var filechooser = new Gtk.FileChooserNative (_("Select Banner Image"),
                          ^^^^^^^^^^^^^^^^^^^^^
window/AccountDialog.vala:344.9-348.61: error: var declaration not allowed with non-typed initializer
window/AccountDialog.vala:352.5-352.15: error: The name `filechooser' does not exist in the context of `AccountDialog.show_crop_image_selector'
    filechooser.set_filter (filter);
    ^^^^^^^^^^^
window/AccountDialog.vala:354.9-354.19: error: The name `filechooser' does not exist in the context of `AccountDialog.show_crop_image_selector'
    if (filechooser.run () == Gtk.ResponseType.ACCEPT) {
        ^^^^^^^^^^^
window/AccountDialog.vala:355.30-355.40: error: The name `filechooser' does not exist in the context of `AccountDialog.show_crop_image_selector'
      string selected_file = filechooser.get_filename ();
                             ^^^^^^^^^^^
SearchPage.vala:67.34-67.37: warning: Argument 2: Cannot pass null to non-null parameter type
    tweet_list.bind_model (null, null);
                                 ^^^^
Corebird.vala:98.30-98.32: warning: Gst is experimental
Corebird.vala:200.5-200.34: error: The name `ensure' does not exist in the context of `GLib.Type'
    typeof (LazyMenuButton).ensure ();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Corebird.vala:201.5-201.32: error: The name `ensure' does not exist in the context of `GLib.Type'
    typeof (FavImageView).ensure ();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 31 error(s), 9 warning(s)
Makefile:1284: recipe for target 'libcorebird_la_vala.stamp' failed
make[2]: *** [libcorebird_la_vala.stamp] Error 1
make[2]: Leaving directory '/opt/corebird/src'
Makefile:451: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/corebird'
Makefile:383: recipe for target 'all' failed
make: *** [all] Error 2

What am I doing wrong?

**Comment by baedert** [comment]
That looks like an old vala. I'm not sure in what version the things you miss are introduced but it certainly looks like your vala is too old for the rest of your system, e.g. `GtkFileChooserNative` is present since gtk+ 3.20 while it's not in the `gtk+--3.0.vapi` that comes with the vala your have installed.

**Comment by Vistaus** [comment]
Also, how come you're running GTK 3.21.4? That's an old beta. 3.22 is the final release version of 3.21.x

**Comment by foger** [comment]
Thank's to all. Updated Vala and GTK+ and compiled normally. 
Distro - Ubuntu 16.04.
