### ISSUE TITLE
Replace the black bar by a GtkStackSwitcher

### ISSUE THREAD

**Issue by Kekun** [baedert/corebird#772]
The black bar looks quite odd, especially with the regular GTK+ theme. It also doesn't look very GNOME 3 like.

What about using a GtkStackSwitcher in the center of the header bar instead? It would avoid having an odd looking widget and would automatically adapt itself to the user's theme, would be more compliant to the GNOME 3 HIG and  would save vertical space.

If for any reason a stack switcher isn't usable, its behavior is easy to mimic, but given that the black bar switches a GtkStack already it should work well.

**Comment by baedert** [comment]
stackswitchers don't do icons and are way too wide for the header bar. I also still want to see a title. And wow it's boring.

**Comment by Kekun** [comment]
The title is pretty useless as for the vast majority of the cases it just explains what the already selected icon shows. If you are OK with it I don't mind implementing this change.

**Comment by baedert** [comment]
I'm ok with it, I like the current style.

**Comment by Vistaus** [comment]
@Kekun I'd love this change! Could you implement it so that we can get a taste of how it works in practice?

**Comment by Kekun** [comment]
@Vistaus Sure I'll definitely try, I have a buggy prototype so far.

**Comment by Kekun** [comment]
FYI, here is a screenshot of what it looks like so far: https://pasteboard.co/GNndwd8.png

The badges are forced just for dev purpose, I plan to change their color to the "highlighted" (blue in Adwaita) one later so don't worry that they are there and all grey. The creenshot shows the smallest width possible with the bar centered (instead of filling all the available space) and with 12px margins added before and after each icon. The margins could be made smaller if needed to get a bit more vertical space.

For the moment the width of the horizontal bar is fixed to the smllest possible, but it could be asked to take all the available width if needed. Here are example taking all the available space or not:
- https://pasteboard.co/GNnfLUf.png
- https://pasteboard.co/GNng39X.png

Any feedback is welcome.

**Comment by Vistaus** [comment]
It looks great so far! I really like this implementation! 😄 Two things though:

1 Not sure why there are selection boxes on the buttons?
2 Not the most important thing and of course it's a matter of opinion, but I think it would be better to have text on the buttons when the window is maximized (so text beside icons). That'd look better than stretched out buttons.

**Comment by Vistaus** [comment]
How are things progressing, @Kekun ? :)

**Comment by Kekun** [comment]
I didn't touch it in the previous week. What is still to do:
- draw the badges with the theme link color rather than a hardcoded one,
- show the navigation box only when it makes sense, and display the headerbar's title otherwise.

I'll go back to it as soon as possible but I'm currently super busy with more urgent projects. :x

**Comment by IBBoard** [comment]
Sorry, but IMO those buttons are just far too cluttered in the header, and you lose some of the clean and conventional information about where you are (without extra cognitive effort)

**Comment by Vistaus** [comment]
@Kekun Are you still working on this?

**Comment by Kekun** [comment]
@Vistaus No I stopped as @baedert seem to prefer the current style and I didn't have much free time to work on it. :/

I may work on that again depending on how the current UI work on the Librem 5.

**Comment by Vistaus** [comment]
@Kekun Alright, I understand. Thanks for trying though! :) But in that case, you might as well close this issue for now.

**Comment by Kekun** [comment]
Sure. it can always be reopened later if needed.
