### ISSUE TITLE
Feature: Emoticons

### ISSUE THREAD

**Issue by dsofeir** [baedert/corebird#773]
Emoticons are absent from corebird when viewing and composing tweets. Is this deliberate? What's the reason?

Is there an appetite amongst the userbase and/or the developer team to add this?

**Comment by baedert** [comment]
Guessing you are talking about emojis. There is an emoji chooser in gtk+3.22.$newest, but for colored emojis you need updates for cairo and fontconfig as well. Once you have that, you can view them mostly fine: https://pbs.twimg.com/media/DKYzfXUW0AMdGnG.jpg

Inserting them is another story....: https://twitter.com/corebirdclient/status/910458735243513857

**Comment by dsofeir** [comment]
Yes, great thank you!

However I am running OpenSUSE Tumbleweed and have double checked that I am running the latest version of libraries mentioned. It's still not working. That may be because I using the KDE desktop?

**Comment by baedert** [comment]
Using KDE doesn't change anything. The dependencies are just very recent so they might not be in your distro yet, or you simply don't have an emoji font installed (like noto-emoji or whatever your distro calls it if it's there...).

**Comment by dsofeir** [comment]
Ah, fantastic! That was it, I didn't have an emoji font installed. I added the package 'twemoji-color-font' and everything works. Thank you
