### ISSUE TITLE
Twitter video playback issue

### ISSUE THREAD

**Issue by 100Hamburger** [baedert/corebird#776]
Hi, since a while I have problems playing videos on twitter feeds. When I hit play, the sound starts for a few seconds but the video stays black and stops. I'm on Fedora 26 x64.

**Comment by Vistaus** [comment]
Same here. It's a gstreamer issue, as we figured out in: https://github.com/baedert/corebird/issues/744

**Comment by baedert** [comment]
Running `GST_DEBUG=5 corebird` would give more info, maybe.

**Comment by Vistaus** [comment]
GST_DEBUG=5 corebird doesn't seem to launch Corebird :/

**Comment by baedert** [comment]
But just `corebird` works?

**Comment by Vistaus** [comment]
Yes.

**Comment by baedert** [comment]
I guess `corebird --gst-debug-level=5` should also work.

**Comment by Vistaus** [comment]
It works, but there's waaaaay too much output. I can't copy that all. Isn't there a way to dump the output of that to a text/log file?

**Comment by baedert** [comment]
You can either try to use a lower number than 5 or try `corebird --gst-debug-level=5 --gst-debug-no-color >> log.txt 2>&1`

**Comment by Vistaus** [comment]
That worked! I couldn't sufficiently copy-and-paste it somewhere so I've uploaded the whole log: https://file.io/SwDZca

**Comment by baedert** [comment]
Does
```
gst-play-1.0 --videosink=gtksink https://video.twimg.com/ext_tw_video/756163597126946817/pu/pl/240x240/naBpspVGzCKouV2Z.m3u8
```
work or print any error?

**Comment by Vistaus** [comment]
That works fine, no errors or anything.

**Comment by zhou0** [comment]
same issue on FreeBSD12-current.

**Comment by baedert** [comment]
Looks like this is a problem when using ffmpeg 3.4: https://bugzilla.gnome.org/show_bug.cgi?id=789193

**Comment by Vistaus** [comment]
That could indeed be the case for the person who opened this issue, but Solus reports that *I* am using ffmpeg 3.3.4

**Comment by baedert** [comment]
Downgrading to ffmpeg 3.3.4 on Arch makes it work again for me.

Can you try running agian with `--gst-debug-level=3` and checking if the output is similar to https://gist.github.com/baedert/12aa2b5eea45966e88f0af5d4bce8d93?

**Comment by Vistaus** [comment]
For some reason, every video works fine now. So this problem seems very random. Will try again tomorrow and if it happens again, I'll compare it to your output.
