### ISSUE TITLE
git master fails to build because of missing data.h

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#777]
Trying to build latest git master fails because of a missing data.h

`make[3]: Entering directory '/builddir/build/BUILD/corebird-7b85eca3446de999cf68f80f3254ab4392515367/src'
  CC       libtl/libtweetlength.lo
make[3]: Leaving directory '/builddir/build/BUILD/corebird-7b85eca3446de999cf68f80f3254ab4392515367/src'
libtl/libtweetlength.c:19:10: fatal error: data.h: No such file or directory
 #include "data.h"
          ^~~~~~~~
compilation terminated.`

**Comment by Vistaus** [comment]
What distro are you running? And what version of Vala?
