### ISSUE TITLE
Settings schema 'org.gtk.Settings.EmojiChooser' is not installed

### ISSUE THREAD

**Issue by d9h20f** [baedert/corebird#781]
Every time I try to tweet, Corebird 1.7.1 crashes with
`(corebird:9049): GLib-GIO-ERROR **: Settings schema 'org.gtk.Settings.EmojiChooser' is not installed`

(using openSUSE Tumbleweed)

**Comment by baedert** [comment]
Installed using the distro package? What gtk+ version?

**Comment by baedert** [comment]
Any chance you could test that fix? Could make a good 1.7.2 with that other potential-crasher fix.

**Comment by d9h20f** [comment]
GNOME 3.26.1, GTK 3.22.24. Thanks for the quick fix, I could check it once it's released. I do wonder why this Emoji Chooser schema isn't installed, and I can't find anyone else with this problem.
