### ISSUE TITLE
140 characters in tweet restriction

### ISSUE THREAD

**Issue by vollknorke1337** [baedert/corebird#790]
Hello,

since a few days Twitter allows 280 characters instead of 140.
Will this be fixed?

**Comment by Vistaus** [comment]
This has already been fixed: https://github.com/baedert/corebird/commit/d3cc0b068b4f3b1d0d97e4bd7c9e723d002636c1

Next time please use the filter function before you report an issue 'cause this had been reported multiple times already and each of them would've answered your question.

https://github.com/baedert/corebird/issues/788
https://github.com/baedert/corebird/issues/785
https://github.com/baedert/corebird/issues/780

**Comment by vollknorke1337** [comment]
Sorry. I'm new to Github. 
Thank you for your awesome client! :)

**Comment by Vistaus** [comment]
Welcome to GitHub then ;)

But don't thank me for Corebird, thank @baedert, he does all the programming, I'm just here to help answer questions and stuff :)
