### ISSUE TITLE
Quoting Retweets

### ISSUE THREAD

**Issue by vollknorke1337** [baedert/corebird#791]
Hey there,

Twitter allows to qoute the Tweet when retweeting and composing an own tweet in addition to the retweet.
Corebird doesn't support that for now. Will this be fixed?

**Comment by Vistaus** [comment]
Corebird already supports that. Click the arrow button on a tweet and click on Quote Tweet.

**Comment by vollknorke1337** [comment]
And also here a thank you :+1:
