### ISSUE TITLE
[Wishlist] Suppress notification popups

### ISSUE THREAD

**Issue by eddelbuettel** [baedert/corebird#792]
[ Apologies if this has been asked before, I searched and did not find a prior discussion but may have missed one, of course. ]

I run corebird on several machines, think home/work/laptop.  I also follow twitter pretty closely and get notifcation anyway via pushbullet.  So I would *love* to run corebird in 'do not send popups, ever' mode.

Having said that, I also feel a wee bit silly as part of me things that the window manager / desktop should be able to handle this, but there too I failed to find an option.

Running 1.7.2 via the contributed PPA on Ubuntu 17.04 under Unity.

**Comment by Vistaus** [comment]
You can uncheck all of the notification options in the Corebird settings. Doesn't that solve your problem?

**Comment by eddelbuettel** [comment]
I am pretty sure that was the first thing I looked for.  And failed.  Hm.
