### ISSUE TITLE
Option to disable logging messages

### ISSUE THREAD

**Issue by Noxbru** [baedert/corebird#793]
The current behaviour of corebird floods completely the journal.

Please, add an option to disable logging general messages so that the journal can stay clear.

**Comment by Vistaus** [comment]
It doesn't flood my journal. Also, AFAIK that's a system-wide setting (Solus recently disabled logging to the journal).

What distribution, distribution version and Corebird version do you use?

**Comment by Noxbru** [comment]
Hi,

I am using Arch linux with corebird-git from AUR at commit https://github.com/baedert/corebird/commit/d3cc0b068b4f3b1d0d97e4bd7c9e723d002636c1 

I have just started my laptop (uptime says that it has been up 12 min) and I already have 232 lines from corebird in my logs (checked with journalctl -b0 | grep corebird | wc -l)

Some excerpts:
```
Nov 20 10:47:23 Archibald corebird[1015]: DefaultTimeline.vala:25: Unread count for @Noxbru from 0 to 1
Nov 20 10:47:23 Archibald corebird[1015]: DefaultTimeline.vala:27: New unread count for @Noxbru: 1
Nov 20 10:47:23 Archibald corebird[1015]: BadgeRadioButton.vala:23: New show_badge value: true
Nov 20 10:47:25 Archibald corebird[1015]: 1 HEARTBEAT (Noxbru) 10:47:25
Nov 20 10:47:28 Archibald corebird[1015]: 1 HEARTBEAT (Noxbru) 10:47:28
Nov 20 10:47:49 Archibald corebird[1015]: 1 HEARTBEAT (Noxbru) 10:47:49
Nov 20 10:47:56 Archibald corebird[1015]: 1 HEARTBEAT (Noxbru) 10:47:56
Nov 20 10:47:57 Archibald corebird[1015]: 1 HEARTBEAT (Noxbru) 10:47:57
Nov 20 10:48:00 Archibald corebird[1015]: 1 HEARTBEAT (Noxbru) 10:48:00
```

**Comment by baedert** [comment]
Those are debugging messages, they only get printed of you built corebird with `--enable-debug` or set the `G_MESSAGES_DEBUG` env var to either `corebird` or `all`. I have no problem running it without getting debugging output.

**Comment by Noxbru** [comment]
Hi,

I have just rebuilt corebird from master and I still get them. I have checked that the PKGBUILD does not have the option `--enable-debug` so it seems that it is on by default.

Here's the PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=corebird-git#n37

**Comment by baedert** [comment]
That PKGBUILD uses the  meson build which [defaults to debugging](https://github.com/baedert/corebird/blob/master/meson.build#L4). `--enable-debug` is the option for the autotools build.

**Comment by Noxbru** [comment]
So, we are getting different behaviour depending if we use autotools or meson?

**Comment by baedert** [comment]
Yes. It's not like I ever advertised the meson build though.

**Comment by Noxbru** [comment]
I'm not the maintainer of the PKGBUILD so I don't know why (s)he chose to change it to meson.

Closing. (Although probably it would be good to make meson and autotools compile corebird both in the same way)
