### ISSUE TITLE
Typing DM causes window to stretch

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#796]
When typing a tweet, the text wraps as expected in the text box.

When typing a Direct Message, the text just keeps extending the width of the browser and doesn't wrap, even when there are plenty of spaces that it could wrap at. At some arbitrary point (around 50% of my screen size) it stops expanding and starts wrapping for some reason.

As with bug #514, you can't reduce the size of the window. Unlike the other bug, if you manually extend the window when it has hit 50% and wrapped then you can't shrink it again (the previously wrapped text fills the available space on the previous line and then won't wrap back again).

Deleting text so when you've extended the window over 50% width causes the window to shrink its width by itself (back to 50% but no smaller, even if more text is deleted).

This doesn't affect DMs in the list, only typing them.

This could be related to the [Pango wrapping change](https://github.com/baedert/corebird/issues/514#issuecomment-342954042).

Version: fdd81f86a1f24ebb90ef7dae2952c2bd0cb32dc8
OS: openSUSE Tumbleweed
GTK: 3.22.25
Pango: 1.40.13

**Comment by baedert** [comment]
Sounds like it's just https://bugzilla.gnome.org/show_bug.cgi?id=766822 again (just that the workaround in corebird is gone).

**Comment by IBBoard** [comment]
Just updated to Pango 1.40.14 and it still happens, but far less than it did. Lots of words with spaces will cause a slight widening if the space lands in the wrong place. A long string of text without spaces eventually wraps in a not-completely-ridiculous way (see [this Pango bug](https://bugzilla.gnome.org/show_bug.cgi?id=131625) for the odd wrapping) but still pushes the window to 50% width.

I guess this is mainly a Pango issue, then.

**Comment by IBBoard** [comment]
Is [the UI part](https://github.com/baedert/corebird/commit/0d992c45f8c72441c7dbba0cd3e29ffb9488baa8#diff-8ffe26f11db20e2d80afeb9fe6f9e186) of the long name change necessary?

I've undone it and everything seems to work correctly with wrapping, and name completion (which I hadn't seen before in DMs) still works, even with long names.

**Comment by ValdikSS** [comment]
I'm using Pango 1.40.14 but it happens to me all the time.

**Comment by Vistaus** [comment]
Can't reproduce this with Pango 1.41 (current git master).

**Comment by ValdikSS** [comment]
Just built git master with fedora's 1.40.14-1.fc27 pango. I don't see any commits in pango git master which fix this issue.

**Comment by Vistaus** [comment]
I'm not talking about Corebird git master, I'm talking about Pango git master which is currently at 1.41 I'm using it and don't notice this issue, whereas I did encounter it with 1.40. So something has fixed it.

**Comment by ValdikSS** [comment]
Just build pango git master and ran corebird with it (made sure that git master version is used with /proc/PID/maps path) and still have this issue.

**Comment by Vistaus** [comment]
Hmm, seems to be a hit or miss then...

**Comment by ValdikSS** [comment]
It used to be fine on Fedora 25 (with corebird git master), but not on Fedora 27, to which I switched only a week ago.

**Comment by ValdikSS** [comment]
@baedert, is it possible to add workaround again until it's not fixed in upstream?
