### ISSUE TITLE
Segfault when using umlauts

### ISSUE THREAD

**Issue by adlerweb** [baedert/corebird#800]
When composing a new tweet or reply corebird consistently crashes with a segfault if I type space after a word including a umlaut (äöüß…). The problem doesn't occur if i finish the tweet without using space. The problem also occurs when pasting a text containing this pattern

Examples:
> "This is a test" -> works
> "This is a täst" -> works
> "This is a täst " -> crash

Trace
```
#0  0x00007fd9a48cfbd6 hspell_check_word (libhspell.so.0)
#1  0x00007fd9a4ad7c86 n/a (enchant_hspell.so)
#2  0x00007fd9b848214c gspell_checker_check_word (libgspell-1.so.1)
#3  0x00007fd9b847f305 n/a (libgspell-1.so.1)
#4  0x00007fd9b847f977 n/a (libgspell-1.so.1)
#5  0x00007fd9b847faa9 n/a (libgspell-1.so.1)
#6  0x00007fd9bae2acb3 n/a (libglib-2.0.so.0)
#7  0x00007fd9bae2c0be g_main_context_dispatch (libglib-2.0.so.0)
#8  0x00007fd9bae2df69 n/a (libglib-2.0.so.0)
#9  0x00007fd9bae2dfae g_main_context_iteration (libglib-2.0.so.0)
#10 0x00007fd9b94945ae g_application_run (libgio-2.0.so.0)
#11 0x00005617bc6846d4 n/a (corebird)
#12 0x00007fd9b80dcf4a __libc_start_main (libc.so.6)
#13 0x00005617bc68459a n/a (corebird)

```
Tested with corebird 1.7.3 and trunk (b298aa45815f56205e8b757a65cf2b680212f070) on arch/amd64 via AUR. Both clean installs, observed on multiple systems.

Since they where mentioned: 
* hspell 1.3 and 1.4
* enchant 2.1.2 (-2 and -3, afaik without hspell-support)
* gspell 1.6.1-2

**Comment by Vistaus** [comment]
Can't reproduce this. Not sure if you're using the German layout though. I'm using English (US, International) and I frequently use umlauts, but it never resulted in a crash. Not in the past, and not in the current trunk.

**Comment by adlerweb** [comment]
Yes, german layout, but since it also happens while pasting text this shouldn't matter.
Still duplicate of #784, so closing here.
