### ISSUE TITLE
Freezes and Crashes when typing German symbols like ä,ö,ü or ß

### ISSUE THREAD

**Issue by naums** [baedert/corebird#802]
Corebird freezes and then crashes some seconds later when typing German symbols like Umlaute (ä,ö,ü) or the ß-chracter in the Compose-Tweet dialog. This happens both when composing a new tweet as well as answering to a tweet. 

For full disclosure: I run Arch Linux ARM on Odroid C2 (aarch64). I installed Corebird 1.7.3 with a modified PKGBUILD-file from the AUR. If necessary I would test that as well on a regular x86 PC.

**Comment by naums** [comment]
Duplicate [#784](https://github.com/baedert/corebird/issues/784)

**Comment by baedert** [comment]
Enchant 2.2.0 has been released a while ago already but the arch package is still at 2.1.2. Just need to wait for that to get updated.
