### ISSUE TITLE
TLS certificate issue

### ISSUE THREAD

**Issue by Grimscythe1983** [baedert/corebird#806]
I am on Arch Linux. Corebird used to work just fine. I wanted to remove my old twitter account and add a new one. While removing the old account Corebird crashed and had to be killed manually. Unfortunately now when I open the application and click Request Pin I get a dialog box saying "Unacceptable TLS certificate".

Is there a simple way to resolve the issue? Any help would be appreciated as Corebird is just fantastic!!!

EDIT: I tried reinstalling Corebird, tried the normal AUR package and the corebird-git package, both prompt for the Unacceptable TLS certificate.

**Comment by baedert** [comment]
The only thing I can tell you about this is that Corebird doesn't do anything with TLS certificates so the problem must be *somewhere* else. I see that error message (or a similar one) now and then when searching, but it fixes itself on the next retry.

**Comment by Grimscythe1983** [comment]
Unfortunately after retrying multiple times, the message is still there. Ok I'll resort to Arch forums in this case. Thank you for your help!
