### ISSUE TITLE
font client

### ISSUE THREAD

**Issue by GiovanniSM20** [baedert/corebird#808]
i'm using arch linux and would like to know which font to install because some parts of the client are not completely loaded for lack of font... :(

**Comment by baedert** [comment]
Um, depends? fontconfig will pick a font that contains the characters it's trying to display as far as I know, so it depends on what text you are talking about.

**Comment by GiovanniSM20** [comment]
as you can see...

![captura de tela_2018-01-19_07-27-20](https://user-images.githubusercontent.com/7796661/35143958-3e5664ae-fcea-11e7-9185-cf62f8c8fdad.png)

**Comment by baedert** [comment]
That's an emoji. Install an emoji font.

**Comment by GiovanniSM20** [comment]
tks!

**Comment by GiovanniSM20** [comment]
tks!
