### ISSUE TITLE
with flatpak corebird 1.7.3 is there any way to increase font size ?

### ISSUE THREAD

**Issue by GrangeBeach** [baedert/corebird#809]
font just too small to read on hi res screen

**Comment by baedert** [comment]
There is no way in Corebird to increase the font size. If your desktop font size is too small, change that. If Corebird picks up the correct desktop font size outside of flatpak but not inside, that's probably a flatpak bug. If It does not pick up that your screen is a hidpi screen, i.e. everything should be scaled by a factor of 2, that's also a flatpak bug.
