### ISSUE TITLE
Font size?

### ISSUE THREAD

**Issue by nardev** [baedert/corebird#810]
Is it possible to increase font size???

The image in 30-50% of monitor width is so bit and the text is being lost in between... Would be nice to add that to a settings.

**Comment by Vistaus** [comment]
That's not possible and not planned either: https://github.com/baedert/corebird/issues/155

**Comment by nardev** [comment]
I just saw that people have been asking for such an option for years.. So shameful ... i really don't see a reason for that.. i'll try to make my patch.

Don't like when nice project is lead by ignorant people.

**Comment by Vistaus** [comment]
Person, not people.

I disagree with your statement though.

**Comment by nardev** [comment]
LOL

**Comment by nardev** [comment]
Well, just made it :D 

If i get some time i'll tune it with nicer font ..  thnx..

**Comment by gnumdk** [comment]
>The only solution is to increase the font size of all apps through System Settings.
@Vistaus Why not but corebird is not respecting system settings font size. Tweets should use "Documents font size" but it does not.

**Comment by feoh** [comment]
That's my issue too. I have my system fonts set large and yet when Corebird starts the text is super unreadably tiny.

Not everyone is blessed with 20/20 vision you know, one day you'll get older and then you'll be in the same boat with partially blind people like me :)

**Comment by feoh** [comment]
>  as Corebird is dead. So you might as well migrate to twitter.com or mobile.twitter.com, where you can set custom zoom per tab which circumvents the font size issue.

Sorry to hear that Corebird is another victim of Twitter's awful decision to destroy its client ecosystem. Way to bite the hand that feeds you, Twitter :(

Thanks for the recommen dation, I've pretty much done that, although I'm stubborn so I turned the website for Twitter/Tweetdeck into native apps with [nativefier](https://github.com/jiahaog/Nativefier) so I'm not stuck flipping tabs in a web browser :)
