### ISSUE TITLE
Prevent deletion of Lists

### ISSUE THREAD

**Issue by thomasbilk** [baedert/corebird#811]
Corebird makes it too easy to delete a complete list by accident as it has happened to me twice now. To accidentally delete a list open it and press space twice. No warning no going back. 

I guess the reason is that the delete button is unnecessarily the prominent and focused first button in the list view. So pressing it by pressing `space` triggers a deletion of the entire carefully curated list. If there is any warning it will not be shown. 

The delete button should be moved or better removed.

**Comment by baedert** [comment]
Hitting space just shows the menu item asking for confirmation but still: nice find. Kinda worsened by the delete button being focused without being visible to the user...
