### ISSUE TITLE
Allow user to change spell checking language of new tweets

### ISSUE THREAD

**Issue by medeotl** [baedert/corebird#812]
At the moment Corebird spell check only in one language (the system one I guess), but many of us tweet in different languages. Please enable us to select in some way the language of the tweet (and set the correct spell check for it)

**Comment by wimpunk** [comment]
I would like this option to...

**Comment by mDfRg** [comment]
Is there a config file perhaps to change it?

**Comment by Vistaus** [comment]
@mDfRg What do you want to change, the list of manually added words?

**Comment by mDfRg** [comment]
No I want to change the spellcheck to my native language which is different from host OS.

**Comment by Vistaus** [comment]
@mDfRg In that case you have to ditch the Flatpak version and compile Corebird from git as it's only available here right now until a new version is released: https://github.com/baedert/corebird/commit/87bc8519968ed8f4ab044afaa09d9f9cefd7f6ea

Then you can just right-click in the Compose Tweet screen and change the language (you do need to have the dictionary of your package installed though - check your package manager).

**Comment by mDfRg** [comment]
87bc851 is precisely what I'm looking for. Unfortunately, from what I understand it's not possible for me to compile as I use Ubuntu 16.04 which has old 3.18 GTK version. When will it be released?

**Comment by Vistaus** [comment]
@mDfRg The GTK requirement has been bumped so a new version of Corebird will most likely also require something newer than GTK 3.18. As for when it will be released: only @baedert can tell you that :)

**Comment by mDfRg** [comment]
It already requires >3.20, so no heaven for me :). I'm gonna stick with my hack for time being, just wanted to share my workaround.

**Comment by medeotl** [comment]
I think the patch will be released with the new version, and since you use the flatpak version you will receive it as soon as it will be released. When the new version will be released is up to @baedert
