### ISSUE TITLE
[Feature] Emoji support

### ISSUE THREAD

**Issue by BloodyIron** [baedert/corebird#814]
Any chance we can get Emoji support? As in, when composing.

**Comment by baedert** [comment]
It's already there.

**Comment by BloodyIron** [comment]
Composing a tweet has no options for emoji, and I can't find anything about this in the program. So it's "where"???

**Comment by baedert** [comment]
There's an emoji button in the compose window, given a recent enough gtk+ version.

**Comment by Vistaus** [comment]
Composing a tweet has no options for emoji, and I can't find anything about this in the program. So it's "where"???

![screenshot_20180208_164445](https://user-images.githubusercontent.com/1716229/35982387-fa19196a-0cef-11e8-9958-536df1697026.png)

You need to have an emoji font installed though. Also, as baedert points out, you need to have a recent enough GTK+ version.

**Comment by BloodyIron** [comment]
Which GTK+ version do I need? Not sure why I wouldn't have a new enough one, how odd... Shouldn't this be a dependency requirement of sorts?

**Comment by baedert** [comment]
Looks like you need gtk 3.22.19 (and corebird 1.7.3), but actually rendering the emojis in color depends on some fontconfig/cairo sutff that I think at least some Ubuntu version didn't ship.

**Comment by diddledan** [comment]
None of the currently stable Ubuntu releases include color-emoji support, though the Snap package _does_ ;-p </blowing my own trumpet slash shameless self-promotion>
