### ISSUE TITLE
[Feature] "Dark" theme

### ISSUE THREAD

**Issue by BloodyIron** [baedert/corebird#815]
Any chance we could get a "dark" mode, so we can save our eyeballs from radiation? Seriously though, it would be appreciated. :)

**Comment by Vistaus** [comment]
You can enable the Dark Theme setting in GNOME Tweak Tool on the Appearance tab.

**Comment by BloodyIron** [comment]
But I'm not using GNOME, I was hoping for something built-into corebird?

**Comment by Vistaus** [comment]
GNOME Tweak Tool also works fine outside of GNOME. Most GTK apps have no built-in setting for dark theme as they are controlled by the Dark Theme setting of GNOME Tweak Tool. If you really don't want GNOME Tweak Tool, then you can also use dconf-editor.

**Comment by mr-blobbyyy** [comment]
The "arc-dark" theme in your appearance settings for your particular distro is your best bet. Just search your favorite repo for [arc-theme](https://packages.ubuntu.com/artful/arc-theme) or [arc-gtk-theme](https://www.archlinux.org/packages/community/any/arc-gtk-theme/) and then the dark theme should then be available in your appearance settings.

**Comment by Vistaus** [comment]
@mr-blobbyyy The best dark theme "bet" is the one the user prefers. Not everyone has the same taste.

**Comment by baedert** [comment]
The way to get a dark theme is to use a dark theme everywhere. I'm not going to ship an entirely separate dark theme in corebird.

**Comment by BloodyIron** [comment]
Forcing people to use a dark theme everywhere just so corebird can have a dark theme, is very short sighted. I for one don't want my entire UI to be dark, and I can't fathom why you think that's going to work for everyone else.

**Comment by Vistaus** [comment]
@BloodyIron It's going to work for everyone else because it already does: iOS, Android, Windows 10... they all have a Dark Theme option which covers the entire UI and most, if not all, apps and except for a couple of Android apps, none of them have the ability to choose b/w a light and dark theme on a per-app basis.

**Comment by baedert** [comment]
I don't really see what makes a twitter client so special that you'd want it to look different from everything else, or why other applications don't cause any radiation to your eyeballs, but if you really want another theme you can do that for any gtk3 application by simply setting the `GTK_THEME` environment variable.

**Comment by Vistaus** [comment]
@baedert I fully agree with you.

**Comment by dcnblues** [comment]
Yeah, and in the app homepage, if dark themes are available, smart developers will include a screenshot that lets new users know there's an option that won't create a gag reflex. Plenty of new users looking for non wysiwyg interfaces.
