### ISSUE TITLE
[Feature] System tray icon

### ISSUE THREAD

**Issue by BloodyIron** [baedert/corebird#816]
I really would like it if I could get a system tray icon for this app, so I can minimize it to systray and get notifications through the environment. This may be tied to #702 but I am not sure?

**Comment by baedert** [comment]
Yes it is but a tray icon is not an option, as discussed several times in older tickets.

**Comment by BloodyIron** [comment]
Yeah, just read #111 and I have to say it's ridiculous this is just being shut down as a concept, but whatever man.

**Comment by Vistaus** [comment]
@BloodyIron I know you're using a different environment, but keep in mind that Corebird is a GTK app. And there is no system tray anymore in GTK-based desktops (including GNOME) - the tray was removed from GTK some time ago.

**Comment by BloodyIron** [comment]
Well that's tragic :(

**Comment by soundgnome** [comment]
Depending on which desktop you're using [kdocker](https://github.com/user-none/KDocker) may provide a workaround. It's in the Ubuntu repo, probably other distros too. Just tried it on XFCE and seems to work well.

**Comment by fmneto** [comment]
@Vistaus that's not an excuse. I am using GNOME 3.28 right now and applications do have a tray icon available (see the attached screenshot). 

![screenshot from 2018-04-23 21-41-22](https://user-images.githubusercontent.com/2249575/39149437-5475dfc2-473f-11e8-8fc3-72fbf743a086.png)

**Comment by fmneto** [comment]
@Vistaus still you can't use the "there is no tray" excuse. It's lame. Just admit you don't want to do it. 

Hopefully if somebody else does it you'll accept a merge.

**Comment by Vistaus** [comment]
@fmneto I don't think it's lame.
But just a heads-up: I'm not the Corebird dev; @baedert is. But he has already said multiple times that he's not going to implement it, not even if somebody does a PR, and I fully agree with him.

**Comment by fmneto** [comment]
@Vistaus that's just sad. I really like corebird but my screen is not big enough that I can afford to just leave it open.

Could you post a link to where @baedert  said he isn't going to do it and why?

And I didn't mean to imply you're the dev, although it may have looked that way; sorry about that.

**Comment by Vistaus** [comment]
@fmneto He said so in this thread: https://github.com/baedert/corebird/issues/816#issuecomment-364140515
But also here: https://github.com/baedert/corebird/issues/111#issuecomment-35016695
And there are a few other tickets on the subject as well.

**Comment by fmneto** [comment]
@Vistaus thanks for the link. It clarifies the problem, although it does not justify losing an important functionality. It's a big loss and a huge factor against more people choosing to use corebird. 

Not to mention that although @baedert expressed to be "hoping for someone to write a shell extension", he also seems to have no intention of making the needed data available for that to work. And _that_'s what I think is lame.  I don't know if that has changed since then, but still.

I know this is pretty much a closed topic (at least for the time being), but @baedert, if you are reading this, what would it take for you to change your mind and either implement it or accept a PR for this?

(I don't really expect an answer, I'm just leaving the question here for posterity).

**Comment by BloodyIron** [comment]
The only tangible reasoning I've been able to gleam from this is...

"From a user perspective it's just very weird that closing the window does not really close the window"

And while it is definitely important to consider UX (User Experience), A LOT, and I really do mean A LOT, of programs already minimize to system tray when closing. It's such a long list I'm not even going to bother making a comprehensive list. But modern tools like Riot, Remmina, STEAM, and so much more already do close to system tray when hitting "x" or "closing" the window.

So the argument that it is bad UX to go to system tray is bunk. Not only that, this can be completely solved by very easy methods, consider a few options...

1. When you hit X, a dialogue comes up "Minimize or Quit application" (this is how Mumble handles this)
2. Have a setting that you can toggle the default behaviour between quit/close to system tray

Honestly, in this day and age, we have so many applications open, to expect users to keep yet another application open just to read contents is unacceptable, and is most certainly far more disruptive to the UX than a program minimizing instead of quitting. It does not look like @baedert has considered the negative implications of not having a system tray icon feature.

I opened this feature request because it is a deal breaker for me. I work on so many different things, expecting me to have yet another window open just to check notifications is such a significant inconvenience, that I just won't use corebird. And clearly I am not the only one.

So, we can remain being ornery about not implementing a system tray feature, or we can explore how that can work in practice (as in, implement a system tray feature).

**Comment by fmneto** [comment]
@BloodyIron I couldn't have said it any better. As I said I really like corebird. I've been through countless ways of using twitter until I found it and finally considered I was done searching. 

This *one* thing, though, this lack of usability, and upstream's attitude towards it, really ruin it. I'm still using, but i'm on the lookout for a better alternative.

Naturally, it's his program and he can do whatever he wants with it. And since I'm not really much of a programmer myself, I can't just branch it and create a version that behaves like I'd like it to. I could go on and on, but to be honest I've wasted way more time than I would have liked on this discussion.

**Comment by Vistaus** [comment]
@BloodyIron If your only goal is to receive notifications, then why don't you just run

> corebird --start-service

at boot (or after boot, whatever your prefer)?

That way, Corebird only checks for notifications in the background without actually opening the window.

**Comment by BloodyIron** [comment]
@Vistaus because I want more than just _only_ notifications. I want to click on the system tray icon to bring it up, and then minimize it to system tray, just like I do for STEAM, Riot, and so many other tools. What you've proposed addresses only part of my particular functional need.

**Comment by Vistaus** [comment]
@BloodyIron Please also check my edit ;)

**Comment by baedert** [comment]
*sigh* I'm not gonna read all that.

As long as I'm the only regular developer on this project, I won't support or maintain things I don't regularly use myself. I can't help people if they have problems if I don't use it and I can't test it either. I also clearly stated in the bug report linked above that I have already written tray icon support and subsequently removed it (and I was not drunk or sleepwalking, I swear) *5 years ago* so why exactly would I suddenly add it now?

**Comment by Vistaus** [comment]
@baedert +1

**Comment by fmneto** [comment]
@baedert Hey man it's you app, do whatever you want with it. We are all here because we *like* it. I like it **a lot**. And I would love to see it getting improvements to make it even better. Things that would make using it even more enjoyable. 

But, hey, it's your app.

**Comment by BloodyIron** [comment]
@baedert why even have an "issues" section of github if you're not even going to read what people care about? Seriously, if that's the kind of attitude you're going to take when we bother to put the time into crafting well thought out statements, then you might as well just turn the "issues" section off.

**Comment by baedert** [comment]
I have closed this issue ages ago and said multiple times that why I'm not going to support it (see above). I'm not going to come home and read the 12 comments you three people wrote over a topic I've stopped worrying about years ago. I told you what the problem is, it's understandable and there is no reason to be childish about it. The issue tracker stays open because people also have problems I support and can fix.

**Comment by BloodyIron** [comment]
I'm not being childish about it, I've spent my time explaining why your perspective is completely the opposite of how system tray functionality works in so many other applications (namely, the significant majority). Again, if you don't want to hear what people have to say about Corebird, then turn the issue section off. I don't care if you closed the issue.

Whatever man, you want to be an ignoramus about this and literally ignore what people have to say about corebird, then so be it. I'm done here, you clearly have zero interest in actually having a discussion about this, and that's wilful ignorance. This is the kind of pig-headed attitude that has always poisoned the open source community, and I'm glad I don't have to work with you.

**Comment by Vistaus** [comment]
@baedert 
> I'm not going to come home and read the 12 comments you three people wrote over a topic I've stopped worrying about years ago.

I defended your POV, so no need to include me in your stance :wink:

**Comment by metal3d** [comment]
Sorry to say that but I don't have any tray icon for CoreBird, using Fedora 27/28, Gnome, and so on... all other app have one.

I have a hard time understanding why all the apps I developed do not worry about creating a trayicon and why this fabulous, well built program does not have that tiny feature that would make it perfect :)

**Comment by Vistaus** [comment]
@metal3d But even if Timm eventually wanted to, it's far too late now anyway to implement it anyway 'cause Corebird will soon stop working: https://www.patreon.com/posts/corebirds-future-18921328

**Comment by metal3d** [comment]
Yes I saw that a few days ago... didn't know that Twitter is so bad...
