### ISSUE TITLE
Text counter not the same as web .

### ISSUE THREAD

**Issue by HybridGlucose** [baedert/corebird#817]
![2018-02-20 02-11-25](https://user-images.githubusercontent.com/1411400/36391913-99f0ccac-15e3-11e8-8d6e-02d640aeb8e4.png)

The same text but not the same value of text counter.
So that when I sent a twitter in the application, the application can click but have not any action.

**Comment by Vistaus** [comment]
I think this is related to https://github.com/baedert/corebird/issues/794

**Comment by baedert** [comment]
It's a duplicate of #794
