### ISSUE TITLE
Flatpak'd Corebird doesn't use the existing translations

### ISSUE THREAD

**Issue by kostich** [baedert/corebird#819]
Latest Corebird flatpak doesn't use the existing translations. Instead, everything is displayed in English.

```
$ flatpak info org.baedert.corebird
Ref: app/org.baedert.corebird/x86_64/stable
ID: org.baedert.corebird
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2017-11-19 08:36:59 +0000
Subject: Update to 1.7.3 (bba63429)
Commit: ae7ae0ef17423054f5697331566fd392dabf20aef0c28e8de0cbec1630a4c53f
Parent: 8c1cb822b79b49588e378976d2ffa6d44f2a831fb62f4c7c551e587d3712473d
Location: /var/lib/flatpak/app/org.baedert.corebird/x86_64/stable/ae7ae0ef17423054f5697331566fd392dabf20aef0c28e8de0cbec1630a4c53f
Installed size: 16,5 MB
Runtime: org.gnome.Platform/x86_64/3.26
```

Host is Fedora Atomic Workstation 27.

I've poked a bit in `/var/lib/flatpak/app/org.baedert.corebird/x86_64/stable/some-long-uid/files/share/locale/` and it seems that all the symlinks pointing to the translations are broken. No .mo files in the ../../runtime/locale/*/.

Are the translations in a separate flatpak/runtime?

**Comment by baedert** [comment]
It's certainly not doing anything special in that regard. Do other flatpak apps work? How did you change the locale?

**Comment by kostich** [comment]
Other Flatpaks are using my system locale correctly. I haven't manually changed my locale inside the app in any way.

**Comment by baedert** [comment]
Yes but how did you change your system locale? Does `locale` print what you'd expect? And did you change your locale to the current value before or after installing corebird? Locales should be downloaded automatically by flatpak if available and not installed.

**Comment by kostich** [comment]
Locale was setup during the initial installation of Fedora Atomic Workstation. Command `locale` returns expected environment variables for my language. I haven't changed the locale in any way before and after installing Corebird.

I've seen the locales downloaded by the flatpak, in the terminal output. I will try to uninstall and then install to capture the terminal outuput.

**Comment by kostich** [comment]
This is the output when reinstalling:
```
[user@box ~]$ flatpak uninstall org.baedert.corebird
Uninstalling: org.baedert.corebird/x86_64/stable
Uninstalling: org.baedert.corebird.Locale/x86_64/stable
[user@box ~]$ flatpak install flathub org.baedert.corebird
Installing: org.baedert.corebird/x86_64/stable from flathub
[####################] 1 delta parts, 3 loose fetched; 6941 KiB transferred in 7 seconds
Installing: org.baedert.corebird.Locale/x86_64/stable from flathub
[####################] 1 delta parts, 1 loose fetched; 91 KiB transferred in 0 seconds
```

It seems that Corebird is looking for the translations in the wrong place. The symlink for my system locale points to:

```/var/lib/flatpak/app/org.baedert.corebird/x86_64/stable/ae7ae0ef17423054f5697331566fd392dabf20aef0c28e8de0cbec1630a4c53f/files/share/locale/sr -> ../../share/runtime/locale/sr/share/sr```

But there's nothing in `../../share/runtime/locale/sr/share/sr`. The translation is instead located in the other path:

```
/var/lib/flatpak/runtime/org.baedert.corebird.Locale/x86_64/stable/62a3e91eea18917274040a207d89c2d76a72f6655ece33d46c917175314d68ff/files/sr/share/sr/
```

Quite a different path.

**Comment by baedert** [comment]
I'm not an expert on this topic (inside or outside of flatpak), but since corebird doesn't do anything special here, it seems like this should be more directed to the flatpak developers. I won' t be around for much longer this weekend, so if you want to get this fixed, would be nice if you could open a bug report at flatpak instead, with the same information as here. The people there are usually responsive and should know about this of course. Otherwise I'll look into it next week.

**Comment by kostich** [comment]
Opened an issue at https://github.com/flathub/flathub/issues/277 . I'll close this issue now.

Thanks for your hard work on Corebird!
