### ISSUE TITLE
Syntax error near unexpected token `gtksink,' while attempting to develop on Windows

### ISSUE THREAD

**Issue by robinhood2014** [baedert/corebird#820]
This may be a duplicate of issue [629](https://github.com/baedert/corebird/issues/629), but I only just encountered the error now.

I'm unable to build corebird on Windows 10 through MSYS. I've installed all the necessary dependencies, including gstreamer, but the `./autogen.sh --prefix=/usr` command I issue in MSYS generates the following error:

`./configure: line 13281: syntax error near unexpected token 'gtksink,'`
`./configure: line 13281: '  GST_ELEMENT_CHECK(gtksink, 1.0, , )'`

I tried running `./configure --prefix=/usr --disable-gst-check` (because by this time the necessary "configure" app was there), but the extra parameter had no effect whatsoever; the error remains. I then checked out IBBoard's patch, but it no longer exists.

Is it possible to fix this problem for compiling on Windows?

**Comment by baedert** [comment]
Don't you have to pass `--disable-gst-check` to `autogen.sh` again so a different configure script gets generated?

**Comment by robinhood2014** [comment]
That seems to have passed the configure stage. But now, on the make stage, I get another error:
`C:\msys64\mingw64\bin\msgfmt.exe: cannot locate ITS rules for org.baedert.corebird.appdata.xml.in`
`make[3]: *** [Makefile:835: org.baedert.corebird.appdata.xml] Error 1`
`make[3]: Leaving directory '/home/donni/corebird/data'`
`make[2]: *** [Makefile:553: all-recursive] Error 1`
`make[2]: Leaving directory '/home/donni/corebird/data'`
`make[1]: *** [Makefile:451: all-recursive] Error 1`
`make[1]: Leaving directory '/home/donni/corebird'`
`make: *** [Makefile:383: all] Error 2`

**Comment by baedert** [comment]
You will have to figure out all of this yourself, I have never compiled Corebird on windows and don't know of anyone else who has.

**Comment by Vistaus** [comment]
I currently also experience this issue while compiling the latest git master on Linux.

**Comment by baedert** [comment]
I removed the gtksink check in the `cb-1.7` branch since it breaks apparently and doesn't exist in the master branch (i.e. meson build) anyway.
