### ISSUE TITLE
"Could not create gtksink. Need gst-plugins-bad >= 1.6" message with gstreamer1.0-plugins-bad version 1.14.0-1 installed

### ISSUE THREAD

**Issue by benalb** [baedert/corebird#821]
Using devuan (https://devuan.org/) a debian derivative, corebird does not play videos with the message:
Could not create gtksink. Need gst-plugins-bad >= 1.6, althought the 1.14 version is installed.

I've uninstalled the package from distro and compiled it without errors, but the result is the same, no video played with the "could not create gtksink..." message.

Also, tried to delete the ~./cache/gstreamer-1.0/ dir, same error.

**Comment by baedert** [comment]
So, generally you don't just need gstreamer-plugins-bad in at least version 1.6, but it also needs the gtk support compiled in. 

I only have the 1.12 gstreamer packages installed here but IRC gtksink moved to plugins-bad recently: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-gtksink.html `gst-inspect-1.0 gtksink` still says it's from -bad here.

**Comment by benalb** [comment]
Ok, the key here is the "gtk support", I've installed gstreamer1.0-gtk3 and videos are played ok. 
thank you very much. 
I will close the issue.
