### ISSUE TITLE
App doesn't open on Arch Linux

### ISSUE THREAD

**Issue by spacekookie** [baedert/corebird#824]
Calling `corebird`, the app crashes immediately with the following error:

```
corebird: error while loading shared libraries: libgspell-1.so.1: cannot open shared object file: No such file or directory
```

Even though the library is installed:

```
❤ (rayya) ~> ll /usr/lib/libgspell-1.so*
lrwxrwxrwx 1 root root   20 Mar 14 21:18 /usr/lib/libgspell-1.so -> libgspell-1.so.2.3.0*
lrwxrwxrwx 1 root root   20 Mar 14 21:18 /usr/lib/libgspell-1.so.2 -> libgspell-1.so.2.3.0*
-rwxr-xr-x 1 root root 140K Mar 14 21:18 /usr/lib/libgspell-1.so.2.3.0*
 ```

I'm using the corebird-git AUR package

**Comment by baedert** [comment]
yeah apparently there was *some* change to gspell or the gspell arch package. You'll just need to rebuild it I guess: https://github.com/Antergos/antergos-packages/issues/302

Though the corebird-git package doesn't work anymore I guess since it builds master and should built `cb-1.7` instead.
