### ISSUE TITLE
Unable to open in Manjaro after latest update

### ISSUE THREAD

**Issue by ecronicar** [baedert/corebird#827]
After latest update pack of Manjaro KDE the Corebird app has become inaccessible. This is the Konsole output: 

$ corebird
corebird: error while loading shared libraries: libgspell-1.so.1: cannot open shared object file: No such file or directory

**Comment by Vistaus** [comment]
There were changes to the gspell package, see: https://github.com/baedert/corebird/issues/824

**Comment by baedert** [comment]
Yes, see #824
