### ISSUE TITLE
Scrolling is laggy in Next

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#830]
I finally got round to building a new enough version of GTK to make Next build.
It looks good from the bits that I've looked at so far, but scrolling seems to be laggy.
If I scroll up and down then it feels slow, but if I grab the scrollbar and quickly move the mouse up and down then the bar definitely gets left behind. I don't see the same behaviour in Corebird 1.7.4, where the scrollbar is responsive.

Running plain Corebird 02d13253 against GTK4 v3.93+git_cfa0480

**Comment by baedert** [comment]
That's due to the blurred outset shadows, but the fix needs to be in gtk+ and not corebird (if and only if those outset shadows stay at all since giving the rows an explicit background color is basically incompatible with every theme in existence).

**Comment by baedert** [comment]
I mean, that's a known problem, but it also depends on the renderer you are using and my comment above relied on the fact that you end up with the opengl renderer. The other two renderers should be worse in this particular case though.
