### ISSUE TITLE
Mouse-wheel scroll doesn't work on tweet view in Next

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#831]
In Master (02d1325), if you double-click on a tweet to view just that tweet and its replies then scrolling with the mouse wheel doesn't always work.

 * If the tweet has replies and you hover over the tweets and scroll down then nothing happens
 * If it has replies and you hover over the scroll bar then it scrolls down
 * If it replies to earlier tweets then scrolling up reveals those tweets
 * BUT once you scroll up then scrolling down again stops working (not that it won't hide it, but that if the thread is now longer than your window then it won't scroll down)

**Comment by Vistaus** [comment]
Known bug: https://github.com/baedert/corebird/issues/804#issuecomment-354663016
"Scrolling in the tweet info page doesn't work. This is more tricky and I need to somehow get an answer from the person who implemented the scrolling event handler in gtk..."

**Comment by IBBoard** [comment]
Sorry I missed that.
