### ISSUE TITLE
Can't interact with tweets from timeline in Next?

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#832]
Probably more of a question about a design decision rather than a bug.

In testing Next, I've not been able to find how to RT or Like a post without double-clicking on it and going to the details view. Since that potentially loads more tweets (conversation chains), which adds requests, then that seems wasteful.

Am I missing something, or is it not possible to RT and Like in the way that we used to with Corebird 1.7?

**Comment by Vistaus** [comment]
Known bug:
"Right-click etc. not working on tweet rows. Just needs re-implementation."

**Comment by IBBoard** [comment]
Just saw that after you mentioned the other one was already known!

I'd skimmed that thread but not read the detail because it was getting a bit old now and there were lots of commits since then!
