### ISSUE TITLE
Auto scroll on new tweets does nothing then disables itself

### ISSUE THREAD

**Issue by jerblack** [baedert/corebird#834]
I just installed Corebird on Ubuntu 18.04 LTS and I was trying to make Auto Scroll on New Tweets work. After finally finding the hidden settings, I turned on the option, closed settings, and waited for the UI to move. Nothing. I checked and new messages had indeed come in, but no scrolling. I looked back in settings and the option was off again. I turned it back on and tried again, but again, no scroll and the option turned itself off. You said in another response that this feature is supposed to be working at the moment. Maybe I don't understand what you think the feature should be doing, but every other implementation I've seen of autoscroll pins the stream to the top and always moves to keep the newest tweet on top. That's not what happens here though. What did you design autoscroll to do and did you mean for it to turn itself off for some reason?

**Comment by baedert** [comment]
It's supposed to scroll to the top of the stream on new tweets, unless you already scrolled down. That's it,

**Comment by jerblack** [comment]
FWIW, it started working after I turned on the setting again, closed the app, and reopened it. Thanks.
