### ISSUE TITLE
Automatically refresh search?

### ISSUE THREAD

**Issue by JonnyTech** [baedert/corebird#835]
Is automatic refresh possible for searches? For example if I want to see all tweets for `#realDonaldTrump` and have corebird update every few seconds to display new tweets then how would I do that?

**Comment by baedert** [comment]
No that's not implemented.

**Comment by JonnyTech** [comment]
Ah, thanks for the quick reply - is there any way that I can achieve it, even with another similar program (are there any?)?

**Comment by baedert** [comment]
No idea, the search on twitter.com refreshes.
