### ISSUE TITLE
How do i fix this error?

### ISSUE THREAD

**Issue by SolarAquarion** [baedert/corebird#838]
corebird:ERROR:../src/CbMainWindow.c:660:cb_main_window_new: assertion failed: (IS_ACCOUNT (account))

**Comment by baedert** [comment]
The master branch is a development version. Use it if you want to work on corebird. If you just want to use Corebird and not work on it, use the `cb-1.7` branch.

**Comment by SolarAquarion** [comment]
My issue happened once I deleted my account from ~/.config/corebird.

**Comment by SolarAquarion** [comment]
Also deleted the dconf settings

**Comment by baedert** [comment]
Why would you do that manually? It's saved both in its own database and in the Corebird.db.
