### ISSUE TITLE
snap and spellchekcer

### ISSUE THREAD

**Issue by joancf** [baedert/corebird#841]
When running from snap 
it gives some warning at start like
gspell-WARNING **: iso_639.xml: Failed to open file “/usr/share/xml/iso-codes/iso_639.xml”: open() failed: No such file or directory

then in the application there is no language to choose for spell checker.

Do I have to install dictionaries/packages with snap? how can I install them?

System Linux mint 18.1
name:      corebird
summary:   Corebird Twitter Client
publisher: snapcrafters
contact:   https://github.com/snapcrafters/corebird/issues
license:   unknown
description: |
  Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It features inline
  image and video preview, creation of lists and favorites, filtering of tweets and full text
  search. Corebird is able to manage multiple Twitter accounts.
commands:
  - corebird
snap-id:      jpPjOVJYHmcVHb0EJVC6hVlq6eCEYkZ5
tracking:     stable
refresh-date: today at 00:25 CEST
channels:                    
  stable:    1.7.4 (97) 45MB -
  candidate: ↑               
  beta:      ↑               
  edge:      1.7.4 (97) 45MB -
installed:   1.7.4 (97) 45MB -

**Comment by diddledan** [comment]
That's a deficiency in the snap packaging. Please move this over to https://github.com/snapcrafters/corebird/issues so that Tim isn't overloaded with packaging-specific issues for packages they're not currently responsible for.

**Comment by joancf** [comment]
moved... well copied
