### ISSUE TITLE
Send button greyed out

### ISSUE THREAD

**Issue by orschiro** [baedert/corebird#843]
Dear all, 

I just installed the Flatpak version and intended to compose a simple tweet but regardless the content of the tweet, the send button remains greyed out. 

Can you please advise me what I am doing incorrectly?

Thank you!

![image](https://user-images.githubusercontent.com/170947/43832890-308e0274-9b09-11e8-8370-7817e793beb5.png)

**Comment by Vistaus** [comment]
I think it has to do with https://www.patreon.com/posts/corebirds-future-18921328
They're probably slowly phasing out every part of the API instead of all at once, starting with posting tweets.

**Comment by orschiro** [comment]
Thank you Heimen. 

Does this basically mean that Twitter can only be used from twitter.com for the future?

**Comment by Vistaus** [comment]
Yes, it does.

**Comment by orschiro** [comment]
Thank you!

**Comment by baedert** [comment]
FWIW that should be unrelated to whatever Twitter is doing. We only desensitivize the send button if no network connection can be established, so it may be a problem somewhere else. But still, you should look for an alternative.
