### ISSUE TITLE
The Site Streams and User Streams endpoints have been turned off. Please migrate to alternate APIs. See https://t.co/usss

### ISSUE THREAD

**Issue by hustler77** [baedert/corebird#844]
Since today I get the message 

The Site Streams and User Streams endpoints have been turned off. Please migrate to alternate APIs. See https://t.co/usss

when I start corebird from console and try to display the timeline

Debian buster - Corebird 1.7.4

**Comment by Vistaus** [comment]
That's because Corebird is dead due to Twitter's ridiculous API changes. See this post for more information: https://www.patreon.com/posts/corebirds-future-18921328

**Comment by baedert** [comment]
As said in the readme.
